### ISSUE TITLE
update when custom values

### ISSUE THREAD

**Issue by Nickholas** [IonDen/ion.rangeSlider#107]
Great component. I am working with it for a few hours and is great. I had only see one issue: when you use custom values despite numbers, the update method doesnt work fine. Could anybody check it?

**Comment by Ionut-Milas** [comment]
to and from need to be indexes data-from=agg.index(from.to_f)   data-to=agg.index(to.to_f)

**Comment by Giovancruz** [comment]
@IonDen, I updated your findle to understand what is this issue. If i understood, when you uses update, you need to use the index of array to set the new value, otherwise, it don't work, correct?

**Comment by IonDen** [comment]
@Giovancruz, yes. It uses indexes.
