### ISSUE TITLE
Using an object instead an array for the values property

### ISSUE THREAD

**Issue by Daniesy** [IonDen/ion.rangeSlider#112]
Hello again!

I've noticed that when initialised with the values option, the slider sets the corresponding input the position instead of the actual value selected. This requires further processing of the data, either after the form is submitted or with javascript when the slider value has changed.

I think it would be better to set the value property using a key-value pair system, where the key would be used as the value of the input and the associated value, would be displayed to the user. Thus, the values would be initialised like this `{"323":1, "324":2, "325":2}` and the data-values attribute could be set up like this `data-values="323:1, 324:2, 325:2"`. An array could be used too, the code would be almost exactly the same for both of the two ways.

I'm suggesting this, because whenever i used the slider, i initialised it with values from my database. After the form was submitted, i had to lookup the position sent to find the value, so, in the end i could find the corresponding id and make changes. I needed only the id. Using an object for the values property would simplify this cumbersome process.

Thanks! Great slider btw!

**Comment by IonDen** [comment]
#207
