### ISSUE TITLE
No fixed-ratio option?

### ISSUE THREAD

**Issue by dudinka** [IonDen/ion.rangeSlider#164]
I really like this plugin even before I used it, it has everything I need, except one thing: Fixed ratio.

Lets say I have the slider set at 100 and 150, with intervals of 10, so when I drag the start slide to 90, I would like the end slide move to 110. 
From the demos, I think I can manually do it with the onChange callback without much hassle, but I was curious to know if a feature like this is planned or been discussed before. It could really nail down this plugin.

**Comment by samzhang111** [comment]
Hi, I think the functionality in question is this: http://ghusse.github.io/jQRangeSlider/. When you click the middle of the range, you can slide the entire selection left and right.

**Comment by dudinka** [comment]
@samzhang111 That's exactly what I was talking about.

I actually used the Ion plugin and wrote something that could make it work properly, but the plugin you suggest here seems to support it natively, so I think I'll switch to it now.

Thank you!

**Comment by IonDen** [comment]
Hi all, yes it is there. Tnx for using.
