### ISSUE TITLE
can't drag slider on touchscreen laptop

### ISSUE THREAD

**Issue by andsat** [IonDen/ion.rangeSlider#166]
I have an Acer laptop with a touchscreen and a normal mouse. The range sliders seem to just ignore both mouse and touch input on Chrome and IE.

**Comment by SoundLogic** [comment]
:+1: thanks!

**Comment by IonDen** [comment]
Super.

**Comment by Samuel-Bie** [comment]
I know that this migth be old but, i am facing problems of dragging the slider on mobile divices i am using V 2.2.0. @IonDen
