### ISSUE TITLE
Invert range

### ISSUE THREAD

**Issue by skyksandr** [IonDen/ion.rangeSlider#169]
В своем проекте я использую слайдер с перевернутым диапазоном.
В этом случае у меня min: 4000, max: 1000 
Пример: http://skyderby.ru/ru/tracks/196

Я выполнял доработку плагина для версии полугодовалой давности. Версия 2.* выглядит очень привлекательной, не могли бы вы реализовать такую возможность в составе вашего плагина, чтобы не приходилось выполнять доработку каждый раз при выпуске новых версий?

**Comment by IonDen** [comment]
#234
