### ISSUE TITLE
Using grid markers on integer values only.

### ISSUE THREAD

**Issue by RWCHRISTIAANSE** [IonDen/ion.rangeSlider#171]
Hi,

When you use set the grid option to true, and you specify a small range, let's say 1 to 24, you get grid-markers on 0.5, 1, 1.5 and so on. I expect to get grid markers on  1, 2, 3 etc.

Is there anyway I can specify this? (From your examples it is not clear how to do this.)

This is what I used:

$("#range_34").ionRangeSlider({
    type: 'single',
    min: 1,  
    max: 24,
    hide_min_max: true,
    from: 10,
    step: 1,  
    grid: true,
    grid_snap: true,
    grid_num: 24,
    interval: 1,
    min_interval: 1,
    force_edges: false,
    prefix: 'ronde ',
  /\*  values: [
        01,02,03,04,05,06,07,08,09,10,11,12,
        13,14,15,16,17,18,19,20,21,22,23,24
    ]  */
});

Example:

![grid](https://cloud.githubusercontent.com/assets/5490091/5516669/783fc6e2-88ad-11e4-9b86-b7fbdaa37085.jpg)

See also: http://jsfiddle.net/RWCH/q586wnqz/

**Comment by shubhamjohar-BWES** [comment]
Is there a way to define the number of small steps in a customized manner for my needs?
