### ISSUE TITLE
From either To value falls to NaN or undefined

### ISSUE THREAD

**Issue by nyan-cat** [IonDen/ion.rangeSlider#174]
How to reproduce:

1. Go to demo page http://ionden.com/a/plugins/ion.rangeSlider/demo.html
2. Click and hold From either To of any slider.
3. Drag it to the left side of the document until mouse x-coordinate becomes = 0 (relative to the document).
4. Ok, now label says NaN (or undefined) and everything is screwed up :\

See attached screenshot. Reproduced in all browsers.

![irsbug](https://cloud.githubusercontent.com/assets/2917886/5599733/8fb15be4-92dd-11e4-9a46-0ff0bf51c4be.png)

**Comment by nyan-cat** [comment]
Ой, автор, оказывается, русский ^_^ Короче надо схватить from или to, и утащить до самого левого края страницы, и будет NaN / undefined.

**Comment by nyan-cat** [comment]
Лучше чинить не следствие, а причину. А причина в том, что в https://github.com/IonDen/ion.rangeSlider/blob/master/js/ion.rangeSlider.js#L501 (и аналогично далее) наличие e.pageX нужно проверять не неявным кастом в бул, а явно сравнивая с undefined ^_^

**Comment by IonDen** [comment]
Should be fixed in 2.0.4. Please check
