### ISSUE TITLE
Add CSS cursor style

### ISSUE THREAD

**Issue by nyan-cat** [IonDen/ion.rangeSlider#175]
Предлагаю добавить CSS cursor: pointer там, где можно кликать (.irs-line, .irs-bar), и cursor: move там, где можно схватить и таскать (.irs-slider).

**Comment by IonDen** [comment]
Я специально зафиксировал курсор, чтобы можно было проще целится в мелкие элементы слайдера. Если вас это поведение не устраивает, то вы можете легко модифицировать это, поправив ваш текущий скин.
