### ISSUE TITLE
why unpublish on npm?

### ISSUE THREAD

**Issue by fengmk2** [IonDen/ion.rangeSlider#176]
I saw https://www.npmjs.com/package/ion-rangeslider missing on npm.

**Comment by IonDen** [comment]
Hi, it was only test. In a week i will do normal publish on npm

понедельник, 5 января 2015 г. пользователь fengmk2 написал:

> I saw https://www.npmjs.com/package/ion-rangeslider missing on npm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IonDen/ion.rangeSlider/issues/176>.
>


-- 
*Denis Ineshin*
JavaScript developer | IonDen.com <http://ionden.com>

**Comment by shuvalov-anton** [comment]
@IonDen  +1 I need npm version of the module too

**Comment by Kobold** [comment]
+1, Looking forward to using this through npm.

**Comment by IonDen** [comment]
Should be on npm now. Please check.
