### ISSUE TITLE
feature request: non linear values

### ISSUE THREAD

**Issue by simonoop** [IonDen/ion.rangeSlider#178]
Great plugin. Excellent work. Wrapped it in an angular directive and works perfectly.
One request: non linear values out of the box would be a nice feature.

cheers!

**Comment by IonDen** [comment]
Hi, i will think about this. But you already can do this, by using values array. You can paste any numbers in there in any order.

**Comment by simonoop** [comment]
Hi. 
Yes, you're right and that's how I actually do it but imagine you have a price slider from 100 to 1000 step 1. You'd have to have an array with all those values. 

On January 11, 2015 7:45:19 AM WET, Denis Ineshin <notifications@github.com> wrote:
>Hi, i will think about this. But you already can do this, by using
>values array. You can paste any numbers in there in any order.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/IonDen/ion.rangeSlider/issues/178#issuecomment-69486491

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by IonDen** [comment]
Hi, it could be done now, using prettify function.
