### ISSUE TITLE
how can i take value for min and max from variable

### ISSUE THREAD

**Issue by ui-devendra** [IonDen/ion.rangeSlider#179]
Hi,

Is there a way by which i can declare the min and max value of the slider to be taken from a variable?

-Dev

**Comment by IonDen** [comment]
Hi, yes

```javascript
$('#range').ionRangeSlider({
    min: externalMin,
    max: externalMax
});
```

**Comment by ui-devendra** [comment]
it is not working this way...

Where should i declare the variables?

Thank You

**Comment by IonDen** [comment]
Anywhere: http://jsfiddle.net/xmeqn8nv/1/

**Comment by ui-devendra** [comment]
Hi Denis,

Thank you for your help :)
