### ISSUE TITLE
feature request: separate pre / postfix

### ISSUE THREAD

**Issue by mteAndy** [IonDen/ion.rangeSlider#181]
Hi,
is there a way to have a separate pre and postfix?
So the lables could read als Example:  "from 40 pcs"        "to 500 pcs"

**Comment by IonDen** [comment]
Hello, easy)
Just put space inside text, like this: " miles", " km"

**Comment by mteAndy** [comment]
Hi Den,
sorry for the misunderstanding :)
I meant a different prefix not the spaces, hehe.
I would like to have the left prefix "from" and the right prefix "to"

**Comment by IonDen** [comment]
Aaa)

Ok. Will think about it.

**Comment by mteAndy** [comment]
wow, faster than light ;)
cool

**Comment by IonDen** [comment]
Duplicates #278
