### ISSUE TITLE
Values looks like is expecting a string, not an array as shown in the demo

### ISSUE THREAD

**Issue by cintamani** [IonDen/ion.rangeSlider#182]
Hi there!! I've tried to set up my slider, and I set uo my values for the grid to be a js array (version 2.0.3 of the framework), and I get this error Uncaught TypeError: undefined is not a function on line 204 (data.values = data.values && data.values.split(",");) as actually the split method is undefined on an array. But the demo shows that values must be array not string. Is this a bug? Or I'm doing something wrong?

**Comment by IonDen** [comment]
Hello, please show the problem here: http://jsfiddle.net/IonDen/qv6yrjrv/

**Comment by cintamani** [comment]
http://jsfiddle.net/qv6yrjrv/50/ Done, can you take a look? Is maybe because the value is coming from the data-value on the node?

**Comment by cintamani** [comment]
Can you also please take a look to this strange behaviour and tell me why is doing that? http://jsfiddle.net/qv6yrjrv/51/ The slider is fixed at 2, and when you move it returns 0-1 values, instead of 1-2 values.

**Comment by IonDen** [comment]
Ok, look at #184 
It should be explained there.
