### ISSUE TITLE
Bug on range slider, when range 1-2 with values for the grid

### ISSUE THREAD

**Issue by cintamani** [IonDen/ion.rangeSlider#184]
http://jsfiddle.net/qv6yrjrv/51/ The main problem is not that the slider is selected on 2, but when you move it it returns values from 0 to 1 instead of 1 to 2

**Comment by cintamani** [comment]
http://jsfiddle.net/qv6yrjrv/52/ check also this

**Comment by cintamani** [comment]
In this one the visual part looks correct, but when you move the slider, is still returning 0 - 1 values instead of 1-2 http://jsfiddle.net/qv6yrjrv/53/

**Comment by IonDen** [comment]
Hi, thx for finding this problems. I will fix them soon.

**Comment by IonDen** [comment]
Okay friend. I checked your problem and this is not a bug. Look here:

In all 3 examples you use custom values array. This array overrides sliders MIN, MAX, FROM, TO and STEP params. Your custom array is base now. For example:

* values: ["a", "b", "c"]
* this is a normal array. It's length is 3. First item has index 0, last item is 2.
* So, sliders MIN now is 0, and sliders MAX now is 2 (first and last array indexes).
* To move FROM handle to "b", you should set it, using it's index inside the array. Here: from: 1

So, then you are using custom values - forget about MIN/MAX/STEP. And keep in mind that FROM and TO should be array's indexes.

About returned values, look in to objects description. It returns 4 numbers in that situation:

from: 0
from_value: "a",
to: 2,
to_value: "c"
