### ISSUE TITLE
heavy CPU usage when idle

### ISSUE THREAD

**Issue by augustblack** [IonDen/ion.rangeSlider#186]
When I have multiple sliders on the, but none in action, CPU is around 100%

If I profile this scenario with chrome, it looks like the requestAnimationFrame call on updateScene is the culprit.   

It seems there are requested events for update even when there is no mouse on the browser frame.

You can see this by opening the chrome inspector and hitting record in the profiler and leaving the mouse offscreen.

**Comment by FiloSpaTeam** [comment]
Me too with Firefox but no with Chromium.

**Comment by FiloSpaTeam** [comment]
The high CPU comes from the updateScene when slider is hidden, maybe it's a problem render a display-none object.
I'm trying to solve the problem myself.
If i'll have a solution i'll fork and push a commit! ;-)

**Comment by FiloSpaTeam** [comment]
Found a solution. See pull request.

**Comment by IonDen** [comment]
Should be fixed in 2.0.7
