### ISSUE TITLE
Hiding rangeSlider

### ISSUE THREAD

**Issue by bjaergager** [IonDen/ion.rangeSlider#187]
In a setup where the number of items in a rangeSlider are dynamic, determined by another rangeslider in fact, I end up in a situation where there is only 1 option to select, this obviously doesn't make any sense, so I wan't to hide the rangeSlider but can't really make it work.

What I ended up doing is to use slider.destroy() - which removes the slider from UI - but then I'm unable to recreate the slider without getting an error : 
TypeError: this.options is null
...)},update:function(a){this.is_update=!0;this.options.from=this.result.from;this....

I could really use some help on this one.
Regards,
Mark

**Comment by IonDen** [comment]
Hi. Should be fixed in 2.0.4. Try the last demo here: http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html
