### ISSUE TITLE
Multiple Ranges

### ISSUE THREAD

**Issue by GadgetUK** [IonDen/ion.rangeSlider#19]
Hi,

Would it be possible to have multiple ranges. To define for example multiple sections of the day.

**Comment by aDu** [comment]
I would love to see this feature also.

**Comment by oriadam** [comment]
Hi, just wanted to add my scenario for this feature, I'm building a grading ladder editor.
User cut the full-range to multiple consecutive ranges, and give a name to each range.

![spec-grading-ladder](https://user-images.githubusercontent.com/2786617/50149664-7b7ac600-02c4-11e9-9c92-f91e3b1abd9b.png)

Great work there btw!

**Comment by IonDen** [comment]
@oriadam, does this demo serve your needs? https://jsfiddle.net/IonDen/tdvxs3zL/

**Comment by oriadam** [comment]
@IonDen  
Thanks for the demo! 
But no, the user should be able to add and remove multiple knobs, creating multiple sub-ranges by changing the cutting point for each range.
In the example above there are 6 ranges: 0-33, 33-50, 50-66, 66-80, 80-90, 90-100
Each range also have a name.

I'm attaching a more detailed explanation.
![spec-grading-ladder2](https://user-images.githubusercontent.com/2786617/50164773-3a96a780-02ec-11e9-8f44-1b6930f6e77a.png)

**Comment by IonDen** [comment]
Ah, got it. Sorry, 2.x can't do it. 3.x will, but it is not ready yet.

**Comment by oriadam** [comment]
That would amazing :) Do you have a time estimation?

**Comment by IonDen** [comment]
@oriadam, not yet. I'm family man and have small time to work on it :)

**Comment by PCasafont** [comment]
Any news on this one?

**Comment by hisenberg1** [comment]
Is this feature implemented? I saw a note in December 2018 that 3.x will support it.
