### ISSUE TITLE
Click and down events are propagated

### ISSUE THREAD

**Issue by wch** [IonDen/ion.rangeSlider#191]
When a click or down event occurs, the event continues to propagate, which can cause some strange behavior.

In this fiddle, dragging the slider also causes the entire draggable panel to move:
  http://jsfiddle.net/winstonchang/6pnedx8c/

I think the solution is to to add `e.stopPropagation()` after `e.preventDefault()` in `pointerClick` and `pointerDown`.

**Comment by IonDen** [comment]
Hello, i did this for a reason. 
You could listen something on body, for popup close for example, and slider should not block events bubble for that, or close tooltip, or something else.

Your example is very rare. But i will think to adding the option to stopPropagation if needed.

**Comment by wch** [comment]
Thanks, that makes sense. Having an option for it would be very useful.

**Comment by IonDen** [comment]
I thought much about this and still think that plugin should be full transparent for events. If you want to stop event propagation somewhere, you should do it outside the slider. In some container maybe.
