### ISSUE TITLE
Slider with values array can slide past zero giving undefined

### ISSUE THREAD

**Issue by scompto** [IonDen/ion.rangeSlider#192]
This is present even in the example on the main page using the values ["one", "two", "three"]. If you scroll the minimum slider quickly past the minimum, you break the element and cause undefined to be displayed. 

![screen shot 2015-01-28 at 1 02 54 pm](https://cloud.githubusercontent.com/assets/5091144/5943574/1d3fedc6-a6ee-11e4-9473-b1887043dfdc.png)

UPDATE:
This happens on all sliders, not just the value ones. Just drag very fast to the left for the lower slider.

**Comment by FiloSpaTeam** [comment]
I think when mouse go to screen border.
If you have a large screen this not happens unless you touch screen limit width. I can see for this bug.

**Comment by FiloSpaTeam** [comment]
Found a solution. Maybe not the best but works.
The problem was in the pointerMove function.
When your mouse is on x = 0 the OR (||) use second condition but the second is undefined because is usefull only for touches ;-)
Just committed.

**Comment by IonDen** [comment]
Hi, i will investigate this.

**Comment by scompto** [comment]
I similarly looked into this. It is an issue with sliding to a screen border. The calculated "real_x" value in that case is NaN, where as your logic is assuming a numeric value. This solved it for me:
<code>       
 if (isNaN(real_x) || real_x < 0) {
   real_x = 0;
 } else if (real_x > real_width) {
   real_x = real_width;
 }
</code>

**Comment by FiloSpaTeam** [comment]
I solved with:
> if (typeof(x) === 'undefined')
>>x = 0

in the pointerMove function :)

**Comment by IonDen** [comment]
Should be fixed in 2.0.4. Please check.
