### ISSUE TITLE
Problem with the slider

### ISSUE THREAD

**Issue by fcferreira29** [IonDen/ion.rangeSlider#195]
Hello,

i am having a problem with the slider, here it is:

I have a page with tabs, when i fill alll the fields and submit to the confirm page, all the sliders are well and the values are well placed in the confirm page, when i press "change values" and return to the previous page, if i dont click on the tabs that contains the sliders and go straight to the last tab, when i submit all the values come to 0. If i click the tabs with the sliders, the submit goes well.

Thanks in Advance,

Fabio Ferreira

**Comment by IonDen** [comment]
Interesting. I will investigate this.

**Comment by IonDen** [comment]
Hi, should be fixed in 2.0.5. Please check
