### ISSUE TITLE
bower install outputs the main files without a directory structure, breaking .irs-slider background

### ISSUE THREAD

**Issue by kowsheek** [IonDen/ion.rangeSlider#196]
My project's bower install outputs to a `lib` directory. When outputting ionrangeslider's main files, the output looks like the image attached.

This breaks the look of elements with `.irs-slider` since the image isn't found in the CSS anymore.

Ideally, the `sprite-skin-flat.png` image should be copied to an `img` directory via grunt (not sure if bower can do it). Similar to how jquery outputs its files.

Thoughts?

![whythishappen](https://cloud.githubusercontent.com/assets/164881/6032344/f8842b0e-abd5-11e4-9596-92882c8234ea.PNG)

**Comment by IonDen** [comment]
Hi, i will check this.

**Comment by birdage** [comment]
ran in to the same issue i just did a grunt copy to the right dir then changed the ion css
`grunt.file.copy('...../lib/iontimeslider/img/sprite-skin-nice.png', '..../static/img/sprite-skin-nice.png')`
then 
`https://github.com/birdage/ion.rangeSlider/commit/0e3ae3dad15c535ada536f84f265a60d7c7bdfbc`

**Comment by kowsheek** [comment]
@birdage I did the same, I'd imagine there's a solution using bower's settings.

**Comment by IonDen** [comment]
Bower is deprecated
