### ISSUE TITLE
"NaN" and "undefined" values when dragging to negative

### ISSUE THREAD

**Issue by andrecavallari** [IonDen/ion.rangeSlider#199]
This bug is fired only when the browser is maximized, If i drag the "from" pin to a negative value, until it reaches the left bord of the screen, it turns the value into "NaN", or in case of using the values as array: "undefined"

A pic of this issue:
![issue](https://cloud.githubusercontent.com/assets/1050485/6132086/6f1a9d46-b137-11e4-90ea-9b02b8da27f3.jpg)

**Comment by FiloSpaTeam** [comment]
I found a solution some days ago.
You can see my Fork and pull request.

**Comment by IonDen** [comment]
Hello, i just finish another plugin update. So, it is turn of this plugin now. Fixes will be released soon.

**Comment by andrecavallari** [comment]
Thanks!!
