### ISSUE TITLE
Keyboard focus problem

### ISSUE THREAD

**Issue by fcferreira29** [IonDen/ion.rangeSlider#204]
Hello,

i am having a problem with the focus event, 

here is the problem, i have a condition in my slider, that checks if the value is >0 and <10, then if it is between 1 to 9 it moves directly to 10, 

if i use the mouse to slide the focus mantains, but when i use the keyboard, after i click 1 time, the slider goes directly to 10 (that is ok, because is supose to do so) but then i loose the focus on the slider with the keyboard, and to make any changes to it i have to click with the mouse to have the keyboard event active again,
(i am using the onFinish event)
thanks in advance,

Fabio Ferreira

**Comment by IonDen** [comment]
Hello, Fabio.

Here is playground: http://jsfiddle.net/IonDen/qv6yrjrv/
Maybe you can set up your config here? It will help me to trace your problem.

**Comment by fcferreira29** [comment]
I have configured the slider has i have it here, for some reason it is not behaving has i have it here, but you can get the basic idea from it, hope it helps, when you "click" the slider and touch on the keyboard to the 1% the bar goes to 10% and then you loose the keyboard focus, Thanks, Fabio Ferreira Date: Tue, 17 Feb 2015 07:26:29 -0800From: notifications@github.comTo: ion.rangeSlider@noreply.github.comCC: fcferreira@msn.comSubject: Re: [ion.rangeSlider] Keyboard focus problem (#204)Hello, Fabio.

Here is playground: http://jsfiddle.net/IonDen/qv6yrjrv/
Maybe you can set up your config here? It will help me to trace your problem.

**Comment by fcferreira29** [comment]
Hello Dennis, i am sending you this message just to check if you have been able to solve / understang my problema, Thanks, Fabio Ferreira Date: Tue, 17 Feb 2015 07:26:29 -0800From: notifications@github.comTo: ion.rangeSlider@noreply.github.comCC: fcferreira@msn.comSubject: Re: [ion.rangeSlider] Keyboard focus problem (#204)Hello, Fabio.

Here is playground: http://jsfiddle.net/IonDen/qv6yrjrv/
Maybe you can set up your config here? It will help me to trace your problem.

**Comment by IonDen** [comment]
Hi again. But you didn't provided link to your example.
