### ISSUE TITLE
Marks on slider's line

### ISSUE THREAD

**Issue by IonDen** [IonDen/ion.rangeSlider#205]
Add support for array of marks (small red vertical lines on the main line). Could help to visualize some key points.

**Comment by unconditional** [comment]
What key points do you think of except the starting values?
How would they be defined?

With starting marks the idea was to make it declarative like the 'shadow' feature - you just say you need it and it's calculated and created automatically.

Regarding the styles - the suggested code adds divs with classes (*irs-mark*, *mark-single*, etc) so they can be styled as needed.

**Comment by IonDen** [comment]
Hi, this feature, potentially, could be used in many different cases. And using this marks only for "from" and "to" starting points is bad idea. Because it is only your case. Other people maybe will find new ways to use this.

**Comment by unconditional** [comment]
Cool, I've no problem with that. But what are those different cases?

**Comment by IonDen** [comment]
That is the problem, we can't imagine them right now. But some of plugin users will.

**Comment by andrevlins** [comment]
That's a real cool feature, really useful.

**Comment by DougManuel** [comment]
Not sure if it is the same concept, but it would be great to be able to have both labels and values in an array, or have more customizable labels. 

My use case is the following:
Stats folks often use percentile boundaries like 0, 10th, 25th, 50th, 75th, 90th, 100. These are nominal. Not ordinal or categorical.

I'd like to have a slider that can have single percentile increments (return values from 1 to 100), but with only labels as described above. 

Please suggest a work around, if you can come up with one.

**Comment by IonDen** [comment]
@DougManuel, your question is off topic for current ticket.

**Comment by IonDen** [comment]
The idea got an extension in #348

**Comment by prakashnsm** [comment]
![image](https://cloud.githubusercontent.com/assets/3167450/21422035/d8484916-c85b-11e6-9feb-9467de25030f.png)

Javascript Code: 


$("#eliminateRange").ionRangeSlider({
			  hide_min_max: true,
			  keyboard: true,
			  min: 0,
			  max: 100,
			  from: 10,
			  to: 40,
			  type: 'double',
			  /*step: 1,*/
			  grid: true,
			  from_fixed : true,
			  onFinish : function(a){
				  $('#eliminate .irs-to.tag').attr('style', $('#eliminate .irs-to').not('.tag').attr('style'));
			  },
			  onChange : function(o){
				  eliminateTagStyleUpdate();
			  },
			  onUpdate : function(o){
				  $('#eliminate .irs .irs').append($('#eliminate .irs-from').clone().text(" C ").attr('title','Current').addClass('tag'));
				  $('#eliminate .irs .irs').append($('#eliminate .irs-to').clone().text(" T ").attr('title','Target').addClass('tag'));
				  $('#eliminate .irs .irs').append($('#eliminate .irs-single').clone().text(" C — T ").attr('title','Current - Target').addClass('tag'));
				  
				  setTimeout(eliminateTagStyleUpdate,100);
			  }
		  });

`function` eliminateTagStyleUpdate(){
			  
			  $('#eliminate .irs-from.tag').attr('style', $('#eliminate .irs-from').not('.tag').attr('style'));
			  $('#eliminate .irs-to.tag').attr('style', $('#eliminate .irs-to').not('.tag').attr('style'));
			  
			  var sty = $('#eliminate .irs-single').not('.tag').attr('style').split('left: ');
			  var v = eval(sty[1].replace('%','')) + 1.3;
			  
			  $('#eliminate .irs-single.tag').attr('style', sty[0]+'left: ' + v.toFixed(5) + '%');
		  }

CSS:

span.irs-from.tag,
span.irs-to.tag, 
span.irs-single.tag {
    top: 165%;
    width: 16px;
}

span.irs-single.tag {
	width: 34px;
}

span.irs-from.tag:after,
span.irs-to.tag:after,
span.irs-single.tag:after {
    position: absolute;
    display: block;
    content: "";
    top: -9px;
    left: 50%;
    width: 0;
    height: 0;
    margin-right: -5px;
    overflow: hidden;
    border: 5px solid transparent;
    border-bottom-color: #50237F;
    bottom: 0px;
    margin-left: -5px;
}

span.irs-from.tag:after {
	border-bottom-color: #B90276;
	left: 50%;
}

span.irs-to.tag:after {
	border-bottom-color: #50237F;
	left: 50%;
}
