### ISSUE TITLE
Request: custom data for grid

### ISSUE THREAD

**Issue by javierdechile** [IonDen/ion.rangeSlider#207]
Is there a way to easily put custom data on grid?

i.e. I would like to display a grid with: ["low", "medium", "high"] for values [0, 500, 1000]. Is that possible somehow?

**Comment by IonDen** [comment]
Hi, not now, sorry. In future, maybe i will add this.

Now you can only emulate this feature. Disable the grid through options and than draw your own grid with labels you wish under the slider.

**Comment by IonDen** [comment]
Hi, this is workaround for this: http://jsfiddle.net/IonDen/r108eq2c/

But i realized that in fact this ticket duplicates #151
