### ISSUE TITLE
Slider's increment doesn't equal 'step' value

### ISSUE THREAD

**Issue by withjuh** [IonDen/ion.rangeSlider#208]
There seems to be a bug where the slider's step isn't equal to the step value specified in 'step'.

I discovered the issue while trying to work with with moment.js times. You can reproduce the issue with these values:

      type: "double",
      grid: true,
      min: 1425218400000,   // 6 AM
      max: 1425279600000,  // 11 PM
      from: 1425218400000,
      to: 1425279600000,
      step: 300000                // 5 minutes
      prettify: function (num) {
          return moment(num, 'x').format("h:mm A");
      }

You'll find that the increments will then sometimes be 4 minutes, sometimes 5, sometimes 6. I wonder if the issue is related to the rounding in calcWithStep.

**Comment by IonDen** [comment]
Hi, will look at it.

**Comment by IonDen** [comment]
Should be fixed in 2.0.13. Please check this demo: http://jsfiddle.net/IonDen/w1ucb8bm/

**Comment by withjuh** [comment]
Fix verified. Thanks!
