### ISSUE TITLE
Handle not draggable on IE 11 and Windows 8.1 Store App

### ISSUE THREAD

**Issue by kashban** [IonDen/ion.rangeSlider#211]
I'm trying to replace ionic-range-slider with this plugin but this is also not working on IE 11 or in a Cordova Windows 8.1 Store App. 

The slider is displayed correctly, the handle lits up when the mouse is hovering above it, but I cannot drag it. The slider is embedded in an ionic content page, which is scrollable. It seems as by grabbing the handle the touch / mouse down event is catched by the scrolling container instead of the slider. 

I don't have a touch device at hand, so I cannot check whether it's draggable by touch.

**Comment by kashban** [comment]
Got it, it had to to with the ion-content element which stole drag events from the slider. After replacing this with a mere div element, it now works.

Strange thing though: The slider still moves after releasing the mouse button, but that will be another issue.

**Comment by anthonnyc2** [comment]
Hi @kashban i'm getting the same problem as you.
"The slider is displayed correctly, the handle lits up when the mouse is hovering above it, but I cannot drag it"

can you help me with this? How you can fix this issue i don't understand your fix comment.

**Comment by kashban** [comment]
Hi @anthonnyc2 , basicly I ditched <ion-content> and replaced it with a <div> container. This eliminates the scroll container which probably consumed the scroll events meant for the slider. 

Or the other way around: The slider does not work within an <ion-content>-block.

So if on your page you have "<ion-content>...</ion-content>" just replace it with "<div>...</div>".

**Comment by anthonnyc2** [comment]
Thanks @kashban .. and another question.. You find a way to fix this problem "The slider still moves after releasing the mouse button"?

**Comment by kashban** [comment]
@anthonnyc2 Unfortunately I am no longer on that project, so I hadn't had an opportunity to look into this any further. As far as I was able to track this down it has something to do with Microsoft naming some touch and mouse event handlers different than the rest of the world. And ionic isn't ready for it (Windows touch clients were not even supported officially half a year ago). 

I guess it requires some patching of ionic code to get this to work.

**Comment by IonDen** [comment]
Hello @anthonnyc2. Please create demo of your bugs here: http://jsfiddle.net/IonDen/726L0aj5/
This demo uses latest version of plugin and jQuery.

Also, if you will really find a bug, please create separate ticket here.

**Comment by anthonnyc2** [comment]
Hi @IonDen. The problem is that i'm using ionicframework and now i'm trying to implement your library. I don't know if you count with that.

**Comment by IonDen** [comment]
Sorry, know nothing about ionic framework.
