### ISSUE TITLE
feature request: HTML5 'range' input polyfill

### ISSUE THREAD

**Issue by texclayton** [IonDen/ion.rangeSlider#212]
HTML 5 specifies a "range" type <input>.
This plugin could easily be modified to act as a polyfill for range inputs.  I have written a wrapper that creates the rangeslider and initializes it using the 'min', 'max', and 'step' atttributes.
The only difficulty is that HTML 5 does not include support for a double-handled slider.  I had to work around differing browser's behavior when the value attribute  is, for example, "10;90".  The value returned by jQuery's 'prop' method was different than the value of the attributes.  Chrome ignores this value and sets it to the midpoint.  Firefox and IE10 use the first number and ignore the rest of the value.  IE8 doesn't support 'range' inputs so it leaves the value alone and returns the actual value text.
A simple fix may be to use $inp.attr("value") instead of $inp.prop("value") in the initialization.

**Comment by IonDen** [comment]
Hi, setting value via attr will not affect the form value. So, we can't support type "range" now.
