### ISSUE TITLE
MouseUp TouchEnd Event not fired on IE 11 / Windows App

### ISSUE THREAD

**Issue by kashban** [IonDen/ion.rangeSlider#213]
I am using ion.RangeSlider on an ionic page and on IE and in a Windows App the mouse up / touch end is not recognized. Thus it is not possible to release the handle, it sticks to the mousepointer and the finish-eventhandler is not called.

I also tried different jquery versions (1.11.1 to 2.1.3), not change. 

I suspect some issue with the ionic framework, like <ion-view> or <ion-content> are not working with ion.RangeSlider on IE, but I already replaced <ion-content> with a simple <div>

Anybody else using this combination and having issues with IE and Windows Store Apps?

**Comment by IonDen** [comment]
Hi. I think the problem is that your framework stops propagation of some events, like mouseup and touchend. Plugin adds the event handler for that events to window and is waiting for them to bubble up there. If your plugin stops event somewhere in the dom tree, nothing i can do.

**Comment by kashban** [comment]
Thanks for the quick answer. Sounds resonable. Any hint on how to test event bubbling?

**Comment by IonDen** [comment]
Look in to frameworks code and search for .stopPropagation method, or "return false"

**Comment by kashban** [comment]
Ok, thanks, I'll do that. Strange thing though (or maybe not) is it works in all browsers except Internet Explorer 10/11 and Windows Scripting Host (Win 8.1 Store apps).

**Comment by kashban** [comment]
To make it work I had to disable two stoppropagation() commands in ionic framework. I will post a ticket to ionic about this and reference it from here.

**Comment by IonDen** [comment]
Hi, glad you could find the solution.
