### ISSUE TITLE
RequireJS Support

### ISSUE THREAD

**Issue by mikelittman** [IonDen/ion.rangeSlider#214]
It doesn't appear that this plugin has AMD/RequireJS support.
Can this be implemented?

**Comment by swapnil0545** [comment]
Can we use this plugin with requirejs?

**Comment by IonDen** [comment]
Hello, @swapnil0545, i never tested it what way. But i suppose it should work as any other jQuery-plugin.
Soon i will try to add native amd support to plugin, but this is not a priority.
