### ISSUE TITLE
Problem with the grid values[]

### ISSUE THREAD

**Issue by iacmru** [IonDen/ion.rangeSlider#216]
Hi! Thanks for awesome plugin!

I'm try to use this on my project (CMS Drupal 7.x):
```javascript
$("input#edit-field-power-value").ionRangeSlider({
  type: 'single',
  grid: true,
  min: 8.2,
  max: 62.5,
  from: 8.2,
  values: [8.2, 12.6, 12.7, 20.9, 25.1, 29.8, 36.9, 39.4, 51, 62.5]
});
```
Works great, but range position ignore `from` option and place value `51` every time. Please help me for this small issue.

**Comment by IonDen** [comment]
Hi, what happened?)

**Comment by iacmru** [comment]
Sorry, my bad) I'm didn't understand "how work option `values`" before post this issue. Now everything is fine. Thanks again for this plugin!
