### ISSUE TITLE
multi ionRangeSlider: update function with from value

### ISSUE THREAD

**Issue by amontanari** [IonDen/ion.rangeSlider#217]
Hi,
i have a particular case, in a web page i insert 3 different ionRangeSlider and i implemented a lock function that permit to change value of 3 slider when a user change a value of one of these.
I have a problem in userinterface the update function redraw all the slider and for a instant the pointer of slider change in 0 value and after in correct value.

(this problem is not present on mozilla on mac, but present on all others browser)

I want optimize the redraw of slider when is called updateFrom function in order to prevent the passage to 0 value.

Can help me to find if is possible optimize the redraw.

a example of call update on other sliders:
```
$("#compGrafico2-1").ionRangeSlider({
                            values: $scope.lista_focali,
                            from: from,
                            prettify: true,
                            grid: true,
                            postfix: " mm",
                            hide_min_max: true,
                            hide_from_to: false,
                            onChange: function(data){
                                // IF LOCK IS CHECKED
                                if($scope.lock == true){
                                    --update a highchart chart
                                    // check if is present second slider
                                    if($scope.compareElements.length > 1){
                                        var slider2 = $("#compGrafico2-2").data("ionRangeSlider");
                                        slider2.update({
                                            from: data.from,
                                        });
                                        --update a second highchart chart
                                        // check if is present third slider
                                        if($scope.compareElements.length == 3){
                                            var slider3 = $("#compGrafico2-3").data("ionRangeSlider");
                                            slider3.update({
                                                from: data.from,
                                            });
                                            --update a third highchart chart
                                        }
                                    }
                                }else{
                                    // is not a problem :)
                                    --update a only highchart chart present
                                }
                            }
                        });
```

Thank you for your attention, best regards.

**Comment by IonDen** [comment]
Hello.
I am not really sure, that i understood your problem, but maybe we can simulate it in a playground.
Here is an example of 3 connected sliders: http://jsfiddle.net/IonDen/qaLpd2mu/

Maybe you can set up this to emulate your problem?

One thing about your code, you should not search for the slider instances each time in onChange function. This function is called very very ofter and you should only use it to get slider data and call some other functions, but not search the DOM.
