### ISSUE TITLE
Middle handler

### ISSUE THREAD

**Issue by dgarciap** [IonDen/ion.rangeSlider#218]
Hi,
This widget looks amazing and I'll like to use it in my proyect. But sadly I'm with a case in which I need three handlers.

"From" and "To" to choose a range and a third handle to choose a concrete point inside this range.

Are there plans to implement this function soon?

**Comment by IonDen** [comment]
Hello, no. This plugin was designed only for 1-2 handlers. Adding support for multiple handlers is in distant plans. 
But still, you can solve your task another way, using 2 sliders, like this: http://jsfiddle.net/IonDen/x3r8zngb/
