### ISSUE TITLE
More than one per use...

### ISSUE THREAD

**Issue by zarza** [IonDen/ion.rangeSlider#221]
I want to build a hour range selection from 1 - 24 hours, but I want a second one to select free times, for example breaks, lunch and so on.

Any idea? Is it possible with this? Two in one? One for hours and other for breaks...

Thank you for any feedback.

**Comment by IonDen** [comment]
Hi, maybe you need something like this? See example with 2 connected sliders: http://jsfiddle.net/IonDen/x3r8zngb/2/

**Comment by zarza** [comment]
Thank you for that.
