### ISSUE TITLE
Get full range

### ISSUE THREAD

**Issue by ChenOhayon** [IonDen/ion.rangeSlider#222]
Hi,

I would like to get all values within the selected range.
For example:
Range is: D,E,F,G,H,I,J,K,L,M,Fancy
Selected range is from **F** to **M**
Requested result is **F,G,H,I,J,K,L,M** instead of F;M

Is it possible?

Great work on the plugin, thank you! :)
Chen

**Comment by IonDen** [comment]
Hi, no. Plugin returns only selected values and their indexes in array. So, if you have your array saved in variable, you will get range easily: http://jsfiddle.net/IonDen/hoz483sL/

**Comment by ChenOhayon** [comment]
Hi,

Great workaround :)

Thanks for your replay!
