### ISSUE TITLE
Destroy Slider

### ISSUE THREAD

**Issue by zarza** [IonDen/ion.rangeSlider#224]
Hello, and thank you for your time.

I have some "issues" destroying the slider. I set up an on/off checkbox/bottom.

But when I re-enable (press on again) slider keep last information. So, I tried:

            var slider = $("#"+ daytoken +"_slider").data("ionRangeSlider");
            slider && slider.destroy(); //destroy slider
            $('#'+ daytoken +'_input').val(''); //Reset var input

What I want is when the user turn it off, it just get back to defaults, and not last selected.
I have confirmed that input is reseted and clean, but when ON back, it just populated with old slider selection.

Thank you for your comments.

**Comment by IonDen** [comment]
Hi, then you create slider, input immediately gets it's value. I don't really understand, what do you expect, after you recreate the slider instance?

**Comment by zarza** [comment]
For example, if default is 1 to 10, and I manually changed it to 2 to 11, when I recreate it I hope to get 1 to 10 again, not 2 to 11.

**Comment by IonDen** [comment]
Look at the destroy demos. That is how it works. But if you wish, at first, before destroy, you should call reset method.
