### ISSUE TITLE
When initializing both handles to the max value, handles are locked 

### ISSUE THREAD

**Issue by deonclem** [IonDen/ion.rangeSlider#228]
I've created a jsfiddle to illustrate my point : 

https://jsfiddle.net/xqc8eLvr/

You can't move the handles when 'from' and 'to' are set on init to the max value, it looks like it's because the 'type_last' class is not added to the 'from' handle, so you can't grab it.

**Comment by IonDen** [comment]
Hi, tnx.

**Comment by IonDen** [comment]
Fixed in 2.0.8
