### ISSUE TITLE
I want to set from and from_max as 0.

### ISSUE THREAD

**Issue by eswarreddy43** [IonDen/ion.rangeSlider#231]
Actually i am using two sliders. The sum of the two selected values should not be more than 100. User can select 100 from one slider also. In that case i need to restrict the user selection on second slider. If user selects < 100 from first slider then only we need to give the ability to select on second slider. But the second slider is selectable of anything if the from, from_max are 0.  

I need to restrict the user as he do not select any thing on the second slider if the first slider value is 100.

How will this possible without disabling the slider?

**Comment by IonDen** [comment]
Hello, you can do it this way for exaple: http://jsfiddle.net/IonDen/x3r8zngb/

**Comment by marcoseliasb** [comment]
The problem I'm having on the #237 is to do the same thing, bu i'll have 3 or 4 sliders to sum to 100.
why I cant click on the line?

**Comment by IonDen** [comment]
Oook, now i understand the problem. Will fix in #253
