### ISSUE TITLE
Is it possible to move the slider using the from-to labels ?

### ISSUE THREAD

**Issue by govindpatel** [IonDen/ion.rangeSlider#233]
I actually want my slider to slide using the from and to label. 
That is when someone click and drag the from or to label, the slider should move.

I tried to see the doc (http://ionden.com/a/plugins/ion.rangeSlider/en.html) , but found nothing.

what should I do so that my slider move using those label?

https://cloud.githubusercontent.com/assets/2056756/7346000/ccfab81e-ecf7-11e4-9658-c50cf248656b.png

**Comment by IonDen** [comment]
Hello, this is not in slider design. But i will think about adding this feature in future.
If you really want this now, you can try to add this feature by yourself. Look into bindEvents method, here: https://github.com/IonDen/ion.rangeSlider/blob/master/js/ion.rangeSlider.js#L500

**Comment by jaredmcqueen** [comment]
@govindpatel @IonDen did you ever figure out how to bindEvents?  I'm working on it now but am stuck.  Any help would be greatly appreciated!

**Comment by IonDen** [comment]
Hi, i think it will be ready before weekend.

**Comment by IonDen** [comment]
Feature added by default in 2.0.13. Please check the demos.

**Comment by mikila85** [comment]
not working, and demos dont have any "label" click..

**Comment by adriandmitroca** [comment]
Hi @IonDen, can you tell what's current status for that?

**Comment by IonDen** [comment]
@adriandmitroca it is working.
http://ionden.com/a/plugins/ion.rangeSlider/en.html
try to drag the labels

**Comment by Anuanirudhan** [comment]
Hi @IonDen , Is this label clicking functionality is working now? not the from, to labels in the top.

**Comment by IonDen** [comment]
@Anuanirudhan, this are not labels, this is grid. Click on grid will work from 3.x

**Comment by Anuanirudhan** [comment]
Thanks, @IonDen  :). When will you plan to release 3.x?

**Comment by IonDen** [comment]
Before end of the year probably. I requires super huge amount of work

**Comment by iryska** [comment]
> Before end of the year probably. I requires super huge amount of work

Hi, any news about 3.x release? Client asked about grid click :(
