### ISSUE TITLE
Set twice from parameter in grid

### ISSUE THREAD

**Issue by llemurya** [IonDen/ion.rangeSlider#236]
This is the [screenshot](http://static.md/24f60db08dadc7fdede4a9b2fc24c36f.png) with the bug and I created a simple [demo](http://jsfiddle.net/vx15o8nf/) on jsfiddle to reproduce this bug.

**Comment by IonDen** [comment]
Hi, thx for mention this. But this is not really a bug, in some cases automatic grid could be not very accurate. To fix this, use grid_snap param. Like this: http://jsfiddle.net/IonDen/vx15o8nf/1/

**Comment by llemurya** [comment]
@IonDen thanks for the quick reply.
