### ISSUE TITLE
Request: Slide step with diff values

### ISSUE THREAD

**Issue by shanytc** [IonDen/ion.rangeSlider#239]
Hey,
I was wondering if it is possible to show grid values (array) and still step (advance the slider) by amount I want?

for example:
from:1
to:40,
grid values: 5,10,15,20,25,30,35,40

but the slider can still advance by 1! ->  1,2,3,4,[5],6,7,8,9,[10]

I don't want the steps be related to the values.

**Comment by IonDen** [comment]
Hi, no.
But you can set up this with "grid_num" property.
http://ionden.com/a/plugins/ion.rangeSlider/demo_advanced.html

**Comment by shanytc** [comment]
grid_num is not good! it won't give the desired solution

**Comment by IonDen** [comment]
It could give you the closest possible solution. Values array was designed for another kind of situations, and it overrides FROM and TO to 0 -> values array length

**Comment by shanytc** [comment]
yes i know,
check my last reply.

> On May 16, 2015, at 11:26 AM, Denis Ineshin <notifications@github.com> wrote:
> 
> It could give you the closest possible solution. Values array was designed for another kind of situations, and it overrides FROM and TO to 0 -> values array length
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/IonDen/ion.rangeSlider/issues/239#issuecomment-102588614>.
> 

- Shany

**Comment by IonDen** [comment]
I understood this question. Look here: https://github.com/IonDen/ion.rangeSlider/issues/207
I already have feature request for that feature. But, as you see, it have nothing common with values array.

**Comment by shanytc** [comment]
OK now i can see that you have the request as well.

well, maybe that means we really need that featured enable already? :D

> On May 16, 2015, at 11:30 AM, Denis Ineshin <notifications@github.com> wrote:
> 
> I understood this question. Look here: #207 <https://github.com/IonDen/ion.rangeSlider/issues/207>
> I already have feature request for that feature. But, as you see, it have nothing common with values array.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/IonDen/ion.rangeSlider/issues/239#issuecomment-102589312>.
> 

- Shany

**Comment by shanytc** [comment]
hey,
Until you code you own version,
I already coded my own solution, hopefully you will implement your own version soon.

> On May 16, 2015, at 11:32 AM, Shanytc g <shanytc@icloud.com> wrote:
> 
> OK now i can see that you have the request as well.
> 
> well, maybe that means we really need that featured enable already? :D
> 
>> On May 16, 2015, at 11:30 AM, Denis Ineshin <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> I understood this question. Look here: #207 <https://github.com/IonDen/ion.rangeSlider/issues/207>
>> I already have feature request for that feature. But, as you see, it have nothing common with values array.
>> 
>> —
>> Reply to this email directly or view it on GitHub <https://github.com/IonDen/ion.rangeSlider/issues/239#issuecomment-102589312>.
>> 
> 
> - Shany
> 

- Shany
