### ISSUE TITLE
Associative array

### ISSUE THREAD

**Issue by NMFES** [IonDen/ion.rangeSlider#243]
Hi.
I would like to use assoc array (or object) values for slider. 

var Obj = {"First": 1, "Second": 2, "Third": 3}; (or key => value)

$("#example").ionRangeSlider({
    values: Obj
});

And then from slider we take an normal int value for using on server side. But now we need somehow convert value "First" into value "1".
Is it possible to use assoc array in slider? maybe in future?

**Comment by IonDen** [comment]
Now, slider works with values array almost the same.
["a", "b", "c"] in the slider will behave like from: 0, to: 2

**Comment by NMFES** [comment]
No, it's not the same.

I need to use keys not only from 0 to ... 2 (integer and increment). 
Array can be like that: {"First amount": 13300, "Second amount": 3000, "Third": 13000}
User select "Second amount" and we can without problems get value for this pick (3000).

Or another example. 
Build slider with distance values: {"20 meters": 20, "900 meters": 900, "1 kilometer": 1000}
User picks "1 kilometer" and we receive value for this pick (1000).

**Comment by IonDen** [comment]
I am not really sure, looks the same with #207

**Comment by NMFES** [comment]
It seems my idea is not new :)
In #207 exactly what i need. But also without a decision.
Hope it will be realised in future versions.
