### ISSUE TITLE
Input Box Getting when Slider Integrated

### ISSUE THREAD

**Issue by neni1006** [IonDen/ion.rangeSlider#244]
Hi,
I integrated the slider on my site http://tekglintsoftsol.com/projects/ajt-new/  .. U can check in left side bar used to filter in particular ranges. But it was getting input box.. On reloading again and again, slider was getting ones in 10 reloads the browser. Why that input box is getting and how to resolve it..

Thanks in advance

**Comment by IonDen** [comment]
You have very many errors on the page. Open console and look (F12 in Chrome Win)

**Comment by neni1006** [comment]
I followed the integrating procedure clearly..

**Comment by IonDen** [comment]
Try to google "including jquery and plugins to the page". Plugin will not
work until you fix other problems and critical exceptions on the page

четверг, 28 мая 2015 г. пользователь neni1006 написал:

> I followed the integrating procedure clearly..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IonDen/ion.rangeSlider/issues/244#issuecomment-106449484>
> .
>


-- 
*Denis Ineshin*
JavaScript developer | IonDen.com <http://ionden.com>
