### ISSUE TITLE
Breaking bug on 2.0.8: Cannot read property 'values' of undefined (Fiddle provided)

### ISSUE THREAD

**Issue by tmikaeld** [IonDen/ion.rangeSlider#246]
http://jsfiddle.net/d3jd3eba/1/

2.0.7 works fine, 2.0.8 doesn't.

**Comment by IonDen** [comment]
Hi, yes i see. Fix will be ready soon.

**Comment by IonDen** [comment]
Fixed in 2.0.9

**Comment by tmikaeld** [comment]
Thanks for the quick fix, great plugin!
