### ISSUE TITLE
Ion.rangeSlider How to change the slider on manual input ?

### ISSUE THREAD

**Issue by sushant357** [IonDen/ion.rangeSlider#249]
How to change the slider on manual input ...
Please kindly reply

**Comment by IonDen** [comment]
```javascript
// Start slider
$("#range_50").ionRangeSlider({
    type: "double",
    min: 0,
    max: 1000,
    from: 200,
    to: 500,
    grid: true
});

// Save slider instance to var
var slider = $("#range_50").data("ionRangeSlider");

// Change slider, by calling it's update method
slider.update({
    min: 100,
    max: 500,
    from: 150,
    to: 450,
    step: 50
    // etc.
});
```

**Comment by sushant357** [comment]
Hi,
Really thanks

Thanks & Regards,
Sushant Jadhav
UI Designer

**Comment by IonDen** [comment]
No problem.

**Comment by sushant357** [comment]
Please check this link
I have done my test on the below link when I move the slider point I got value above the input box but when i tried to input some value in the input box, slider unable to move...
how its works ?
http://jsfiddle.net/sushant357/29uykptf/1/

**Comment by IonDen** [comment]
Hello, i already have a test playground for that: http://jsfiddle.net/IonDen/zqh4o7uc/
Please check it.

**Comment by sushant357** [comment]
Thanks for your Help I Appreciate it ...



*Thanks & Regards,*
*Sushant Jadhav*

**Comment by sushant357** [comment]
Hi There is one minor issue is remaining,
My Max limit is 100
I set my max_postfix: "+", lyk this
 & if i typed 200 in input box then slider slide to 0 how can i handle this ?

**Comment by sushant357** [comment]
Hi Sir,
Thanks i got that answer which i asked u earlier thanks for your help

**Comment by IonDen** [comment]
No problem.

**Comment by SinglaShivani** [comment]
Hi sir
how to Auto move the slider till end on clicking on play button

**Comment by IonDen** [comment]
@SinglaShivani, just use "update" method by timer.

**Comment by sujit-q2pay** [comment]
Hi,
I need a help
I want to implement dynamic value with step.
for example
step: 1,
value: [0, 10, 100, 1000, 10000, 100000, 1000000]

**Comment by IonDen** [comment]
@sujit-q2pay, i can't understand your request.

**Comment by vavilons84** [comment]
Hello,
I want to pass value to slider from php. Could You give me some advice?
BR

**Comment by IonDen** [comment]
@vavilons84, hi. Passing from PHP means that you build page on backend. During that process, you can change any part of outcoming web page. Just predefine slider values in data-attributes for example.

**Comment by vavilons84** [comment]
Hallo Den,

Maybe my question was not clear :( I have page with slider and when user pick some value and click the button at form, slider value passes correctly, but when page reloads selected value of slider returns at ones defined in javascript. I want to make that slider shows new value passed in $_POST["xxx"]. Could You advice?

**Comment by IonDen** [comment]
@vavilons84, after page reloads of course this will happen. To avoid this, you should rewrite slider value in hidden input field, assigned to slider.

**Comment by vavilons84** [comment]
@IonDen nope, value to hidden input filed pased correctly after form submition, but visual representation on slider remains as it is set at js.

![screen shot 2018-05-22 at 13 57 57](https://user-images.githubusercontent.com/39519651/40361102-85bfd23c-5dc8-11e8-877e-99990e2e21e3.png)

**Comment by IonDen** [comment]
@vavilons84, try also put the value in to data-from attribute

**Comment by IonDen** [comment]
@amarbhatia, like this: https://jsfiddle.net/IonDen/gk6e85md/

**Comment by amarbhatia** [comment]
> 
> 
> @amarbhatia, like this: https://jsfiddle.net/IonDen/gk6e85md/
@IonDen 
> 
> You can call functions like updateValues1, updateValues2, updateValues3 and so on for example.

no, lets say i have 2 html pages and 2 javascripts, now i want to call a function named myFunction() on finish in 1st html page and myFunctionNew() in 2nd html page on the onFinish method dynamically

**Comment by muarachmann** [comment]
Hello i am trying to update my slider it updates but not retaining the `min` and `max` values.
Here is my code
```
$("#slider").ionRangeSlider({
        type: "double",
        min: 0.05,
        max: 30.00,
        step: 0.01
})
```
![Screen Shot 2019-07-02 at 9 57 35 AM](https://user-images.githubusercontent.com/16350814/60499261-03984a00-9cb0-11e9-8db7-f8ccf5172105.png)

And how i do the update after getting the slider instance - `slider =
$("#slider").data("ionRangeSlider");`
```
slider.update({
            type: "double",
            min: 0.05,
            max: 30.00,
            from: min_val,
            to: max_val,
            step: 0.01
        });
```
After update it removes the labels
![Screen Shot 2019-07-02 at 9 58 33 AM](https://user-images.githubusercontent.com/16350814/60499281-0b57ee80-9cb0-11e9-8aad-af72752fb87e.png)

The updates works fine but the double handles of the `min` & `max` disapears. Please any help would be appreciated
