### ISSUE TITLE
Option to show input text

### ISSUE THREAD

**Issue by cassianotartari** [IonDen/ion.rangeSlider#250]
Hello.

I looking into issues and docs but didn't found any register about how to show the input text that is hidden. I see that is ``irs-hidden-input`` that hides the input but library adds an ``readonly`` option too.

My idea is to add an slider for price field but I will limit it just for a most common range. I would like to show input for the cases that user needs an higher or some specific value that slider doesn't cover.

Thanks!

**Comment by IonDen** [comment]
Hi, you should use separate inputs for that. Check this demo: http://jsfiddle.net/IonDen/zqh4o7uc/

**Comment by cassianotartari** [comment]
Nice!! :smile:  I'll study the code. I'll try to adapt to use with https://github.com/igorescobar/jQuery-Mask-Plugin

**Comment by cassianotartari** [comment]
Did the trick to use with mask modifying this methods:
```js
    var updateValues = function () {
        $from.prop("value", from*100);
        $to.prop("value", to*100);
        $from.mask('000.000.000.000.000,00', {reverse: true});
        $to.mask('000.000.000.000.000,00', {reverse: true});
    };

    $from.on("change", function () {
        from = +$(this).cleanVal()/100;
        if (from < min) {
            from = min;
        }
        if (from > to) {
            from = to;
        }

        updateValues();
        updateRange();
    });

    $to.on("change", function () {
        to = +$(this).cleanVal()/100;
        if (to > max) {
            to = max;
        }
        if (to < from) {
            to = from;
        }

        updateValues();
        updateRange();
    });
```

![screenshot from 2015-06-03 09 53 40](https://cloud.githubusercontent.com/assets/3017642/7960371/7a8e209c-09d6-11e5-86c4-76044a532919.png)
