### ISSUE TITLE
Exponential/Binary step

### ISSUE THREAD

**Issue by cassianotartari** [IonDen/ion.rangeSlider#252]
Hello!

I would like to know if is possible to create an exponential step to slider. I don't know exactly how to express but the idea is a price slider as I asked before with the ruler showing the small numbers more than the big numbers. For example, the range is 0 to 10 million, 40% of width slider focus on values between 0 and 500 thousand, 20% of with to 500 to 2 million, ... so the user can easily choose and value like 1200 with step 100. Simple using 0 to 10 million with 100 step is almost impossible to set 1200

I hope I made myself clear.

**Comment by IonDen** [comment]
Hi, it is possible with prettify function. You can write anything inside it.
