### ISSUE TITLE
Firefox caching values after refreshing page.

### ISSUE THREAD

**Issue by marcoseliasb** [IonDen/ion.rangeSlider#254]
When I refresh a page, some sliders come with the same values as previous the refresh. Even though I had set the "from".

This is using the same code as #237

**Comment by IonDen** [comment]
I will check.

**Comment by brazenvoid** [comment]
please give a workaround for this, thanks.

**Comment by IonDen** [comment]
Please add  autocomplete="off" to your inputs.
Check this: http://stackoverflow.com/questions/2486474/preventing-firefox-from-remembering-the-input-value-on-refresh-with-meta-tag
