### ISSUE TITLE
Custom Grid Value

### ISSUE THREAD

**Issue by JaserAkuly** [IonDen/ion.rangeSlider#255]
I am currently using this slider and I honestly love it. Great work!

Wanted to know if there was a possible way to make the steps:1 but the grid to show custom values of [1, 500, 1000, 1500, 2000+]. I also would like to have a minimum of 1 instead of the usual 0. 

The issue i come across is being able to start at 1 and then have 500 show instead of 501. Also how can i add "+" to the end of 2000?

I have added an image of my slider, please let me know any feedback you may have for me. 

![capture](https://cloud.githubusercontent.com/assets/8867922/8118000/100e3504-1052-11e5-8d5c-73913afb01f9.PNG)

**Comment by IonDen** [comment]
Hi, to add "+" at the end, use max_postfix param:
http://jsfiddle.net/IonDen/9ovaydxh/

To set up your situation, you can use prettify function. This is the key for all this stuff.
Like this: http://jsfiddle.net/IonDen/9ovaydxh/2/
But this is not very honest calculation)

**Comment by JaserAkuly** [comment]
Thank you very much, I appreciate the help provided. 
 
For the max_postfix problem, I apologize for not properly stating my question. I was trying to find out a way to add it to the grid 2000 mark point. I have already added a "+" to the max_postfix, but I would like to add it to the grid max as well. See screenshot below:

![screen shot 2015-06-15 at 10 46 35 am](https://cloud.githubusercontent.com/assets/8867922/8164085/8389154c-134c-11e5-87ca-e419ee86bd25.png)

As for the prettify function, what does "n" stand for?

Once again thank you for the assistance.

**Comment by IonDen** [comment]
Hi, there is no max_postfix on grid. This is a minor bug.

**Comment by JaserAkuly** [comment]
Ok, Thank you. 

Another question, is there a way I can land to a specific value on the slider when coming from a another page on my site: For example I click on a link on another page and when landing on this particular page it will start from a specific value, lets 10 instead of the default value of 20?

**Comment by IonDen** [comment]
Yes, set FROM param.

**Comment by IonDen** [comment]
Created complex ticket for that: #278
