### ISSUE TITLE
Request: Minimum Range Option

### ISSUE THREAD

**Issue by Nosferican** [IonDen/ion.rangeSlider#256]
It would be useful to have an option to handle the minimum range. In other words, instead of the default which is that the lower input is never greater than the second one, that there be some minimum distance in between these. For example, set the minimum distance be one step less than the second input, i.e., not being allowing the inputs to be the same.

**Comment by IonDen** [comment]
Hi, this option already exists. Check the description and look at min_interval and max_interval options. This is what you are looking for.

**Comment by Nosferican** [comment]
You are totally right. I guess Shiny has not import it to the SliderInput, yet.
