### ISSUE TITLE
object  can't  saving it's instance to var 

### ISSUE THREAD

**Issue by rubylab** [IonDen/ion.rangeSlider#257]
Hi, I use  ion-rangeslider with meteor ,but something went wrong when I wan't to  update  the value  of the object ,I read [docs]( https://www.npmjs.com/package/ion-rangeslider) ,it tells :
```js.
var slider = $("#range_01").data("ionRangeSlider");
slider.update({
    from: 300,
    to: 400
});
```
However ,it  doesn't work    and result 
just like  [this](http://www.jqueryscript.net/demo/Flexible-Touch-Friendly-jQuery-Range-Slider-Plugin-Ion-RangeSlider/)
```
var slider = $("#someID").data("ionRangeSlider"); 
//  return  undefined  
$("#someID").data();   
//return  Object {isActive: true}
```
How can I  get  the instace to var , so  that  I can update the value ? tks

**Comment by IonDen** [comment]
Hi.

### You have input field
```html
<input type="text" id="testID" name="test" value="" />
```

### Set up the slider to this input:
```javascript
$("#testID").ionRangeSlider({});
```

### Get link to the instance:
```javascript
var slider = $("#testID").data("ionRangeSlider");
```

### Update the slider:
```javascript
slider.update({
    from: 150
});
```

**Comment by rubylab** [comment]
@IonDen   Hi ,thanks for your answer,I'm so sorry didn't  respose it in time due to the holiday .
I  use it  just as u write ,but  it doesn't work. when I use 
```js
  $('#bp_slider').data()  # it return only Object {isActive: true}
```
![111](https://cloud.githubusercontent.com/assets/4611267/8345716/f92cce66-1b25-11e5-9f39-7724b03c01a8.png)

the  attribute  of  data("ionRangeSlider") doen't work ,my programming  language is Meteor,maybe some conflict  exits.what should I do ? Thank you !

**Comment by IonDen** [comment]
Oh, version 1.9.1. :disappointed: 
Update to the latest 2.0.10 and everything will work.

**Comment by iamrommel** [comment]
Ow.. that work for the latest version

**Comment by RanaGit** [comment]
@IonDen Hi, var slider = $("#ionrange_AM").data("ionRangeSlider"); still giving undefined, I am using bootstrap & angularjs in my page. Pls suggest

**Comment by IonDen** [comment]
@RanaGit, slider instance should be created before you are trying to save it to variable.

**Comment by RanaGit** [comment]
slider instance created within angularjs controller
$("#ionrange_AM").ionRangeSlider({
            min: $scope.AMmin,
            max: $scope.AMmax,
            from: $scope.AMmin,
            to: $scope.AMmax,
            step: 1,
            type: 'double',
            //prefix: "",
            //maxPostfix: "",
            //prettify: false,
            //hasGrid: false,
            onFinish: function (data) {
                $scope.AMmin = data.fromNumber;
                $scope.AMmax = data.toNumber;
            }
        });

**Comment by RanaGit** [comment]
code follows as:
$scope.AMTypeRadClick = function (AMTypeVal){
            if (AMTypeVal == 'AMDays') {
                $scope.AMmin = $scope.AMminDays;
                $scope.AMmax = $scope.AMmaxDays;
                //slider.reset()
                //$("#ionrange_AM").ionRangeSlider({
                slider.update({
                    min: $scope.AMmin,
                    max: $scope.AMmax,
                    from: $scope.AMmin,
                    to: $scope.AMmax,
                });
            }
            if (AMTypeVal == 'AMYears') {
                $scope.AMmin = $scope.AMminYrs;
                $scope.AMmax = $scope.AMmaxYrs;
                //slider.reset()
                //$("#ionrange_AM").ionRangeSlider({
                $scope.slider.update({
                    min: $scope.AMmin,
                    max: $scope.AMmax,
                    from: $scope.AMmin,
                    to: $scope.AMmax,
                 });
            }
        };

**Comment by IonDen** [comment]
You should do it like this:

```javascript
// Init slider
$("#ionrange_AM").ionRangeSlider({...});

// Save it in to var
var slider = $("#ionrange_AM").data("ionRangeSlider");

// Now, it is usable and you can call methods
slider.update({...});
slider.reset();
```

**Comment by RanaGit** [comment]
Thx a lot.....its working perfectly fine....

**Comment by RanaGit** [comment]
I just change the variable to scope variable as it is within anjularjs controller
var $scope.slider = $("#ionrange_AM").data("ionRangeSlider");
$scope.slider.update({...});
