### ISSUE TITLE
Maximum value and increments

### ISSUE THREAD

**Issue by kellettemma** [IonDen/ion.rangeSlider#258]
Hi,

I am having an issue with this slider in regards to the maximum value and increments. Depending of the value of the increment I cannot reach the max value.  

I can see a similar issue here: https://github.com/IonDen/ion.rangeSlider/issues/247 Is there any update on when this will be fixed?

Thanks,
Emma

**Comment by IonDen** [comment]
Hi, very soon, 2-3 days.

**Comment by kellettemma** [comment]
Hi Denis,

Is there any update on this? This is currently causing a blocker for the project I am working on.

Thanks,
Emma

**Comment by IonDen** [comment]
Hi, this weekend will be a fix, i think.

**Comment by IonDen** [comment]
Hi again. Should be fixed in 2.0.11. Please check
