### ISSUE TITLE
Adding custom values for labels and set custom container for slider

### ISSUE THREAD

**Issue by Tantacula** [IonDen/ion.rangeSlider#260]
Привет. Хотелось бы иметь возможность добавлять кастомные метки для задаваемых значений в слайдере, чтобы на слайдере отображалась метка, а в инпут попадало соответствующее ей значение. Перебор в onChange решает проблему, но это грязный путь.

Также хотелось бы иметь возможность инициализировать слайдер внутри любого блока, а не только рядом с инпутом, к которому он привязан, а у самого инпута иметь возможность снять readonly опциями (опять же решается созданием скрытого инпута и пересылкой значений в необходимый инпут, но это лишний элемент, который нафиг не нужен на странице и выглядит костылем).

**Comment by IonDen** [comment]
Привет, первое можно решить так: http://jsfiddle.net/IonDen/r108eq2c/ и это отличное решение, не нужно пихать в слайдер слишком много всего, сложно будет пользоваться.

Это очень рискованно, так как если снять readonly то юзер сможет записать туда любую фигню и сломать слайдер. А тут задача другая.
