### ISSUE TITLE
Material design skin

### ISSUE THREAD

**Issue by mvujica** [IonDen/ion.rangeSlider#261]
Hi,
Thanks for this great control! Excellent.
I'm trying to create skin based on Google Material Design. Everything is fine, I created .png file and skin looks great but since slider and hover slider are different in size there is some flickering when one try to grab the slider. Not a big issue (slightly visually annoying) but it would be fine if you could point me in right direction to solve this. 

Attaching skin image, css at the link:
https://drive.google.com/file/d/0Bz4wDnHeXT1OVUVjWVFFQURTR28/view?usp=sharing

Thanks,
Marko. 
![sprite-skin-material2](https://cloud.githubusercontent.com/assets/11364617/8258612/9b2820b8-16b6-11e5-984d-bc63823709aa.png)

**Comment by IonDen** [comment]
Hi, maybe you can provide a demo here: http://jsfiddle.net/IonDen/y81j67qh/
just fork and replace a flat skin in to yours.

**Comment by mvujica** [comment]
Thanks, I finally solved it, it took me a while to figure out the metrics of png file and css. I tried to fork project but I'm unable to upload a .png file via web, not much a github user myself. If you want I can email you the files, didn't try all the options but skin works for basics, it's nice purple material-ish design slider.

**Comment by IonDen** [comment]
Hi, good to here what you solved your problem, but i meant to fork jsfiddle demo)

**Comment by cadilhac** [comment]
It would be great to have an official material design skin. No plan to add one?

**Comment by IonDen** [comment]
@cadilhac, i think i will include some in to 3.x
