### ISSUE TITLE
События сладера

### ISSUE THREAD

**Issue by panasyuk** [IonDen/ion.rangeSlider#266]
Здравствуйте.
Наткнулся на вот такую историю:
При инициализации срабатывает событие START. Честно говоря, я ожидал, что onStart будет работать, когда я начну таскать хэндл.
С другой стороны, начало перетаскивания хэндла можно отследить по срабатыванию CHANGE, а окончание изменения по событию FINISH. Но (в version 2.0.11 Build: 327) сразу после FINISH сдледует опять CHANGE. И из-за этого приходится городить код, который запомнит, что перед текущим CHANGE был FINISH и событию CHANGE срабатывать необязательно.
Подобная неоднозначность рождает и другие аномалии в коде.
Считаю правильным следующий способ генерации событий:
START - только в начале перетаскивания хэндла
CHANGE - при каждом изменении позиции хэндла
FINISH - только в конце перетаскивания
UPDATE - только при изменении значения программно

**Comment by IonDen** [comment]
Привет, взгляните еще раз на демо, на вид работает так же как и было.
http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html

Если быстро быстро дергать слайдер, то видно что финиш срабатывает после последнего change.

Но я это конечно проверю на всякий случай. По поводу колбэка onStart, тут я с вами не согласен, оно должно происходить при запуске, так чтобы любой внешний код мог быть синхронизирован со слайдером, даже если никто слайдер потом не трогал.

**Comment by panasyuk** [comment]
Проверил еще раз:
```javascript
# код
$("#range_43").ionRangeSlider({
    type: "single",
    min: 0,
    max: 100,
    from: 50,
    keyboard: true,
    onStart: function (data) {
        console.log("onStart");
    },
    onChange: function (data) {
        console.log("onChange");
    },
    onFinish: function (data) {
        console.log("onFinish");
    },
    onUpdate: function (data) {
        console.log("onUpdate");
    }
});
```
```
# вывод
(23) onChange # Двигаю хэндл
onFinish # Отпускаю хэндл
onChange
(21) onChange # Двигаю хэндл
onFinish # Отпускаю хэндл
onChange
(18) onChange # Двигаю хэндл
onFinish # Отпускаю хэндл
onChange
```
Но если кликать на линейку, то сначала onChange, а потом onFinish.

**Comment by IonDen** [comment]
Повторяющийся тикет, скоро будет исправлено. См: #270
