### ISSUE TITLE
The documentation does not make clear how to access value slider is set to.

### ISSUE THREAD

**Issue by oi-sendai** [IonDen/ion.rangeSlider#267]
One possible solution I can see might be for the slider to update the initial input element with the value. At the moment the only way I can find to access the value is to catch the change event and capture the resulting html in `<span class="irs-single">262</span>` via jquery. This seems like it's possibly not the correct way to achieve this, especially since the rest of the plugin seems so comprehensive and well thought out, however looking at the docs I can see plenty of ways to modify the slider params but no clear instruction on how to capture the result. For context I'm writing it into angular directive, so my particular use case is to update a scope value as the range moves, however I feel that anyone trying to get started with with this plugin would be looking for similar sort of feedback before delving into the advanced configuration options which are so clearly set out. Perhaps I'm missing something, however I still think the clarity of the documentation on this is an issue worth noting. Thanks for your work on this, having tried a number of plugins I've really enjoyed my experience with ion.rangeSlider so far.

**Comment by IonDen** [comment]
Hi, there are several ways to get the value from slider. First, and most common way is to use callbacks (onStart, onChange, onFinish, onUpdate). This callbacks get data object as their first argument with all plugin data.
```javascript
onChange: function (data) {
     console.log(data.from); // value of left/single handle
     console.log(data.to); // value of right handle
}
```

The socond way is to subscibe on base inputs 'change' event
```javascript
$(".input").on("change", function () {
    var value = $(this).prop("value");
    console.log("Value: " + value);
});
```

All this stuff can be found in "interactions demo", here: http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html

**Comment by IonDen** [comment]
Made little update to readme files.
