### ISSUE TITLE
Проблема с интервалами более 10 000 000 единиц.

### ISSUE THREAD

**Issue by BoBaHbl4** [IonDen/ion.rangeSlider#269]
Добрый день.
Столкнулся со следующей проблемой:
Скрипт используется для отображения интервала от 0 до 20 000 000 (для выбора количества показов). Пользователь может выбрать значение используя слайдер, а может ввести через поле ввода. При вводе "руками" значения через поле обнаружил следующее:
При вводе нечётных значений слайдер неверно их отображает. Если, к примеру, ввести 1 (11, 21, 111 и т.д.) слайдер переместит ползунок на 2 (12, 22, 112 - соответственно). Так же с 3, 5, 7, 9.

Методом перебора обнаружил что проблемы начинаются, когда интервал слайдера прописывается значением превышающим 10 000 000 (точно уже определить сложнее). Причем иногда он некорректно работает на нечетных числах, иногда на чётных.

Пример кода с проблемой:
http://free-coder.info/index_v2_parallax.html#tarifSection
Первый слайдер со значением 20 000 000 — работает с описанными выше проблемами. Второй с интервалом до 2 000 000 — без проблем.

Хотел узнать каким образом возможно решить эту проблему, если с ней кто-либо сталкивался до меня.

**Comment by IonDen** [comment]
Привет, скорее всего имеет место недостаточная точность округления для очень больших чисел, буду смотреть.

**Comment by IonDen** [comment]
Должно быть исправлено в 2.0.12. Проверьте

**Comment by BoBaHbl4** [comment]
Проверил — при вводе все значения отображаются корректно.
Спасибо за оперативное обновление!
