### ISSUE TITLE
Issue with decimal for years

### ISSUE THREAD

**Issue by sushant357** [IonDen/ion.rangeSlider#271]
My code is like this:
type: "single",
min: 0.6,
max: 6.0,
from: 0.6,
step: 0.1,

if I want to slide on 2.11 is directly go on 3 its logically correct but its wrong when its for years bcoz 12 months how can i solve this...?
please help asap
Advance thanks

**Comment by IonDen** [comment]
Hi, you should change step to 0.01
http://jsfiddle.net/IonDen/3rrwzgk2/
