### ISSUE TITLE
can not set step value when working with dates and time using moment.js

### ISSUE THREAD

**Issue by gisellecruz** [IonDen/ion.rangeSlider#273]
When working with dates and time using moment.js, it seems I can not specify the step value. For example, Max = current datetime and Min = datetime from a day ago. I want my steps to be shown per minute. What actually happens when moving the slider is that not every minute is shown.

**Comment by IonDen** [comment]
Hi, i will check this.

**Comment by gisellecruz** [comment]
Thank you.

**Comment by IonDen** [comment]
Should be fixed in 2.0.13. Please check this demo: http://jsfiddle.net/IonDen/w1ucb8bm/
