### ISSUE TITLE
How to custom the number of labels the ion.rangeslider displays?

### ISSUE THREAD

**Issue by leosbrf** [IonDen/ion.rangeSlider#275]
I am using the ion.rangeslider and sometimes the container element is not big enough to show labels for all values. I would like to customize the way labels are shown. Something that only display labels every 2 steps (or 10 or 100, etc).    
I checked the demos page but I didn't see how you set those values. For example, [here](http://ionden.com/a/plugins/ion.rangeSlider/en.html) there are only two ticks between the 1 thousand and 2 thousand labels.

**Comment by IonDen** [comment]
Hi, maybe you may provide some screenshot of your problem? And some drawing of the result you want to achive?

**Comment by leosbrf** [comment]
Hi Denis,

I have set the minimum and maximum values to -20 and 20. I also added two values before -20. My array of options is ['NULL', 'N/A', -20, -19.75, -19.50, -19.25, ....., 20]. But as you see in the image below, the slider is too small to show all the options.

![image of rangeslider](https://raw.githubusercontent.com/leosbrf/images/master/rangeslider.png)

I would like to display the label just for some of the options. For example, in my array I would like to display the labels for ('NULL', 'N/A', -20, -15, -10, -5, 0, 5, 10, 15, 20). The result that I wish (sorry, but I'm no good with mspaint):

![image of rangeslider](https://raw.githubusercontent.com/leosbrf/images/master/rangeslider_exit.png)

**Comment by IonDen** [comment]
Hi, i understand your problem.
This happends because grid collisions module is still in beta stage.
If you have too much values, please disable snap to step option.

As about grid labels, i already have similar request: https://github.com/IonDen/ion.rangeSlider/issues/207
