### ISSUE TITLE
ion.rangeSlider.js and ion.rangeSlider.min.js seem to have different behaviour

### ISSUE THREAD

**Issue by sebastianstoelen** [IonDen/ion.rangeSlider#277]
I'm working with moment.js to display dates on the slider. Herein I found different behaviour for the .js and .min.js file, both version 2.0.12. When using the .min file, the dates get displayed correctly, but there is no diapason between the two sliders of a "double" slider. When I use the .js file, there is a diapason, but the timestamps are not converted to a proper date format.

**Comment by IonDen** [comment]
Hi, please provide some demo here http://jsfiddle.net/IonDen/09u17wg7/
and please tell the source there you did get the files.

**Comment by sebastianstoelen** [comment]
Hi,

I’ve added my code here http://jsfiddle.net/09u17wg7/8/ <http://jsfiddle.net/09u17wg7/8/> . I use a custom css skin, the basis I got from a Metronic theme, preview here. http://www.keenthemes.com/preview/metronic/theme/templates/admin4/components_ion_sliders.html# <http://www.keenthemes.com/preview/metronic/theme/templates/admin4/components_ion_sliders.html#> The js and min.js files I got from http://ionden.com/a/plugins/ion.rangeSlider/en.html <http://ionden.com/a/plugins/ion.rangeSlider/en.html>. Thanks for your quick response.

**Comment by IonDen** [comment]
Ok, i see. You are using old skin names. They changed in 2.x
irs-diapason is now irs-bar please copy styles from some other skin.

**Comment by IonDen** [comment]
http://jsfiddle.net/IonDen/09u17wg7/9/ see, the bar is here

**Comment by sebastianstoelen** [comment]
Okay, thanks for your help!
