### ISSUE TITLE
How to dynamically set values 

### ISSUE THREAD

**Issue by chavika** [IonDen/ion.rangeSlider#279]
I have one textbox which allows user to input values.i need to change the slider according to textbox input in runtime .how can i achieve this.

**Comment by IonDen** [comment]
Hello, @chavika 

You may do it that way: http://jsfiddle.net/IonDen/mvrfg2vc/

**Comment by chavika** [comment]
Thanks IonDen..Appreciate the quick response

**Comment by IonDen** [comment]
No problem.

**Comment by abhijiy** [comment]
I want to set dynamic min and max value.I have used " <ion-range-slider #sliderElement type="double"  [min]="priceRange.min" max="{{priceRange.max}}" from="{{priceRange.min}}" to="{{priceRange.max}}" hide_from_to="true" prefix="{{currencySymbol}}"
                  postfix=".00"   (onFinish)="getFilterByRange($event)" ></ion-range-slider>"

Values are set but the slider is not working. Can you please help me?

**Comment by IonDen** [comment]
@abhijiy, what do you mean by dynamic values?

You want to change them before slider start, or after?
If after - here is the demo: http://jsfiddle.net/IonDen/mvrfg2vc/

**Comment by ed-walpole-on-pc** [comment]
I think the demo is broken now, I get this error: 

"<a class='gotoLine' href='#73:8'>73:8</a> Uncaught TypeError: $range.ionRangeSlider is not a function"

Apologies if I'm wrong!

**Comment by IonDen** [comment]
Demo was outdated. Check it again: https://jsfiddle.net/IonDen/mvrfg2vc/
