### ISSUE TITLE
how can i get slider's associated input name?

### ISSUE THREAD

**Issue by okliv** [IonDen/ion.rangeSlider#280]
i have multiple sliders on my layout and every of them is initialised correctly with:

    $range.ionRangeSlider({
        type: "double",
        min: $(this).data().min,
        max: $(this).data().max,
        prettify_enabled: false,
        grid: true,
        grid_num: 10,
        drag_interval: true,
        data_prefix: $(this).data().prefix,
        onFinish: function (data) {
            $.post('/path', {---> current_input_name <---: data.from+';'+data.to})
        }
    });

but i can't get how to construct onFinish post request with slider values and it's *name*

    <input type="text" class="js-range-slider" ---> name="my_unique_input_name" <--- data-prefix="$" data-max="100" data-min="0"/>

thank you!

**Comment by IonDen** [comment]
Hi, @okliv. Look here:
```javascript
Obj: {
    "input": object,    // jQuery-link to input
    "slider": object,   // jQuery-link to sliders container
    "min": 0,           // MIN value
    "max": 1000,        // MAX values
    "from": 100,        // FROM value
    "from_percent": 10, // FROM value in percents
    "from_value": 0,    // FROM index in values array (if used)
    "to": 900,          // TO value
    "to_percent": 90,   // TO value in percents
    "to_value": 0       // TO index in values array (if used)
}
```

This is the object you get in to <code>onFinish: function (data) {</code> data attribute.
First property input - is the jQuery object with the original input.

So you can get inputs name this way:
```javascript
onFinish: function (data) {
    var $input = data.input;
    var name = $input.prop('name');
    // ok you have name now!
}
```

**Comment by okliv** [comment]
bingo! thank you!!!

**Comment by manabidev** [comment]
Thank you so much.
