### ISSUE TITLE
Dragging the interval to min max extents

### ISSUE THREAD

**Issue by jkhk** [IonDen/ion.rangeSlider#281]
When the rangeSlider drag_interval is true, and you drag the interval beyond the min/max extents, the period appears to compress. I would of expected the interval to bump up against the edges (with interval period, start, end remaining the same)

For example:
1)
![image](https://cloud.githubusercontent.com/assets/159715/9054340/9e63b9d4-3ab2-11e5-9edc-acaf039bf7b6.png)

2) Drag interval to the left end (expected it to stay here as I continued to drag to the left)
![image](https://cloud.githubusercontent.com/assets/159715/9054273/f3a73dc2-3ab1-11e5-8731-708c1bf3dacf.png)

3) However "to" continues to decrease as it's dragged to the left
![image](https://cloud.githubusercontent.com/assets/159715/9054318/683a2870-3ab2-11e5-9fa4-2a9e02fb08cf.png)

**Comment by IonDen** [comment]
Hi, this feature is still in beta stage. So it has no options to set up.
Refactoring of this component is in future plans.

**Comment by IonDen** [comment]
Done in 2.1.0
