### ISSUE TITLE
Same value for min and max causes doubled max value

### ISSUE THREAD

**Issue by D-ominik** [IonDen/ion.rangeSlider#282]
If min and max get the same value then the max value will increase by 100%

Example:
`$("#range").ionRangeSlider({
            min: 5000,
            max: 5000,
});`

You can now select up to 10000

**Comment by IonDen** [comment]
Hi, ok. What will you expect in this situation?
Now, then plugin validate this values it checks if max is <= min and auto adjust max if needed.

**Comment by D-ominik** [comment]
Hi. In this case, the range slider is used as an price range selector and min is the price of the cheapest product and max the price of the most expensive product in the current search results list. There are other filters too and therefore it's possible, that only a few products will get listet, possibly with the same price. As a workaround currently I'm increasing max by 1, if min and max are the same value. That's fine for me.

I would expect: the range slider should comply with the given min/max values. In my example the scale should show 5000 on the left side and 5000 on the right side, the start point should be on the most left position, the end point on the most right position. The slider should be fixed or inactive, as there's no usable range.

**Comment by IonDen** [comment]
Ok i will think about that.

**Comment by Ape** [comment]
This caused weird behavior for me. In my case, the minimum and maximum values are dynamically loaded and it's possible that sometimes they are the same value. In my case it means that the slider value cannot be changed, but it's forced to be the same value as the min and max values. The slider value should never be allowed to be outside the minimum and maximum values.

**Comment by IonDen** [comment]
Yes yes, it will be done as soon as i can.

**Comment by IonDen** [comment]
Hello, fixed in 2.1.1
