### ISSUE TITLE
ion.rangeSlider on IE9 doesn't render correctly and breaks other jQuery

### ISSUE THREAD

**Issue by PRSMND** [IonDen/ion.rangeSlider#283]
If I have two instances (two sliders) on the same page the second one doesn't show (assigned text field shows instead) and the first instance on page shows 0 value, no matter if "from" is set to a certain number. Trying to drag the first slider results in jerky movement and labels showing false values.
In this case any other jquery code on page breaks as well.

**Comment by IonDen** [comment]
Can't reproduce.
