### ISSUE TITLE
Make it even more unobtrusive: definable decimal symbol, value separator, separate from/to input field

### ISSUE THREAD

**Issue by D-ominik** [IonDen/ion.rangeSlider#284]
This is really a great range slider. Thanks a lot!

While integrating this slider in an existing project I noticed a few things which could be extended to make it even more unobtrusive. Some of these things could be made with custom functions, but I think these are not uncommon situations, built-in support would be great.

- Type "double": the from and to values are retrieved from and assigned to one input field, separated by a semicolon. When adapting the slider to existing projects, where no sliders existed up to now, it's most likely that separate input fields for 'from' and 'to' are used. It would be easier to adapt the range slider to existing projects if separate input fields for 'from' and 'to' could be defined (instead of one field with separated values).

- Type "double": in the input field the 'from' and 'to' values are separated by a hard coded semicolon. Adapting the slider to existing projects would be easier if the separator could be defined.

- When working with decimals it would be fine, if the decimal symbol could be defined. It's possible to use a custom prettify function to modify the value shown on the scale. But I'm talking about the values retrieved from and assigned to the input field.

**Comment by IonDen** [comment]
Hello.
1. Rare situation, but i will think about it.
2. I will think about it.
3. I think no. Hey they are decimals, type number, why should i convert them to string and change the separator symbol?

**Comment by bweston92** [comment]
+1

**Comment by IonDen** [comment]
Added value separator in 2.1.0
