### ISSUE TITLE
Why javascript configure is priority ?

### ISSUE THREAD

**Issue by C0nstantin** [IonDen/ion.rangeSlider#286]
When I create some sliders in different parts of my site, I can not use js config how default config and data-* how specific for that slider , all work v.v.

**Comment by IonDen** [comment]
Hi, please, make you question more clear, i don't really understand the problem.

**Comment by C0nstantin** [comment]
https://github.com/IonDen/ion.rangeSlider/blob/master/js/ion.rangeSlider.js#L266
why is that? I think data-* configures should have more priority? Its convenient

**Comment by IonDen** [comment]
Ah, okey, i understand your point. Good idea.

**Comment by IonDen** [comment]
Fixed in 2.1.0
