### ISSUE TITLE
Problems when updating sliders

### ISSUE THREAD

**Issue by d3mueller** [IonDen/ion.rangeSlider#287]
Hi,

I experience a problem when I try to update a slider. 

Look here: http://jsbin.com/qusuqaxomo/edit?html,css,js,output

You can only drag a slider by 1%. Then you have to re-click and drag it another 1%. You can't do it fluently. This is caused by adding the update method. In my example I update all of the sliders, but the problem occurs when updating one slider as well.

Something inside the update method crashes the slider temporarily I think. Or am I doing something wrong?

**Comment by IonDen** [comment]
Hi, you should not update current slider in onChange callback. Each update will cause slider redraw and reset of all its event listeners. So, you may update current slider only in onFinish callback. Other sliders you could update thenever you want.

**Comment by d3mueller** [comment]
Okay. Thank you for the fast answer :)
