### ISSUE TITLE
Page crashes when clicking on some point on the slider (instead of dragging)

### ISSUE THREAD

**Issue by d3mueller** [IonDen/ion.rangeSlider#288]
Hi,

I used onFinish now instead of onChange and found another problem:
The page crashes when you click on the slider instead of dragging it. I mean, instead of pulling it to the value you want you can click on that value. But then the whole page crashes and nothing works. I even have to close the tab and reopen it.

Any ideas how to fix that?

JSBin: http://jsbin.com/xifilupiqa/edit?html,css,js,output

**Comment by IonDen** [comment]
Hi, i see. I will investigate this.

**Comment by IonDen** [comment]
Fixed in 2.1.0
