### ISSUE TITLE
Clicking on an area of the slider outside the interval only moves the closest handle

### ISSUE THREAD

**Issue by jkhk** [IonDen/ion.rangeSlider#289]
Here's another request for the drag_interval beta feature; rather than moving the closest handle to the click location on the slider, have an option to move the interval centered on the click location.
e.g. 
![image](https://cloud.githubusercontent.com/assets/159715/9517350/1379f4ae-4ce2-11e5-9b6f-2792f7e1e926.png)

Then left click on a value < 30 (e.g. 20)
![image](https://cloud.githubusercontent.com/assets/159715/9517436/968c1ee4-4ce2-11e5-8843-a6c466937e91.png)

Left clicking inside the to/from range would not change either handle position.

**Comment by IonDen** [comment]
Hi, i will think about this.

**Comment by IonDen** [comment]
Done in 2.1.0
