### ISSUE TITLE
Calling reset seemingly does not do anything

### ISSUE THREAD

**Issue by Puffton** [IonDen/ion.rangeSlider#292]
Add the following two lines at the end of this fiddle: https://jsfiddle.net/IonDen/qv6yrjrv/

```javascript
$range.data("ionRangeSlider").update({from:400});
$range.data("ionRangeSlider").reset();
```

Setting the value to 400 works, but resetting does nothing. I have noticed it on both Chrome and Firefox (haven't tested in more browsers), and I'm having a similar real-world issue (without calling update just before, so it is no hypothetical/narrow use-case). Or I simply misunderstood the use of reset.

No errors or warnings in the log.

**Comment by IonDen** [comment]
Hi, reset works another way. It resets slider to it's original values, but calling update changes original value to the new ones, so reset also now works with this new values.

**Comment by Puffton** [comment]
Is it possible to update the slider without calling update, to preserve this value?

**Comment by IonDen** [comment]
Just save base values in some external variables and use spesific update method to update slider to that saved variables.

**Comment by Puffton** [comment]
Ok!
