### ISSUE TITLE
onDragStart?

### ISSUE THREAD

**Issue by Puffton** [IonDen/ion.rangeSlider#293]
Is there an onDragStart or similar? I see there is an onChange but what I would like to do is fade in the "irs-single" when the user is dragging, and fade it out onFinish.

This is possible using onUpdate, but it is causing a lot of DOM searches with jquery to find the element each time, causing lag on mobile devices.

**Comment by IonDen** [comment]
It can be simulated very easy.
http://jsfiddle.net/IonDen/f6n576tb/

**Comment by Puffton** [comment]
Yeah that's what I ended up doing, but it felt like a bit of a hack. It would be cool if this was handled internally.

**Comment by IonDen** [comment]
No need, that will be to much messy at the end.

**Comment by Puffton** [comment]
Ok.
