### ISSUE TITLE
Keyboard fixed step instead of percent

### ISSUE THREAD

**Issue by LDSign** [IonDen/ion.rangeSlider#297]
Hi

Is it possible to modify the slider with fixed steps instead of percent via keyboard?

Ive a large "slider" range and it is difficult to select a specified number width the handle, so it would be nice to do this with the keyboard.

Thanks,
Frank

**Comment by IonDen** [comment]
In future it will be possible. Now keyboard support is in beta stage.

**Comment by IonDen** [comment]
#229
