### ISSUE TITLE
Slider adding spaces to labels when they are numbers represented as strings

### ISSUE THREAD

**Issue by Robert-W** [IonDen/ion.rangeSlider#298]
If I provide an array of values that are just string representations of numbers, its adding a space after the first number.  For Example, if the values array is something like this:
```
values: ["2001, "2002", "2003", "2004"]
```
It renders the numbers on the slider like 2 003 and 2 004 instead of 2003 and 2004.  I can add a `&nbsp;` to the front of each label (`"&nbsp;2001"`) and it sort of tricks it to get the desired result but thats definitely a hack.

Please see attached fiddle: http://jsfiddle.net/gqqby2s7/1/

**Comment by IonDen** [comment]
Hello. Numbers like strings will be converted to numbers, so, if you don't want to prettify them, just use this: http://jsfiddle.net/gqqby2s7/2/

**Comment by Robert-W** [comment]
Man that has to be the fastest response I have had to a ticket in my life, thanks man, that works as expected.

**Comment by IonDen** [comment]
No problem)
