### ISSUE TITLE
Error Rangeslider with css.zoom

### ISSUE THREAD

**Issue by cbeneyto** [IonDen/ion.rangeSlider#299]
Good afternoon.
There is a problem with Rangeslider when I put the property CSS zoom in the body.

for example: I want to default zoom my page is: 80%

```css
body { zoom: 80%; }
```

The Rangeslider never reaches the end (to the left).
Any solutions?

**Comment by IonDen** [comment]
Hello, it does work correctly with native browser zoom.
CSS zoom is not well supported, and really deprecated feature. You should not use it.
