### ISSUE TITLE
Can not shrink slider/interval by dragging slider handles

### ISSUE THREAD

**Issue by mKlus** [IonDen/ion.rangeSlider#305]
This issue seems to be introduced with version 2.1.0.

When rangeSlider is created with the following options and the slider is moved left or right the handles then can not be moved to make the slider/interval smaller.

$range.ionRangeSlider({
    type: "double",
    min: 100,
    max: 1000,
    from: 300,
    to: 800,
    grid: true,
    force_edges: true,
    hide_min_max: true,
    drag_interval: true
});

e.g. http://jsfiddle.net/y81j67qh/11/
change the slider interval from 300-800 to 200-700 by dragging the slider to left. Then try moving the 'from' handle to 250.

**Comment by IonDen** [comment]
Tnx, fixed in 2.1.1
