### ISSUE TITLE
Issue when we activate grid_snap without step

### ISSUE THREAD

**Issue by ncoquelet** [IonDen/ion.rangeSlider#307]
There is not a really use case to do this, I think :)
But during my test, I do it with one year of date !! do the same with a range of 10000 unit

The probleme is the plugin try to render all the grid tick !!! with a label !!!!
And this can take a long time, a very long time ... resulting an ugly result ;-)

example with 1000 http://jsfiddle.net/09u17wg7/23/ and with 100000 http://jsfiddle.net/09u17wg7/22/

Regards

**Comment by ncoquelet** [comment]
Add a step resolve the problem
http://jsfiddle.net/09u17wg7/24/

but this not seem to be a bug, finally !

**Comment by IonDen** [comment]
Oh yes, grid collisions are still in beta stage.

**Comment by IonDen** [comment]
This was fixed long ago
