### ISSUE TITLE
click outside the interval move to its start or its end

### ISSUE THREAD

**Issue by ncoquelet** [IonDen/ion.rangeSlider#308]
Hello,

Like #303, I would propose configurable move to the new #289 feature.

Instead of center the interval on click, which can be a little hazardous anddifficult to predict the new interval values. It could be interting to add option to align the interval on its start or on its end !

Regards

**Comment by IonDen** [comment]
Hi, again. No, it's to messy and rare situation. #303 would be quite enough.

**Comment by ncoquelet** [comment]
Hi,

I'm totaly agree with your point of view for a slider with number or arbitrary string. Centered seems enough and #303 is a great evolution

But in our case, we deal with date by selecting weeks. After selecting a range of date, four weeks for example, we want to move the range to compare with another period.
#303 don't help us because our full period is too large ! we can't do more 2 clicks for an action.
Of course, we can move the interval by drag and drop, but it's more user friendly to click directly on the track. 
In this case we assume that our four weeks interval, start where we are clicked ! But for this moment, the interval is centered near the click, it's position can't be predictable and it need a second action to place it correctly.

But i'm not worry if you won't implement it, I do it myself ;-)

**Comment by IonDen** [comment]
Hello, @ncoquelet , look at this demo: http://jsfiddle.net/IonDen/kdr083wg/
It can be very accurate.

**Comment by ncoquelet** [comment]
Hello,
@IonDen, now image you don't have max_interval and you have selected equivalent to step * 4.
http://jsfiddle.net/kdr083wg/2/
It becomes less accurate 

And it's more relevant with date, try to start the range to june 20, 2015 ;-)
http://jsfiddle.net/kdr083wg/3/

**Comment by IonDen** [comment]
@ncoquelet, i don't really understand, what is the problem. If not clicking, user will drag diapason to some random position. Don't expect that 100% users will click.

**Comment by ncoquelet** [comment]
Our soft is like a google analytics, it allows users to analyse data over a selected period.

Okay, some user will use the drag and drop method and it works fine.
But some others will click and expect that interval start where they have clicked. It's the way where our app is implemented. 

But I repeat myself, it's not a big deal if you don't implement it, I would do it myself ;-)

**Comment by IonDen** [comment]
Ok)))
