### ISSUE TITLE
Format Money?

### ISSUE THREAD

**Issue by andrewteg** [IonDen/ion.rangeSlider#309]
I'm using the update method to add in money values from a form (like a payment slider) and I'm losing my formatting.

I saw in #298 that "Numbers like strings will be converted to numbers" but since I need to keep the formatting for 237.5 to show as 237.50 can I stop that conversion in some way? 

FWIW, I have to use an array instead of a step because it's a custom formula of amounts I'm calculating as options for the slider.

**Comment by IonDen** [comment]
Hello, use real numbers formatting, then passing values to slider. But, inside slider, redefine prettify function, to show money as they are meant to be. Example: http://jsfiddle.net/IonDen/juh5ph73/

**Comment by andrewteg** [comment]
Thanks, that works great. Did notice that line 18 of the fiddle should read

`result += "." + str[1] + "0";` 

instead of 

`result += ".0" + str[1];`

to make a number like 2.4 correctly go to 2.40 instead of 2.04 so I created http://jsfiddle.net/76bgkv24/1/ with that change for anyone else finding this.
