### ISSUE TITLE
onFinish event doesn't fire for min and max values

### ISSUE THREAD

**Issue by antongrinenko** [IonDen/ion.rangeSlider#310]
See demo 43 (interactions tab). 
Move slider to "0" and little left outside the slider element. Only onChange event fires. 
Move slider to "100" and little more right ontside the slider element. Only onChange event fires. 
Move slider to any other value. onChange and onFinish events fire.

**Comment by IonDen** [comment]
Cool, i will check this.

**Comment by PRSMND** [comment]
I encountered the same issue.
onFinish triggers a function only if slider is not moved outside the slider element.

**Comment by ncoquelet** [comment]
+1
My slider is displayed in full width of page, and this bug occur each times we go to the left or right edges

**Comment by IonDen** [comment]
Yes, yes will check this soon.

**Comment by ncoquelet** [comment]
Guys, you can try #312, until IonDen validate it.

**Comment by IonDen** [comment]
Fixed in 2.1.2
