### ISSUE TITLE
blocked slider in "double" if both are on the left

### ISSUE THREAD

**Issue by ncoquelet** [IonDen/ion.rangeSlider#313]
Hi,
Here a little bug with double slider

Take the demo range_03 http://ionden.com/a/plugins/ion.rangeSlider/demo.html
Put the min slider to 0$ and the max slider to 0$ too.
= dead lock !! :-)

Fortunately, you can click on the track to release the max label ;-)

**Comment by IonDen** [comment]
Mmm, tried it again, no dead lock. Maybe you have very old version of plugin in browser cache? Try to Ctrl+R.

**Comment by ncoquelet** [comment]
Effectively, in some case it works !

If we use the slider only, after move the max slider to 0, we can grab it again to move it forward.
But if we use the tooltip, the focus stay on the min and we can't grab max label or max slider anymore.

2 break cases :
- if we move both tooltip only to 0,
- or if we click on the tooltip after moved both sliders to 0

It's a tricky behavior of the tooltip and slider z-index

**Comment by IonDen** [comment]
Ok, i will check this.

**Comment by IonDen** [comment]
Fixed in 2.1.2
