### ISSUE TITLE
3rd tooltip to show exact value within a range

### ISSUE THREAD

**Issue by murrayclement** [IonDen/ion.rangeSlider#314]
Hey,

I'm wondering if it's possible to set a third tooltip to show the current value within a range. I've attached a mock:

![slider](https://cloud.githubusercontent.com/assets/7799888/10180166/bbd24e16-66bf-11e5-8494-92ec42e5a0d3.png)

Thank you and great work.

**Comment by IonDen** [comment]
Hello, you can make this tooltip by yourself. In its callbacks, slider returns object with data. In this data there is an information not only about slider values, but also about handlers coordinates in percent. So, you could write your own tooltip and update its position on every slider change. This will be you 3-rd tooltip.
