### ISSUE TITLE
Не могу задестроить сущность

### ISSUE THREAD

**Issue by aios** [IonDen/ion.rangeSlider#315]
var slider = $range.data("ionRangeSlider"); Возвращает undefined соответственно задестроить нечего.

Делаю как в мануале 1 в 1. Нужна помощь.

**Comment by IonDen** [comment]
Привет, чтобы присвоить сущность переменной, нужно вначале создать.
```
var $range = $('.input').ionRangeSlider();
var slider = $range.data('ionRangeSlider');
slider.destroy();
```

**Comment by aios** [comment]
Все бы ничего - но вот код:
```javascript
var $range = $("#rangePrice"),
                slider;

        var create = function () {
            $range.ionRangeSlider({
                type: "double",
                grid: true,
                min: 0,
                max: {{ $price }},
                from: 25000,
                to: 60000,
                prefix: "$"
            });

            slider = $range.data("ionRangeSlider");
        };

        $("#changeSlider").click(function () {
            if ($(".sliderUp:visible")) {
                $(".sliderUp").addClass('hide');
                create();
                console.log(slider);
            } else {
                $(".sliderUp").removeClass('hide');
            }
        });
```
Вы вод console.log(slider)  - undefined. Хотя слайдер создается. То есть функция create отрабатывает.

**Comment by IonDen** [comment]
Поиграйтесь с этой демкой, может вы делаете что-то не так: http://jsfiddle.net/L65x7cse/

**Comment by aios** [comment]
Блин я уже все сделал как по демке - ну не получает оно инстанс этого слайдера - как его можно задестроить по другому?
http://i.imgur.com/Yw1vdLw.png

**Comment by IonDen** [comment]
Так попробуйте на демке воспроизвести свою ситуацию, хотя бы в самом приближенном виде.

**Comment by aios** [comment]
Да! оно видно что на демке работает. У меня делаю тоже самое 1 в 1 и не получается - что мешает даже не знаю.

**Comment by IonDen** [comment]
На демке сильно упрощенный код, воспроизведите там свою ситуацию.

**Comment by aios** [comment]
Ну в общем на демке работает - у меня нет - есть еще какие то способы получить инстанс и задестроить, если нет - то смысла тратить время дальше я не вижу. Пойду искать что по проще.

**Comment by IonDen** [comment]
Я так и не увидел чтобы вы демку настроили под свой код.

**Comment by aios** [comment]
Да ее не нужно настраивать под мой код что бы понять что у меня он не
работает - хотя все подключено 1 в 1. Я ведь не буду оборачивать в лару,
jsfiddle что бы создать окружение как у моего кода.

2015-10-03 22:39 GMT+03:00 Denis Ineshin <notifications@github.com>:

> Я так и не увидел чтобы вы демку настроили под свой код.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IonDen/ion.rangeSlider/issues/315#issuecomment-145281325>
> .
>



-- 
С уважением, Габриелян Д.М.

ICQ:      *3092095*
Skype:  *gt_fios*

**Comment by IonDen** [comment]
Ок, мои телепатические способности исчерпаны. Советую создать онлайн демо с проблемой и задать вопрос на https://toster.ru/ или http://ru.stackoverflow.com/
