### ISSUE TITLE
Traverse class name to container

### ISSUE THREAD

**Issue by mharvester** [IonDen/ion.rangeSlider#318]
Great job!

Found one missing functional! Cannot add a custom class name to container_html, so be kind, add a parameter, something like "container class", for input and copy it to "span class="irs ..."

Thank you.

**Comment by IonDen** [comment]
Hello, please tell some examples, why should we need this?

**Comment by mharvester** [comment]
Hi Denis, For individual styling on the page. Take a look at example in attachment.
![slider](https://cloud.githubusercontent.com/assets/15071779/10416147/45cec7ce-7012-11e5-8d00-38eed7ae98af.png)

**Comment by IonDen** [comment]
Ok, why can't you put each slider inside different containers and set individual styles from top?

**Comment by mharvester** [comment]
I can, now it act this way, but more convenient, i think, to build html with asked style. It is in your 
decision.

**Comment by IonDen** [comment]
Implemented in 2.2.0
