### ISSUE TITLE
Suggestion: Required, blank default value (HTML 5 validation)

### ISSUE THREAD

**Issue by Puffton** [IonDen/ion.rangeSlider#320]
It would be nice to require the user to actively set the value of the slider (so it isn't forgotten at its default).

Like adding "Please choose..." in a dropdown with an empty value, and making it required using HTML5 validation.

**Comment by IonDen** [comment]
Sorry, but no. Only several types of controls could have optional values. Slider is supposed to have some value by default. For example 0 for single slider, of maximum available diapason for double slider.

I rare situation, then you don't need some default value, you may add some checkbox which will control slider visibility.
