### ISSUE TITLE
How can we use an input field to set a slider's "max: " value.

### ISSUE THREAD

**Issue by iansears** [IonDen/ion.rangeSlider#322]
I'm unable to solve how to use an input field to set a slider's "max: " value. 
Is there a JSFiddle perhaps?

To be clear, I am not asking how to set a slider's position. I am asking how to set the value of "max". It would be ok if there was a temporary "hardcoded" max value at runtime. However, I have a field I called input2. I would like to type 1200 (for example) and have that change the slider's full max value from the hardcoded whatever TO the value 1200 (for example).

Is this possible?

**Comment by iansears** [comment]
Solved!
I did it like this:

$input2.on("change keyup", function () {
    var val = $(this).prop("value");
    
    // validate
    if (val < min) {
        val = min;
    }
    
    instance.update({
        max: val
    });
});

Thanks for being available though.
:)

**Comment by IonDen** [comment]
@iansears, sorry, i'm living in different time zone) I was sleeping)
