### ISSUE TITLE
Setting data-min to 0 defaults to 10.

### ISSUE THREAD

**Issue by webbson** [IonDen/ion.rangeSlider#323]
When setting the min value of the slider to 0 via data-min="0" on input element it default to 10, however when setting via JS it works with 0.

**Comment by IonDen** [comment]
Hi, tell me more, or it was missunderstanding?

**Comment by webbson** [comment]
Hey, I was to fast writing an bug report. Noticed you had already fixed in latest release. It was a duplicate of bug #316
