### ISSUE TITLE
Question: Min and Max change display value

### ISSUE THREAD

**Issue by Izopi4a** [IonDen/ion.rangeSlider#324]
Hello,

lets say we have `[1,2,3,4,5,6,7,8,9]` double slider

I want min 0 that sais: "Doesnt matter" and max that sais "Doesnt Matter" with submit value 0

and also on min/max the postfix to be empty

**Comment by IonDen** [comment]
Hello, easy: http://jsfiddle.net/IonDen/whkn0bnm/

**Comment by Izopi4a** [comment]
thank you very much.

Cheers.
