### ISSUE TITLE
Step using Date

### ISSUE THREAD

**Issue by yuriolive** [IonDen/ion.rangeSlider#325]
Hi, first thank you for your awesome plugin. I'm new to it, so I don't know if is a bug or if have some way of doing that, by I detected that I couldn't use step when using a date. Thanks ;)

**Comment by IonDen** [comment]
Hello, please look at this demo: http://jsfiddle.net/IonDen/w1ucb8bm/
As you see, step also should be a date converted to miliseconds.

**Comment by yuriolive** [comment]
Thank you Ion! ;)
