### ISSUE TITLE
Performance issue on update FF and IE

### ISSUE THREAD

**Issue by danyj** [IonDen/ion.rangeSlider#326]
I am working on CSS generator that is using about 40+ sliders as options.  On load the performance is ok , but when I  need to update there is a noticeable lag on IE and FF. 
Chrome , Safari, Opera look ok  . 

Here is fiddle 

http://jsfiddle.net/p9fsyx84/

note that on button click I must update all form inputs. With this lag , combined with CSS that needs to be applied to the page , I am looking at the 3-5 sec  lag until all sliders have finished.

**Comment by IonDen** [comment]
Hi, i will check this soon.

**Comment by danyj** [comment]
thnx bud , I am trying all possible options but cant find any suitable one. the update is performance killer since it does so much ,  validating , removing initiating , instead just changing the val, 
https://github.com/IonDen/ion.rangeSlider/blob/master/js/ion.rangeSlider.js#L2232-L2237

I tested range sliders , default UI and an array of others and none of them have an issue 

here simple range slider instead of ion in same manner  and much faster 
http://jsfiddle.net/qzjvxg9t/

please see what you can do.

**Comment by IonDen** [comment]
Hi again. I already have #290

More intellectual updates - is one of the features, planned for 3.x version. It requires remastering of whole plugin structure, so, not in 2.x brunch. Sorry.

Then 3.x will be ready? Good question. It is in preproduction stage right now. I expect it to be ready in the first quarter of 2016.

**Comment by danyj** [comment]
thnx for the info but this means we have to drop it at this time.

**Comment by IonDen** [comment]
I have a plans to impement quick update if only values was changed. This should be ready before 3.x

**Comment by danyj** [comment]
That wold help a great deal. It is only value change as you see on those demos

**Comment by IonDen** [comment]
@danyj, ok, follow for updates.

**Comment by danyj** [comment]
here this is biggest killer and I would like to use it , 



    grid:true


huge difference on FF and IE
http://jsfiddle.net/p9fsyx84/1/

**Comment by IonDen** [comment]
Yep, grid is very complex component.

**Comment by IonDen** [comment]
#328 created.

**Comment by danyj** [comment]
:100:
