### ISSUE TITLE
No possibility to set custom grid units

### ISSUE THREAD

**Issue by vadim-bulochnik** [IonDen/ion.rangeSlider#327]
Hello,

It would be good to have possibility to set custom grid units instead of using "grid_num" param that put grid units based on calculations.
For example: there is a range slider to choose price for product. Min = 500€, Max = 10000€. I would like to set only following grid units: 1000, 3000, 5000, 7000, 9000. Not it's not possible.

Anyway, thank you for great slider!

Best regards,
Vadim

**Comment by IonDen** [comment]
Hi, custom grid is in plans.

**Comment by IonDen** [comment]
#151
