### ISSUE TITLE
Slider values not shown when initialized with same value

### ISSUE THREAD

**Issue by Fidel90** [IonDen/ion.rangeSlider#330]
http://jsfiddle.net/qv6yrjrv/325/

The slider will be initialized e.g. with 300/300 and the label above will not be shown. When you start dragging them around and place them at the same value, the label is visible as expected.

**Comment by Fidel90** [comment]
Maybe related: https://github.com/IonDen/ion.rangeSlider/issues/333

**Comment by IonDen** [comment]
Hi, i will try to fix this soon.

**Comment by tylercubell** [comment]
#362

**Comment by IonDen** [comment]
Fixed in 2.1.4
