### ISSUE TITLE
Decrementing right handle beneath min causes jump to max

### ISSUE THREAD

**Issue by Fidel90** [IonDen/ion.rangeSlider#331]
http://jsfiddle.net/qv6yrjrv/326/

Both slider handles have to be set to min (no matter if initialized or manually). Now I decrement the right handle by pressing an external button. What I expect to happen is literally nothing, as the handle can't go beneath min. What happens instead is the right handle jumping to max value.

**Comment by IonDen** [comment]
Hi, @Fidel90, thanks for finding this issue. I will try to fix this soon.

**Comment by IonDen** [comment]
Should be fixed in 2.1.5
