### ISSUE TITLE
Decrementing left handle beneath min causes value label to disappear

### ISSUE THREAD

**Issue by Fidel90** [IonDen/ion.rangeSlider#332]
http://jsfiddle.net/qv6yrjrv/327/

First, move both handles to min. The label should be visible (100). Now press the button to decrement the left handle. The label disappears.

**Comment by Fidel90** [comment]
Maybe related: https://github.com/IonDen/ion.rangeSlider/issues/333

**Comment by IonDen** [comment]
Hi, i will try to fix this soon.

**Comment by Fidel90** [comment]
Make sure to:

1. Move the right handle to 100 (right and left handle have to be the same value, the label is visible)
2. Now click the button to decrement the left handle, the label will disappear (tested in Chromium)

I can reproduce that with the given fiddle without problems.

**Comment by IonDen** [comment]
Ok, thanks for finding this bugs. I will try to fix them as soon as possible.

**Comment by IonDen** [comment]
Should be fixed in 2.1.5
