### ISSUE TITLE
Value label disappears when both handles are set to same value by external buttons

### ISSUE THREAD

**Issue by Fidel90** [IonDen/ion.rangeSlider#333]
http://jsfiddle.net/qv6yrjrv/328/

Start values are 500/501 (works with every other values as well). If you click the button to decrement the right handle to 500, the label disappears. Same would happen when you increment the left handle to 501 via button. Dragging the handles does not show this issue.

**Comment by IonDen** [comment]
Should be fixed in 2.1.5
