### ISSUE TITLE
custom prefix labels 

### ISSUE THREAD

**Issue by zspitzer** [IonDen/ion.rangeSlider#336]
I would like to be able to use a custom prefix label for the markers

ie prefix : ['lower threshold',''upper threshold']

**Comment by IonDen** [comment]
What do you mean? Different prefixes for each label?
Now plugin have 3 options: prefix, postfix and max_postfix. Is it not enough?

**Comment by zspitzer** [comment]
Yep, different prefixes for each label in a double, I'd imagine passing in a third parameter to the decorate function and then the prefix, postfix and max_postfix options could optionally be function which could handle the selection logic if you didn't want to build support directly into the library

**Comment by IonDen** [comment]
Ok, then you question duplicates this request #278. Please check and at your ideas there.
