### ISSUE TITLE
Slider Labels does not show decimal/floating values

### ISSUE THREAD

**Issue by aalokm** [IonDen/ion.rangeSlider#339]
To start with, the  slider is really awesome! But there is one thing that I would be really happy if we could manage to achieve it. The slider labels will always show integer values only. the only way it will show a decimal value is if i have used prettify on it. 
It may be a feature request than an issue but can we have it set to display decimal values in labels?

**Comment by IonDen** [comment]
Hello, i'm not sure what do you mean.
Check this: http://jsfiddle.net/IonDen/ezn7egek/
And maybe create a demo to show the problem

**Comment by knitesh** [comment]
Not an issue. Check
http://jsfiddle.net/knitesh/26tuewe9/3/

**Comment by IonDen** [comment]
@aalokm, to operate decimal values, you will need to set step attribute in config.
