### ISSUE TITLE
Update slider's MinValue with other slider's from-Value

### ISSUE THREAD

**Issue by beyinsi** [IonDen/ion.rangeSlider#340]
Hi all,

i have a problem about on updating sliders values...i see a solution (  http://jsfiddle.net/IonDen/qaLpd2mu/ ). but, this example not update when page load and span.html(result) update when using sliders....

i edit this code for what i want >>> http://jsfiddle.net/beyinsi/8pn635co/3/ 

hope u can understand me, my english is not well.

summary; i wanna this:
when page load update span.html(result) values, 
when changing sliders values update span.html(result) values, 
when changing first slider update all html results

when page load slider1 default from value update  slider2 min value update

**Comment by IonDen** [comment]
I think this is a solution: http://jsfiddle.net/IonDen/8pn635co/4/

**Comment by beyinsi** [comment]
Thank you very much  Denis..

Can we update , when i use slider1, and slider1 from up to 50 
slider2 minimum from value changed forexample 51 ..

how we update  $('#sonuc2').html(data.from); ... (NOT use slider2)

**Comment by beyinsi** [comment]
excuse me for bad english, hope you can understand what i mean :)

**Comment by IonDen** [comment]
I think i did't understand)
