### ISSUE TITLE
take over bower registry.

### ISSUE THREAD

**Issue by graingert** [IonDen/ion.rangeSlider#341]
Currently I've registered ion.rangeslider to my fork at https://github.com/graingert/ion.rangeSlider

@IonDen I'd like you to take over this registration

**Comment by graingert** [comment]
I've just found the real registration at "ion.rangeSlider" consider setting the bower.json name and the registration to match: https://github.com/IonDen/ion.rangeSlider/pull/342

**Comment by IonDen** [comment]
Hi, not sure what will be result. Check this:
http://bower.io/search/?q=ionrange
http://bower.io/search/?q=ion.range

Both has links to my repo.

**Comment by graingert** [comment]
Ok I've assigned ion.rangeSlider to your repo now. Maybe it would be a good idea to unregister those other bower registrations?

**Comment by IonDen** [comment]
Hm, maybe not important. Let people find it many ways.

**Comment by IonDen** [comment]
Fixed in last update.
