### ISSUE TITLE
Severe issue if a value is set on the input (any number):  Uncaught TypeError: Cannot read property 'input_values_separator' of undefined (Fiddle supplied)

### ISSUE THREAD

**Issue by tmikaeld** [IonDen/ion.rangeSlider#343]
http://jsfiddle.net/tj6896nk/

**Comment by IonDen** [comment]
Hi, thanks for finding the bug.

**Comment by tmikaeld** [comment]
Will the change be rolled out to bower directly?

**Comment by IonDen** [comment]
Bower is getting files from this repo, so yes, then the fix will be ready it will be on bower also.

**Comment by sylvainbaronnet** [comment]
FYI, the problem ca be bypass simply by setting type:'single' or type:'double'

**Comment by IonDen** [comment]
@sylvainbaronnet, thanks for solution. Nevertheless the fix will be ready soon.

**Comment by natatkinson** [comment]
Any updated on this? Still getting the error.

**Comment by IonDen** [comment]
@natatkinson, i'm deeply in 3.0 development process, but soon will be one more minor release for 2.x, to fix some bugs.

**Comment by natatkinson** [comment]
Great, thank you so much!

**Comment by IonDen** [comment]
Should be fixed in 2.1.5
