### ISSUE TITLE
Not able to update Slider value on change of another input

### ISSUE THREAD

**Issue by aalokm** [IonDen/ion.rangeSlider#351]
Hi,

I am not sure whether I am missing something here or this is an actual issue. 
what I am trying to do is that I have a slider on-change of which I am able to update value of input field, which works fine. When I try to achieve the same by changing the value of input I am not able to do so.
There are no error messages in console either. 
Can you please help me in this? The fiddle is given below:
[http://jsfiddle.net/aalok/nrqjs90f/11/](http://jsfiddle.net/aalok/nrqjs90f/11/)

**Comment by IonDen** [comment]
Hello, @aalokm.
Please check this demo: http://jsfiddle.net/IonDen/mvrfg2vc/

**Comment by aalokm** [comment]
Hi,

the demo works but there is one basic difference with my code. I am trying to change the value of slider based on a input type="number" while in your demo you are using text fields.

**Comment by IonDen** [comment]
http://jsfiddle.net/IonDen/mvrfg2vc/14/
With type "number"

**Comment by aalokm** [comment]
Works just fine mate! After applying validations, the code works like a charm.

**Comment by IonDen** [comment]
Nice)
