### ISSUE TITLE
Basic demo example displaying incorrectly

### ISSUE THREAD

**Issue by Maggie-M** [IonDen/ion.rangeSlider#352]
On [this page](http://ionden.com/a/plugins/ion.rangeSlider/demo.html), the second example of the **Visual Details** section does not match the code shown to the left.

<img width="729" alt="screen shot 2016-02-19 at 1 28 52 pm" src="https://cloud.githubusercontent.com/assets/1417520/13186642/c2cca42e-d70c-11e5-8f4f-8b477bfb69f5.png">

Despite *grid: false*, the grid still appears on the right.

**Comment by IonDen** [comment]
Hi, thank you for finding this.

**Comment by IonDen** [comment]
Fixed in latest update.
