### ISSUE TITLE
How to know which handle was changed?

### ISSUE THREAD

**Issue by whydna** [IonDen/ion.rangeSlider#353]
I'm subscribing to changes to the slider using the `onChange` event. However, there does not seem to be a way to know which handle was changed.

**Comment by IonDen** [comment]
Hi, @whydna. It is easy. If slider is double, you will get the value with separator. Like this: ```39;47```
So, you should just split it in to 2 values, like this: ```value.split(";");``` and check left or right was changed.

**Comment by slidenerd** [comment]
prettify function however is called twice for each value it seems

**Comment by IonDen** [comment]
@slidenerd, yes it is called separately for each visible number (from, to, labels, grid etc.)

**Comment by ffiona** [comment]
Can someone provide an example please? I don't quite understand how to get this value to detect left of right handle was changed.
