### ISSUE TITLE
Wrong value when setting step !=  1

### ISSUE THREAD

**Issue by tieppt** [IonDen/ion.rangeSlider#355]
Thank you for contribute very good resource, but when I try init with step != 1 (maybe 5), then listen `change` event of my ranger input, then i got wrong value as step init, sometime value is `1` or `6`
![mysuper247](https://cloud.githubusercontent.com/assets/7151365/13374282/411e1668-ddb2-11e5-9a4b-d72898662521.png)

**Comment by IonDen** [comment]
Hi, i need more info on this.

Besides, step does not mean that the value will start from 0. Like: 0, 5, 10, 15.
If your start value vas 2, it will be: 2, 7, 12, 17, 22 ...
