### ISSUE TITLE
Add prettified value to result object

### ISSUE THREAD

**Issue by softlimit** [IonDen/ion.rangeSlider#356]
Probably a relatively basic question... but I'm a little stuck nonetheless. 

How would you go about passing the defined options from the RangeSlider over to a Value Result box? Specifically, max_postfix, prefix and prettify_separator? 

I have the basic setup here: [http://jsfiddle.net/z57hhjdx/](http://jsfiddle.net/z57hhjdx/) ... just not sure how to take it this additional step towards passing the extra data over.

Thanks.

**Comment by IonDen** [comment]
Good idea. I will try to add this feature to future release.

**Comment by IonDen** [comment]
@softlimit 
Implemented in 2.2.0
