### ISSUE TITLE
Resize the slider

### ISSUE THREAD

**Issue by yankees6543** [IonDen/ion.rangeSlider#360]
Is there any possible way to make the slider larger or smaller?

**Comment by IonDen** [comment]
Just change its skin file. You may set any sizes you wish inside.

**Comment by yankees6543** [comment]
Will that resize the entire control or just the bar?

**Comment by IonDen** [comment]
Anything you wish

**Comment by yankees6543** [comment]
Ok thanks, I was able to get it how I wanted it through a bit of trial and error changing numbers.  Maybe in a future release there will be a way to just change one value that will grow or shrink the control based on percentage.
