### ISSUE TITLE
Is there a way to drag the entire slider and not just the ends?  

### ISSUE THREAD

**Issue by cdaniel77** [IonDen/ion.rangeSlider#361]
I would like to request the addition of being able to drag the entire slider and not just the ends.  If I don't choose the ends then the entire slider shifts and updates the min/max values as it shifts.

**Comment by IonDen** [comment]
Hi, @cdaniel77, check last demo on this page:
http://ionden.com/a/plugins/ion.rangeSlider/demo_advanced.html

**Comment by cdaniel77** [comment]
Yes, that is exactly what I'm looking for.  Thank you.  Side question, I would like to use this with Aurelia.  Is there a tutorial on how to include and use the plugin?

**Comment by IonDen** [comment]
Just as any other jQuery-plugin, just check the [info base](http://stackoverflow.com/questions/tagged/aurelia%20jquery?mode=all).
