### ISSUE TITLE
slider pointer is not working in ajax container 

### ISSUE THREAD

**Issue by vivinblack** [IonDen/ion.rangeSlider#363]
Range slider is working as it is in normal div container , but pointer's slide functionality is not working in the ajaxed container , in the ajaxed container I need to manually click the mouse pointer on range bar .is it issue with jQuery ui dependency ?

**Comment by IonDen** [comment]
Hi, please tell me more, o provide some demo.
P.S. Slider have only jQuery dependency, not jQuery UI.
