### ISSUE TITLE
No UI elements appearing...

### ISSUE THREAD

**Issue by crouti** [IonDen/ion.rangeSlider#366]
Hi, great slider ! Cheers
I've included all specified files, but the range slider show up, without any skin elements (whatever skin i include in my page). No error in browser console, so all files included.
Do i need a special import for the skin png image ?

Thank you very much!

[capture d ecran 2016-04-15 a 13 25 32](https://cloud.githubusercontent.com/assets/10502063/14560098/b2e368ea-030d-11e6-9861-7d7188cb5e46.png)

**Comment by IonDen** [comment]
Hi, just check all the paths and paths to images in skin files itself.

**Comment by crouti** [comment]
My fault, problem was coming from incorrect enqueue of script in wordpress.
Thank you very much !! =-
