### ISSUE TITLE
bar color delimitation

### ISSUE THREAD

**Issue by AlexandreMoulti** [IonDen/ion.rangeSlider#367]
Hello,
I would like to make a bar with 2 colors delimited not by the cursor but by a javascript configurable value as in the example.
Someone knows how to do that ?

**Comment by IonDen** [comment]
No JS API for that.
Try to play with skin CSS file to implement this.

**Comment by AlexandreMoulti** [comment]
The problem is that I need the separation to be configurable and not fixed, depending on what the server computes as value.

**Comment by IonDen** [comment]
@AlexandreMoulti, i think, that this manipulation is doing outside of slider, with CSS and inline styles. You can manipulate it with external JS script (jQuery.CSS(...), element.style.something etc.)

This logic you want is too complex to include it in the box, you should write you own code for it.

**Comment by AlexandreMoulti** [comment]
Dobri den
You seem to speak russian :-)
Do you know on which feature in the css i havz to play with?
Le 18 avr. 2016 5:10 PM, "Denis Ineshin" <notifications@github.com> a
écrit :

**Comment by IonDen** [comment]
Ок, какой у вас вопрос?

**Comment by AlexandreMoulti** [comment]
My russian is limited.
I wanted to fix the color to make it not dependent on the cursor.
If we have a range of 20 years. I would like 17years left in blue and 3
years in red.
If I want it to be dependent on input data, I need to make it into
javascript. So I need to change some css fracture in the JavaScript. I
don't know which feature to chnage?
Le 21 avr. 2016 9:36 AM, "Denis Ineshin" <notifications@github.com> a
écrit :

Ок, какой у вас вопрос?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/IonDen/ion.rangeSlider/issues/367#issuecomment-212787373>

**Comment by IonDen** [comment]
Ok, it does not support that. Try some CSS tricks, this is my only advice.
