### ISSUE TITLE
Inital step needs to subtract min value

### ISSUE THREAD

**Issue by ShaunR** [IonDen/ion.rangeSlider#368]
If you create a slider with a min value of 1 and a step of 1024 the first step will end up being 1025, and then every step after that will increment by 1024 (1025, 2049, ...).

If you try and get around this by setting the step to 1023 the first step is 1024 however the second step ends up being 2047.

It looks like what may need to happen is for the slider to subtract the min value when doing it's first step.

**Comment by IonDen** [comment]
It is normal behaviour.
1. If you have step 10 and min 0. Result will be: 10, 20, 30, 40 etc.
2. The same step, but min is 5. Result will be: 15, 25, 35, 45 etc.

So, i do not round step to 0 all the time, this could be strange.

To archive your case, you should use custom rounding function inside prettify function, like this:
http://jsfiddle.net/IonDen/jhwypurk/
