### ISSUE TITLE
Request for a 'Labels' Setting

### ISSUE THREAD

**Issue by grantwoodtechnology** [IonDen/ion.rangeSlider#370]
Hello,

Is it possible to specify an array of labels that appears underneath the values, like in the attached image?

--
Regards,
Sean
![ion_range_slider_labels_beneath_values](https://cloud.githubusercontent.com/assets/1209138/14839192/e1c5fdca-0bf6-11e6-98d4-ae2d662acf78.jpg)

**Comment by IonDen** [comment]
Hello, no. Future plans: #348
