### ISSUE TITLE
Incorect grid when using odd range with - 

### ISSUE THREAD

**Issue by alexrugik** [IonDen/ion.rangeSlider#372]
Good day!

I see bug  with grid when i am using range like from -5 to 5 or -7 to 7 with step 1.

https://scrn.gbksoft.net/bOxrrOCywegTiZQyv3SRfQ.png

Could you please help me fix  this?

Thank you in advanced.

**Comment by IonDen** [comment]
Hi, try custom grid values (grid_num, grid_snap).

**Comment by Skripatch** [comment]
Confirm bug. Can see live demo
https://jsfiddle.net/amgefv0w/

**Comment by IonDen** [comment]
@alexrugik, @Skripatch this is a rounding issue for default grid setting, really not a bug. To prevent this in such cases you should use custom grid number, like this: https://jsfiddle.net/IonDen/2Lpr9er2/

**Comment by IonDen** [comment]
@alexrugik: demo for you: https://jsfiddle.net/IonDen/8c148aee/

**Comment by ptomkiel-oktawave** [comment]
As this bug's closed is it fixed now?

**Comment by IonDen** [comment]
@ptomkiel-oktawave, it is not a bug, see demos to set proper setup.
