### ISSUE TITLE
Unbalanced Steps within Specified Ranges

### ISSUE THREAD

**Issue by solepixel** [IonDen/ion.rangeSlider#375]
Just curious if this is possible or can be tagged as a feature request. I'd like to be a bit more precise with smaller numbers, and not so much with larger numbers. For example, for the range of 0-20, I'd like to step through at 0.25, but 20-50, I'd like the step to be 0.5, and from 50-100, step at 1. It would also be handy if the interface was a little different for these step sections as well.  So the 0-20 range could be as wide or wider than the 20-50 range. The 50-100 range could be smaller than the others since there are less steps, since the steps gradually increase as the number increases.

Sorry if this explanation is a bit confusing. Here's a rough idea of what I'm talking about: http://3cd.co/1C1A3k1E3Z3K - The example implementation is for Lot Sizes for houses/real estate. Note that the 50-100 range is smaller than half since there are only 50 steps, but the range between 0-20 has 80 steps (@ 0.25), so it's wider, and the range of 20-50 has 60 steps (@ 0.5).

So really what I'm asking for is:
1. Ability to change Step value based on range
2. Have the grid scale based on total steps in range, instead of equidistant.

The only other way I can think to explain it is by using this mixer board slider: http://3cd.co/0r1J1C1j1r16 Note how the numbers get tighter the further down the slider goes and the larger the value.

**Comment by IonDen** [comment]
In this version there is no such a build in feature. But, you can always do something close, using prettify function. Check this demo to got the idea: http://jsfiddle.net/IonDen/st9eotpy/

**Comment by solepixel** [comment]
Can you use a callback function for the step parameter and do something similar? That might do the trick.

**Comment by IonDen** [comment]
No, you could only modify the final value, but you can emulate step in where, just play with Math.round at the end of transformation.
