### ISSUE TITLE
Slider does not work in element with position:absolute 

### ISSUE THREAD

**Issue by csweaver** [IonDen/ion.rangeSlider#377]
If I include and ion range slider in a div that had the style position:absolute, the slider is displayed incorrectly. See example:
http://jsfiddle.net/charklet/w8wqb8jo/

**Comment by IonDen** [comment]
Hi, of course it is, you should set some width to this container, like this: http://jsfiddle.net/w8wqb8jo/1/

**Comment by csweaver** [comment]
Thanks, that worked.

**Comment by IonDen** [comment]
Np
