### ISSUE TITLE
click after dragging does not call onchange

### ISSUE THREAD

**Issue by yene** [IonDen/ion.rangeSlider#378]
Steps:
- in chrome
- grab knob
- move knob to the left
- let knob go
- click on the slider

Problem
- the click after does not fire a onChange
- it fires a onFinish again

**Comment by IonDen** [comment]
Thanks.

**Comment by boylove142** [comment]
My workaround, use both the `onFinish` and `onChange` to update value. 

- `onFinish` to update value after click and drag events and prevent `onChange` not fire bug.
- `onChange` to update value during drag event.
