### ISSUE TITLE
Dinamic Values 

### ISSUE THREAD

**Issue by rafatriolo** [IonDen/ion.rangeSlider#379]
Hi , first of all thanks for this plugin, it is really helping me with my project. However I have a question , is it possible , to dinamic create the array witch is in "values" property ? For example : 

$range.ionRangeSlider({
            type: "single",
            values: [
              Make a loop to populate the values!
            ],
            }

I don´t know if a made my self clear. 

Tks

**Comment by IonDen** [comment]
Of course, do this: :)
```
var myValues = [];
for (var i = 0; i < 10; i++) {
    myValues[i] = "something";
}

$range.ionRangeSlider({
    values: myValues
});
```

**Comment by rafatriolo** [comment]
It´s work perfect! Sorry to bother you , but can you help in one more thing? I´am building a price range for my project. What I can´t figured out is that if I have in array values like : var myvalues["R$200,00" , "R$300,00" , "R$100,00"] how to sort this into min - max values? 

Tks again!

**Comment by IonDen** [comment]
You should not work with styled numbers like this "R$200,00", you should work with numbers itself: 200.
But, then you want to show this numbers, you can prettify them as you like, examples:
http://jsfiddle.net/IonDen/xcwx2xse/
http://jsfiddle.net/IonDen/j0tLzgq1/
