### ISSUE TITLE
Click without dragging fails to update values

### ISSUE THREAD

**Issue by vnportnoy** [IonDen/ion.rangeSlider#380]
This is what I do using a double slider:
- Click on a middle value
- Min limit moves, but neither onchange or onfinish is called
- Click back to the min limit
- Now drag to the same middle value, now onchange/onfinish is called perfectly
- Back to the min limit
- Try to click again (not dragging) to the middle value
- This second attempt works

This test was made using the last version of Chrome.

**Comment by IonDen** [comment]
Hi, thanks for finding this bug.

**Comment by IonDen** [comment]
Should be fixed in 2.1.5
