### ISSUE TITLE
onFinish is not working in ionRangeSlider

### ISSUE THREAD

**Issue by Raghava525** [IonDen/ion.rangeSlider#383]
Can you please provide the what is the bug in the following code

```
$("#my_slide").ionRangeSlider({
    type: "double",
    min: 1000,
    max: 12000,
    step: 500,
    force_edges: true,
    onFinish:function () {
		alert('slider drag finished');
		}     
});
```

There is no alert after finishing the click and drag on slider.

**Comment by IonDen** [comment]
http://jsfiddle.net/278ktdnz/
It is working.

You may have some local JS-issues, open web developer console and look for errors.
Remember, if you are using some other code, alert function could be changed in it and will do nothing, like this:
http://jsfiddle.net/278ktdnz/1/

**Comment by Raghava525** [comment]
Still its not alerting the result after completion of slider dragging from the link you have provided too .....
Please provide one example to alert a statement after finishing the slide drag.

**Comment by IonDen** [comment]
This link will have alert after drag: http://jsfiddle.net/278ktdnz/
If you don't see alert, then you have some problem with your browser, or maybe some browser extension, which blocks it.

**Comment by Raghava525** [comment]
Ok Thankyou. Its working fine. You can close the discussion. :)

**Comment by valtido** [comment]
Why does this `onFinish` event triggers when the page first loads up? or when it is initialized ?

this is really puzzling me.

**Comment by IonDen** [comment]
@valtido, it was the recent change to slider core, which i will probably revert soon, because it is really confusing.

**Comment by valtido** [comment]
Ok, cool, could you keep us posted please, I'd like to update to that version :)

**Comment by mobilemeneer** [comment]
@IonDen Did you revert the change to slider core for the onFinish event which is auto triggered with a page load? This is causing a heavy load on my page because i use three sliders which all post to the db.

Many thanks in advance.

**Comment by IonDen** [comment]
@mobilemeneer, revert will be ready next week

**Comment by mobilemeneer** [comment]
Thanks man

I could also install an older version but now I will wait for next week


Op do 9 mrt. 2017 om 21:43 schreef Denis Ineshin <notifications@github.com>
