### ISSUE TITLE
ionRangeSlider Uncaught TypeError: Cannot read property 'update' of undefined

### ISSUE THREAD

**Issue by myblinks** [IonDen/ion.rangeSlider#384]
Please help me!
My Code:
// Saving it's instance to var
        var slider = $("#result").data("ionRangeSlider");
        // UPDATE - updates slider to any new values
        slider.update({
            from: 35.6,
            to: 40
        });
My issue:
Uncaught TypeError: Cannot read property 'update' of undefined

Please help me
Thanks

**Comment by IonDen** [comment]
Hi, what is `#result`? Show me all code.

**Comment by the-teacher** [comment]
I think, this user just has a few instances with the same `id`. Second one can be created with any copy/append operations. It's not a bug of this solution
