### ISSUE TITLE
Prettify not applied to String values

### ISSUE THREAD

**Issue by gerbyzation** [IonDen/ion.rangeSlider#385]
Hi,

It seems that the prettifier function isn't applied to strings, is this intended behaviour or a bug?

In my particular use case I'm displaying version numbers (eg 8.12.2) which are stored zero-padded (008.012.002) for database reasons. Before displaying I need to parse the values to remove the padding, something ideally done with the prettify method.

Cheers

**Comment by IonDen** [comment]
I can't apply prettify to strings, it could bring strange results potentially. So, you should do it outside, like this: http://jsfiddle.net/zq49ffk5/

**Comment by gerbyzation** [comment]
Ok, thanks, that works fine!

**Comment by IonDen** [comment]
NP
