### ISSUE TITLE
Any way to print in PDF with mPDF ?

### ISSUE THREAD

**Issue by crouti** [IonDen/ion.rangeSlider#386]
Hello,
It seems the html object is not recognized by mPDF (Gravity PDF) during PDF transformation, any solution ? like transforming as a png ?
Thanks !

**Comment by IonDen** [comment]
Hi, try to use HTML5-skin. Or create any other skin with no images and contrast colors for it.
Try to print this page: http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html
and you will see, that elements of slider are visible.
