### ISSUE TITLE
Slider positions persist when reinitializing

### ISSUE THREAD

**Issue by gerbyzation** [IonDen/ion.rangeSlider#387]
Hi there, got another question.

I'm making a simple wrapper so I can use the slider in React. When updating the slider with a new array of values, I'm destroying it and reinitialising, but after initialisation the sliders are positioned at their old indexes when the new values is a bigger array.

```javascript
export default class Slider extends React.Component {
  renderSlider = () => {
    let {values, labels} = this.props;
    let {slider} = this.refs
    let disable = values.size < 3 ? true : false;

    let that = this;
    $(slider).ionRangeSlider({
      disable: disable,
      type: "double",
      grid: true,
      hide_min_max: true,
      values: values,
      onFinish: this.props.onFinish
    });
  }

  componentDidMount() {
    this.renderSlider();
  }

  shouldComponentUpdate(nextProps, nextState) {
    return nextProps.values !== this.props.values;
  }

  componentWillUpdate(nextProps, nextState) {
    $(this.refs.slider).data('ionRangeSlider').reset();
    $(this.refs.slider).data('ionRangeSlider').destroy();
  }

  componentDidUpdate(prevProps, prevState) {
    this.renderSlider();
  }

  render () {
    return <input type="text" name="slider" ref='slider' value="" />
  }
}
```
When the values have changed, the order of executing is this:
```
componentWillUpdate -> render -> componentDidUpdate
```
I've tried accessing the data attribute after calling .destroy() and before rerendering which doesn't bring anything up. 

I've created a JSBin where I'm not using react and the issue is there as well: https://jsbin.com/gemake/2/edit?html,js,output The jQuery data attribute is empty after .destroy() so I'm not sure how this information is being persisted.

If you could share your thoughts on this that would be great!
Thanks!

**Comment by IonDen** [comment]
F**c JSbin. Here: http://jsfiddle.net/1j8p6o3z/
Best way to call update.

**Comment by gerbyzation** [comment]
Ah, makes life much easier! Somehow thought I couldn't update the values this way, my bad!

Thanks for being so helpful and this great project!

**Comment by IonDen** [comment]
Np)

**Comment by H0uss3m** [comment]
does this Slider works in reactjs i didnt know where to initialize .ionRangeSlider()

this is the code i set : 
import React ,{Component} from 'react'
import {ionRangeSlider} from 'ion-rangeslider'
const $=require('jquery')
class Menu extends Component {
    componentWillMount(){
        $(document).ready(function() {
            $(".js-range-slider").ionRangeSlider();
        } );
    }
    render() { 
        return (  <div>
             <input type="text" class="js-range-slider" name="my_range" value="" />
        </div> );
    }
}
 
export default Menu;
and this is what i got as an error : 
"TypeError: $(...).ionRangeSlider is not a function"

**Comment by gerbyzation** [comment]
@H0uss3m yes it does work with react, but this issue isn't the appropriate place to ask how or what's wrong with your code.
