### ISSUE TITLE
Throttle/Debounce option for updating of the field

### ISSUE THREAD

**Issue by the-teacher** [IonDen/ion.rangeSlider#391]
Hello! Thanks for this solution! It works really cool!

In my case I have a form with filtering of products by price.
On each update of this form I automatically send request for getting of amount of products in this price range.

ion.rangeSlider updates input value right after slider was changed. In my case it is a reason of sending a lot of requests to server.

Of course I can implement Throttle/Debounce functionality in submit handler of form, but maybe it will be good idea to add new option, something like `delay` of something like this, which will limit a number of update operations of input per second.

**Comment by IonDen** [comment]
Hi, i will think about it, but it is a little strange, 90% that this functionality should be implemented from outside.

**Comment by the-teacher** [comment]
It's just an idea. You can reject it. Thanks for attention to this.

**Comment by the-teacher** [comment]
I solved this situation with simple code

```js
    slider.ionRangeSlider({
      onChange: debounce(ShopFilterRangeSlider.onPriceRangeUpdate, 250)
    })
```
Now it sends request `get_products_count_in_price_range` after 250ms after last `onChange` event. Work like a charm. 👍 


![screen shot 2016-07-06 at 12 10 47 am](https://cloud.githubusercontent.com/assets/496713/16600230/25fc7b7a-4317-11e6-8846-affd7343831b.png)

**Comment by IonDen** [comment]
You see, no need to add this in to range slider code.
