### ISSUE TITLE
Feature Request: support for 'range' data type.

### ISSUE THREAD

**Issue by JustinTBrown** [IonDen/ion.rangeSlider#392]
Currently this only seems to support 'single' and 'double' data types. As such, two values seem to be concatenated with a semi-colon (;) in between, but my app requires values to be submitted as ranges joined by dashes (-). Any hope of these being supported? Thanks!

**Comment by IonDen** [comment]
Hi, this is supported. User `input_values_separator` param to do that:
`
input_values_separator: "-"
`

**Comment by JustinTBrown** [comment]
Oh wow, I completely missed that even after looking through the options. Many thanks @IonDen!

**Comment by IonDen** [comment]
Np)
