### ISSUE TITLE
Display the number after the decimal place irrespective of its value

### ISSUE THREAD

**Issue by aalokm** [IonDen/ion.rangeSlider#396]
Hi,

I am trying to get the slider to show decimal values irrespective of the number after decimal point. i am able to do so when the number is greater than 1, e.g.3.6/4.2 etc. But if it is equal to 0 e.g. 3.0/5.0 etc. then it just shows the number. 
Can we force the slider to display the number after the decimal place irrespective of its value?

Please find the JSFiddle link below
[http://jsfiddle.net/aalok/726L0aj5/7/](http://jsfiddle.net/aalok/726L0aj5/7/)

**Comment by IonDen** [comment]
Hi, you should use prettify function for that.
Example: http://jsfiddle.net/Lh6aoaep/

**Comment by aalokm** [comment]
Hi,

This is exactly what I was looking for. Not sure why I hadn't thought about it. 
Thanks a ton!
