### ISSUE TITLE
ion.rangeSlider re-initialise on inputs added later dynamically

### ISSUE THREAD

**Issue by katwekibs** [IonDen/ion.rangeSlider#398]
Hi can any one please show me how to re-initialize ion.rangeSlider to a dynamically added input element bellow?

When this part of html is return from a jquery post, it show just as a normal input field. Until the user refreshes the page.

Is their any way that i can use delegation to come around my problem? thanks

```
 <p>
    <input
     class="measures"
     type="text" 
     data-min="<?php echo $measure->getCurrent(); ?>"
     data-from="<?php echo $measure->getCurrent(); ?>"
     data-max="<?php echo $measure->getTarget(); ?>"
     data-to="<?php echo $measure->getUpdate(); ?>"
     data-type="double"
     data-grid="true"
     data-grid-num="10" 
     value="" 
   />
</p>
```

**Comment by IonDen** [comment]
Hi. If you are adding input via AJAX request, you should start plugin for that new input manually. Like this:
```
$.ajax({
    ...
    success: function (html) {
        $target.append(html); // append new HTML
        $target.find("input").ionRangeSlider(); // launch slider
    }
    ...
});

**Comment by katwekibs** [comment]
Thanks it worked
