### ISSUE TITLE
Slider basic color modification

### ISSUE THREAD

**Issue by vanetreg** [IonDen/ion.rangeSlider#399]
Hello,
that would be great to be able to modify a slider color from code. 
I mean eg. in 
_$("#range_29").ionRangeSlider({
    type: "double",
    min: 0,
    max: 10000,
    step: 500,
    grid: true,
    grid_snap: true
});_
there would be 1 (some) color parameter which would override the selected skin's colors. I might not like for example the HTML5 skin's blue and I'd prefer to select another one.
Thanks,
Best,
V

**Comment by IonDen** [comment]
Hi, improved skin support will be available in 3.0 version. Subscribe for updates.
