### ISSUE TITLE
Inverse range slider

### ISSUE THREAD

**Issue by vgirase** [IonDen/ion.rangeSlider#400]
Can we have the range slider inverted as shown in pic below?

![image](https://cloud.githubusercontent.com/assets/20777990/17302819/a246dfb6-583b-11e6-8410-13bb4a624dd8.png)

**Comment by IonDen** [comment]
Hi, for now just invert colors on the skin.
Version 3.0 (coming soon) will support this.

**Comment by vgirase** [comment]
Thanks a lot.
I inter-changed the background position for line and bar classes and it worked as expected.
I appreciate the work you guys have put in for this plugin as it looks really great.

Thanks.
