### ISSUE TITLE
Set this to ion.rangeSlider object for callbacks.

### ISSUE THREAD

**Issue by mKlus** [IonDen/ion.rangeSlider#402]
Would it be possible to set `this` in the callback functions to a ion.rangeSlider object?
In the current version (2.1.4) the callbacks are called as below:

`this.options.onStart(this.result);`
which means that `this` is set to the options object.

Can that be changed to 
`this.options.onStart.call(this, this.result);`

Would be nice to have `this` set properly for onStart, onChange, onFinish, onUpdate and prettify.

**Comment by IonDen** [comment]
Good idea. I will add this in 3.0.

**Comment by mKlus** [comment]
Could you consider adding this to 2.1.7 or 2.2.0 release?
The new 3.x seems to be few weeks/months away and also would probably be a lot different so it would take us bit more time to adopt our styles and other workarounds to the 3.X version...

**Comment by IonDen** [comment]
Hello, i will think about it.

**Comment by mKlus** [comment]
Any update? :)

**Comment by IonDen** [comment]
@mKlus 
Implemented in 2.2.0

**Comment by mKlus** [comment]
@IonDen Thanks for fixing this.
The scope is now passed to onStart, onChange, onFinish and onUpdate callbacks. However it's not passed to the prettify callback.
Can you please fix that?

**Comment by IonDen** [comment]
@mKlus, prettify is not a callback function. Give me a real life example, why you would need this?

**Comment by mKlus** [comment]
Let assume I have the following options and using prettify and onChange callbacks.
`
let options = {
    ...
    prettify: function(num: any): string {
        const ionRangeSlider = this;
        // some code accessing ionRangeSlider properties, i.e.
        var max = ionRangeSlider.result.max * 1000;
    },
    onChange: function(data: any) {
        const ionRangeSlider = this;
        // some code accessing ionRangeSlider properties, i.e.
        var movingThumb = ionRangeSlider.target !== 'both'
    },
    ...
`
The options are then used to create ionRangeSlider object
`
this._ionRangeSlider = $(ionSliderElement).ionRangeSlider(options).data('ionRangeSlider')
`

However, the onChange and prettify are called before the this._ionRangeSlider is resolved.
So the best way to access the ionRangeSlider object is if it was passed into the prettify and onChange callbacks.

I haven't tried using version 2.2 yet but I believe that it wouldn't work for me anyway because I have to pass the scope to the options. I really want the scope to be set automatically to ionRangeSlider object.

**Comment by mKlus** [comment]
See this jsfiddle that shows the issue.
http://jsfiddle.net/nb75n1ft/

**Comment by IonDen** [comment]
@mKlus, ok, so we are speaking about different problem. A moment then slider instance is created.
I can try to fix that.

But passing scope to prettify function? I don't think so. Prettify is an utility function to transform visual look of numbers. 9000 -> "9,000" and so on.
