### ISSUE TITLE
Handle is moving back to its starting position after filter is set.

### ISSUE THREAD

**Issue by vanetreg** [IonDen/ion.rangeSlider#404]
Hello,
I use ion.range.Slider bundled with a plugin sold on Envato and named Woocommerce Product Filter.
After moving upper handle the filter value is set correctly but the handle goes back to its original position.
You can test it here:
http://shopydoo.info/bolt/

I use this code with HTML5 skin:
$(\\\"#range_04\\\").ionRangeSlider({
type: \\\"double\\\",
grid: true,
min: 0,
max: 10000,
from: 0,
to: 10000,
postfix: Ft,
prettify_enabled: true,
force_edges: true
});

Pls. see either plugin or some other WP component adds \ before " after each save of that plugin page ( problem also exists if I remove \ )
and also pls. note 
postfix: Ft is 
used instead of the code shown on your page like:
postfix: "Ft"
If I use the latter, the handle label would show like:
1 000 "Ft

Any idea, silution is appreciated,
thank you,
Vane

**Comment by IonDen** [comment]
After each price range change, you should also change plugins from and to attributes on backend part.

Like this:
1. You moved 1 handle from 0 to 2000
2. Page reloads with new price range
3. While doing so, you change `from: 0,` to `from: 2000` in plugin config
4. Profit!

**Comment by vanetreg** [comment]
I informed the plugin developer about it, I hope he will fix the plugin soon, thanks!
