### ISSUE TITLE
Scroll not updating on first scroll

### ISSUE THREAD

**Issue by mikila85** [IonDen/ion.rangeSlider#406]
Reproduce:
1) go here.
[JSFiddle reproduction](http://jsfiddle.net/r108eq2c/28/)
2) scroll only one tick right.... "Result label" updates.
3) drag the slider one tick right/left, dont leave mouse.. "Result label" does not update untill you leave mouse or you drag Another tick.

expected result:
onChange event should be fired on any change even only one value change right/left.

**Comment by IonDen** [comment]
I see it, thanks.

**Comment by IonDen** [comment]
Should be fixed in 2.1.6
