### ISSUE TITLE
Disjointed slider bar with custom values

### ISSUE THREAD

**Issue by jiezandus** [IonDen/ion.rangeSlider#407]
Hi I have included the following code to incorporate a range slider for a series of phases, but the bar appears to be disjointed, with the left tip detached. Did I do something wrong or this is a bug?

Here is my code: 

`<div class="col-lg-11">
            <input type="text" id="range_02" name="example_name" value="" />
            </div>`

`$("#range_02").ionRangeSlider({
    from: 3,
    step:1,
    values:["Planning",
        "Financing","Land Acquisition",
        "Design","Construction",
        "Marketing","Operation"
    ],
    onFinish: function(data){
        console.log(data);
    }
});`

![screen shot 2016-08-18 at 3 26 13 pm](https://cloud.githubusercontent.com/assets/19626436/17787698/2326a87c-6558-11e6-95ab-f45ad0fe744c.png)

**Comment by IonDen** [comment]
Hi, this could be your site problem, maybe some styles collision.
Try to reproduce it here: http://jsfiddle.net/IonDen/726L0aj5/

Or provide an online demo

**Comment by jiezandus** [comment]
Jsfiddle had it all nice and clean. I will dig into my site more - it is indeed a local problem. Thank you so much!
