### ISSUE TITLE
Logarithmic values

### ISSUE THREAD

**Issue by zdarovka** [IonDen/ion.rangeSlider#410]
I think many people will appreciate, including me, if slider could have logarithmic characteristic. Like on screenshot

![psychobig](https://cloud.githubusercontent.com/assets/5191607/18425360/274c7782-78b9-11e6-95ab-bd9160155f78.jpg)

**Comment by IonDen** [comment]
Hi, you can do it now lots of ways, check this thread https://github.com/IonDen/ion.rangeSlider/issues/42

Maybe i will build in this functionality in 3.x

**Comment by zdarovka** [comment]
Thank you very much, I have overlooked this thread.
