### ISSUE TITLE
How to use time scale

### ISSUE THREAD

**Issue by koup** [IonDen/ion.rangeSlider#416]
How can I make a range of 2 times and the right steps between?

e.g.: 08am - 08pm steps 30 minutes

thanks

**Comment by IonDen** [comment]
Hello, demo with Moment.js:
http://jsfiddle.net/tvn2ckj2/

As you see, to work with dates, you should convert them to Unix ms timestamp

**Comment by Devary** [comment]
IonDen thank you very much you saved my life
