### ISSUE TITLE
Config params min: 100, max: 0 give strange results

### ISSUE THREAD

**Issue by immwi** [IonDen/ion.rangeSlider#417]
I like to set a scale from 0 to 100 in reverse order, that is from 100 to 0.
Setting the params min: 100, max: 0, step: 1 (or step: -1) breaks the slider.

A possible workaround is partially failing:
Explicitely defining the values with param values: [100,99,98,97,...,1,0] still returns wrong values in 'data.from'.

**Comment by IonDen** [comment]
In 3.x it will be possible to do a reverse easily. Now follow this demo:
http://jsfiddle.net/IonDen/wawgd9w2/

**Comment by immwi** [comment]
Great, thanks for the help!
