### ISSUE TITLE
can we apply Prettify function & Prettify separator together?

### ISSUE THREAD

**Issue by aalokm** [IonDen/ion.rangeSlider#418]
Hi,

Is it possible to apply both the Prettify_seprator & Prettify custom functions applied in the same slider? I have tried it but no luck as such?

PFA the Fiddle here.

**Comment by IonDen** [comment]
Hi, nope, but you may re use default prettify code in your prettify function.
The default code is this:
https://github.com/IonDen/ion.rangeSlider/blob/master/js/ion.rangeSlider.js#L1825

**Comment by aalokm** [comment]
Hi,

Sorry, I forgot to add the link in my initial comment. The link [here.](http://jsfiddle.net/Lh6aoaep/2/) 
Thank you for confirming it. If we modify the labels directly usign $.number() plugin for static sliders, would it work?

**Comment by IonDen** [comment]
Inside prettify function you may use any code to transform values as you want. It could be a plugin, why not.
