### ISSUE TITLE
Web - demo interactions little mistake?

### ISSUE THREAD

**Issue by Lajdak** [IonDen/ion.rangeSlider#420]
In this URL http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html , example 'reset range slider' (in my opinion) is mistake in this line: 'var slider = $range.data("ionRangeSlider");' if i use this i get error: ReferenceError: $range is not defined. So i am to replace it by this: '$("#my-hardcore-id").data("ionRangeSlider");' and it is ok now.

**Comment by IonDen** [comment]
Hi, yes, it is a mistake in demo code.

**Comment by IonDen** [comment]
Fixed in 2.1.8
