### ISSUE TITLE
Showing all the array values in grid

### ISSUE THREAD

**Issue by prabhukhanna** [IonDen/ion.rangeSlider#422]
Is there any way to show all the values in an array in grid. My array is given below.
 ["0", "0.5", "0.613", "1", "1.7", "2", "3.75", "4", "7", "7.5", "8", "15", "15.25", "16", "17.1", "22.5", "30", "30.5", "32", "34.2", "60", "60.5", "61", "64", "68.4", "117", "122", "160", "244", "256", "488", "732", "976", "1952"].

I am trying to show all the values. But it gives me only specific values like below.
![screenshot from 2016-11-11 18-38-28](https://cloud.githubusercontent.com/assets/8287746/20216018/1188f376-a83e-11e6-993a-5a0f799a392e.png)

`$("#ionrange").ionRangeSlider({
    type: "single",
    grid: true,
    values: array
 });`

**Comment by IonDen** [comment]
Hi, it should work from the box, look at this example:
http://jsfiddle.net/IonDen/n7asv2y7/

If some values are missing, maybe they was excluded because of collision calculation.

**Comment by prabhukhanna** [comment]
@IonDen Many thanks for your reply. 
I think, the values in the array in the example you have given above contains less values. When I replaced those values with mine, I am not getting all the values in the grid.

![screenshot from 2016-11-11 19-20-09](https://cloud.githubusercontent.com/assets/8287746/20217023/e362a40a-a843-11e6-9ff4-3325f8cd6e81.png)

**Comment by IonDen** [comment]
Yeah, if there are too much values, some of them will be dropped because they are overlapping neighbors.

**Comment by prabhukhanna** [comment]
Fine. Is there any property or way to show the values even if the value overlap with neighbours.

**Comment by IonDen** [comment]
Sorry, but no. Maybe in 3.x i will think about it.

**Comment by prabhukhanna** [comment]
Cool. Thanks again.
