### ISSUE TITLE
Is it possible to have more then 2 handles?

### ISSUE THREAD

**Issue by BlureX** [IonDen/ion.rangeSlider#425]
Hi there, I was wondering if it was possible to add more then 2 handles in the slider. Ideally, I would like to have an extra handle which moves on the slider based on some external events and not restricted by the other sliders in terms of position.

**Comment by IonDen** [comment]
Hi, no. Multi handle option will be available in 3.0 only.

Now you can place extra slider close to first one and do almost what you want.

**Comment by BlureX** [comment]
Awesome, I can't wait. Any idea when it's going to be released?

**Comment by HwangLong** [comment]
Hi, I'm also waiting this feature. When can you release your 3.0? 
Thanks, IonDen

**Comment by yairEO** [comment]
This is a must!!! such a basic feature 👍

**Comment by IonDen** [comment]
Hello, @yairEO. More than 2 handles will be the main feature of 3.0 slider version, which is under development now.

**Comment by yairEO** [comment]
@IonDen - I will sit by the keyboard and won't eat or drink and only refresh the page until it is done

**Comment by IonDen** [comment]
:)

**Comment by Disane87** [comment]
Any updates about this? 3.0 isn't releases, right?

**Comment by IonDen** [comment]
@Disane87, hi, i don't have much time right now to finish developing 3.0, core is done and i expect to get back to it in the fall.
