### ISSUE TITLE
Disable slider dynamically

### ISSUE THREAD

**Issue by Cirivas** [IonDen/ion.rangeSlider#427]
Hi

I'm using this plugin with AngularJS, but I can't dynamically disable an Slider. The disable option only take in account the initialization value, but when it change via checkbox, other functions, etc, it doesnt update, i.e. the slider can't be enabled/disabled dynamically. 

I'm missing something? There is a way to disable/enable a slider dynamically?

**Comment by IonDen** [comment]
Hello, you should use `update` method to do that. Check this demo:
http://jsfiddle.net/IonDen/t936wtjv/
and this
http://jsfiddle.net/IonDen/ctkouh69/

**Comment by Cirivas** [comment]
Thanks for the information and examples. However, implement this with AngularJS will be a bit challenging.

Thanks anyways!

**Comment by IonDen** [comment]
@Cirivas NP!
