### ISSUE TITLE
Bug or No

### ISSUE THREAD

**Issue by webmarkelov** [IonDen/ion.rangeSlider#429]
Привет! у меня сегодня не большие траблы случились в одном проекте, когда то я инициализировал слайдер на div после обновления до версии `2.1.5` все сломалось, начал дебажить обнаружил что `val`  у меня` undefined` 

на этой строчке кода все сломалось:
`val = val.split(config_from_data.input_values_separator || options.input_values_separator || ";");`
не может прочитать свойство `split `

может обновить условие? и будет возможность работать  не только с `input`  ))
`if (typeof val == 'string' && val !== '' )`

**Comment by IonDen** [comment]
Ок, я конечно добавлю, но использовать `div` вместо `input` - это как то странно, убивается базовый функционал по записи параметров в value.

**Comment by webmarkelov** [comment]
ага, на 100% согласен, зачем так сделал уже не вспомнить.

**Comment by IonDen** [comment]
В 2.1.6 будет работать, но при этом покажет предупреждение в консоли.
