### ISSUE TITLE
How can I change the colors of the irs-bar and irs-line?

### ISSUE THREAD

**Issue by pmirandaarias** [IonDen/ion.rangeSlider#435]
I made two new classes for irs-bar and irs-line:

irs-bar-yellow
irs-line-yellow
irs-bar-red
irs-line-red

I need to use them based on external radio buttons if they are checked or not, and only when I change the value of the rangeslider. I've read something about:

var irs_line_yellow = $(".irs-line-yellow");

and then on the  .ionRangeSlider({

onChange: function(e){
    irs_line_yellow.css({some properties});
    etc...

Is there a way to call different classes (different colors of the bar and line) in the onChange: function of the slider?

**Comment by IonDen** [comment]
Hi, no. You should do it different way:
1. Wrap a slider in to external container
2. Set color modificator to this container
3. Inherit line color from this modificator, like this:
```
.container.color-yellow .irs-line {
    background-color: yellow;
}
.container.color-red .irs-line {
    background-color: red;
}
```

**Comment by pmirandaarias** [comment]
Excuse me, I don't get it. This is my code where I call the input:

<div className="uk-width-1-4">
    <input type="text" name="timewmsslider" ref="timewmsslider" />
</div>

That input is being generated with the default irc-line and irc-bar css classes. So, how should I call if I have this classes in the css (for both colors red and yellow)? 

.irs-line-yellow {
    height: 16px;
    top: 24px;
    border-radius:8px;
    border: #EEEEEE 1px solid;
    background: #e9d759; /* Old browsers */
    background: -moz-linear-gradient(top,  #e9d759 0%, #e9d759 70%); /* FF3.6-15 */
    background: -webkit-linear-gradient(top,  #e9d759 0%,#e9d759 70%); /* Chrome10-25,Safari5.1-6 */
    background: linear-gradient(to bottom,  #e9d759 0%,#e9e459 70%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#e9d759', endColorstr='#e9d759',GradientType=0 ); /* IE6-9 */
    position: relative;
    display: block;
    overflow: hidden;
    outline: 0!important;
}

.irs-bar-yellow {
    height: 16px;
    top: 24px;
    margin-left: -7px;
    padding-right: 5px;
    background: #e9d759; /* Old browsers */
    background: -moz-linear-gradient(top,  #e9d759 0%, #e9d759 70%); /* FF3.6-15 */
    background: -webkit-linear-gradient(top,  #e9d759 0%,#e9d759 70%); /* Chrome10-25,Safari5.1-6 */
    background: linear-gradient(to bottom,  #e9d759 0%,#e9d759 70%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#e9d759', endColorstr='#e9d759',GradientType=0 ); /* IE6-9 */
    position: absolute;
    display: block;
    left: 0;
    width: 0;
    border-radius:8px;
    border: #EEEEEE 1px solid;
}

.irs-bar-red {
    height: 16px;
    top: 24px;
    margin-left: -7px;
    padding-right: 5px;
    background: #e95959; /* Old browsers */
    background: -moz-linear-gradient(top,  #e95959 0%, #e95959 70%); /* FF3.6-15 */
    background: -webkit-linear-gradient(top,  #e95959 0%,#e95959 70%); /* Chrome10-25,Safari5.1-6 */
    background: linear-gradient(to bottom,  #e95959 0%,#e95959 70%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#e95959', endColorstr='#e95959',GradientType=0 ); /* IE6-9 */
    position: absolute;
    display: block;
    left: 0;
    width: 0;
    border-radius:8px;
    border: #EEEEEE 1px solid;
}
.irs-line-red {
    height: 16px;
    top: 24px;
    border-radius:8px;
    border: #EEEEEE 1px solid;
    background: #e95959; /* Old browsers */
    background: -moz-linear-gradient(top,  #e95959 0%, #e95959 70%); /* FF3.6-15 */
    background: -webkit-linear-gradient(top,  #e95959 0%,#e95959 70%); /* Chrome10-25,Safari5.1-6 */
    background: linear-gradient(to bottom,  #e95959 0%,#e95959 70%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#e95959', endColorstr='#e95959',GradientType=0 ); /* IE6-9 */
    position: relative;
    display: block;
    overflow: hidden;
    outline: 0!important;
}

I have to change the input classes with those ones depending on externala actions (some radio buttons will change the color of the bar and line via javascript)

**Comment by IonDen** [comment]
Hi, you have this div: `< div className="uk-width-1-4">`

You should add color name to it as an additional class, like this:
`< div className="uk-width-1-4 theme-red">`

So, now, you can update slider skin this way:
instead of creating new `.irs-bar-red`, you should put this code:
```
.theme-red .irs-bar {
    // your css
}
.theme-red .irs-line {
    // your css
}

// and the same for yellow
.theme-yellow .irs-bar {
    // your css
}
.theme-yellow .irs-line {
    // your css
}
```

And now, to switch between red and yellow you will need to switch only one class on a container, without touching sliders code.

**Comment by IonDen** [comment]
I created a demo to show a workaround:
http://jsfiddle.net/IonDen/2sruxk4e/

**Comment by Janitha133** [comment]
> Hi, no. You should do it different way:
> 
> 1. Wrap a slider in to external container
> 2. Set color modificator to this container
> 3. Inherit line color from this modificator, like this:
> 
> ```
> .container.color-yellow .irs-line {
>     background-color: yellow;
> }
> .container.color-red .irs-line {
>     background-color: red;
> }
> ```

It worked. Thank you

**Comment by mtariq786** [comment]
> I created a demo to show a workaround:
> http://jsfiddle.net/IonDen/2sruxk4e/

Great bro, thanks!! it helped
