### ISSUE TITLE
Single-slider line optional

### ISSUE THREAD

**Issue by danniranderis** [IonDen/ion.rangeSlider#436]
Hi,

I can see that as of version 2.0 the single slider now always draws a marked line to its left. Before version 2.0 it didn't.

![selection_078](https://cloud.githubusercontent.com/assets/10196548/21569290/e6bc75a6-cebb-11e6-9f50-f60e2b7d8d43.png)

Is there any way to get the old behavior without using very old code? I have tried looking in the docs/code, but failed to find a setting toggling this.

Thanks in advance.

**Comment by IonDen** [comment]
Hello, to do it now, you should modify slider skin file.
Just remove all styling from this line and it will be find.

In 3.0 this line will be optional.
