### ISSUE TITLE
updated from version 1.8 to latest 2.1.6 now the slidebar is missing

### ISSUE THREAD

**Issue by micha1983** [IonDen/ion.rangeSlider#437]
Hello everybody.

i have seen, that i don't use the latest version of ionrangeslider, so i updated it to 2.1.6
after i changed the following files my slider style was a little bit different.

updated files:
-ion.rangeSlider.skinFlat.css
-ion.rangeSlider.min.js
-ion.rangeSlider.skinFlat.css

Before:
<img width="561" alt="before" src="https://cloud.githubusercontent.com/assets/3142136/21641257/edf78398-d27a-11e6-98b3-56284971dbf9.png">

After:
<img width="567" alt="after" src="https://cloud.githubusercontent.com/assets/3142136/21641038/715447f0-d279-11e6-9c7f-6ebbe1a18438.png">

The reason for the update was, that i want to remove frame around the slider after i update only the js File.
<img width="562" alt="frame" src="https://cloud.githubusercontent.com/assets/3142136/21641314/44f58262-d27b-11e6-89c1-d2e9825fe1fe.png">

Before the update i was not able to use the keyboard.

**Comment by IonDen** [comment]
Hello
* Check if all CSS is new;
* Check if images are also updated, 2.x version is using skin images to draw the background;

If nothing helps, provide a link to online demo to check.
