### ISSUE TITLE
Sliders partially un-draggable in Chrome.

### ISSUE THREAD

**Issue by hughstimson** [IonDen/ion.rangeSlider#439]
Using Chrome 55.0.2883.87 m (64-bit) on Windows 10.

On this site, in the box over the map: https://geocology.ca/scpims-map/

Left slider handle can't be moved from left-most position. Right slider handle can be moved one stop, but only one.

No JavaScript errors.

Problem is not present using FireFox or Edge.

**Comment by IonDen** [comment]
Hi, please show me slider config. It is pretty hard to find it in the code.

**Comment by hughstimson** [comment]
Hi @IonDen, sorry about that, Cloudflare was minifying scripts. I've removed the minification now. The config is:

```
    $('input#entry').ionRangeSlider({
        type: 'double',
        min: 2010,
        max: 2017,
        from: 2010,
        to: 2017,
        grid: true,
        grid_num: 7,
        force_edges: true,
        drag_interval: true,
        onChange: function (data) {
            map.updateParcels();
            map.updatePoints()
        }
    });

**Comment by IonDen** [comment]
Hi, the config itself is working fine: http://jsfiddle.net/IonDen/vrc571t9/

But i can't open you site now, it is offline.

**Comment by hughstimson** [comment]
Hi @IonDen, sorry, the site was briefly down for maintenance. It's available now if you can have a look.

https://geocology.ca/scpims-map/

**Comment by IonDen** [comment]
Hello, i checked a little. Looks like you program is working super slow and it makes everything around to freeze on its execution.

To fix that, you should debug it step by step and find a week spot. This is a best advice i can give to you.
