### ISSUE TITLE
onFinish callback called on instantiation

### ISSUE THREAD

**Issue by mikealexander** [IonDen/ion.rangeSlider#440]
It seems that when you use the "ionRangeSlider" constructor and specify an "onFinish" callback, that callback is executed immediately.  I don't believe this was the case in previous versions.

http://jsfiddle.net/hcfmike/1LfuL9cd/1/

**Comment by mikealexander** [comment]
I now realize that this is intended behavior after seeing PR #390.

**Comment by IonDen** [comment]
Hi, do you think this is bad behaviour?

**Comment by pantagruel964** [comment]
Hi, I like your slider, but onFinish callback make me sad. If you get data via ajax when document loaded, callback initiates redundant request with same data.

**Comment by IonDen** [comment]
@pantagruel964, hi. In 3.x i will try to make it more understandable. Because now, it is needed for some special cases.

To avoid extra ajax request, you can can do something like this:
```
var is_first = true;
...
onFinish: function () {
    if (is_first) {
        is_first = false;
        return;
    }

    $.ajax();
}
```

**Comment by pantagruel964** [comment]
Exactly, thank you! It works. What improvements will be in 3.x version?

**Comment by IonDen** [comment]
@pantagruel964, lots of. The main feature will be multiple handles (not like 1/2 in current).
