### ISSUE TITLE
Change color of the Flat UI Sikin

### ISSUE THREAD

**Issue by gtreimun** [IonDen/ion.rangeSlider#442]
Hi! i would like to know how i can change the color of the slider, iam using the Flat UI skin, it's posible? 
thanks and sorry for my bad english.

**Comment by IonDen** [comment]
Hello, of course, just modify skin CSS file, or create your own skin file from it.

**Comment by shubhamnab** [comment]
I am using angular 2 version of Ion RangeSlider. I am able to use the flat UI skin component but I want to use HTML5 skin components. Please let me know how to use that.
