### ISSUE TITLE
Is it possible  dynamic to change steps values?

### ISSUE THREAD

**Issue by HejVkt** [IonDen/ion.rangeSlider#448]
I want to change steps value if slider value is greater than 30.

I use prettify and onChange, but i want also change steps, but it does not work.
Please look fiddle http://jsfiddle.net/hejvkt/yu68bvwv/

**Comment by IonDen** [comment]
Hi, @HejVkt 
The only possible solution now is this:
http://jsfiddle.net/IonDen/a7rz8qyu/

**Comment by HejVkt** [comment]
Yes, thank you. It's almost works, but I have some negative effects with postfix. When I try to change postfix value from 30 days to 8 weeks. postfix label not changes right away. Look that please http://jsfiddle.net/hejvkt/a7rz8qyu/23/

**Comment by IonDen** [comment]
@HejVkt, hi. Unfortunately labels could not be changed that way, because their change requires slider rebuild via calling update method.

Prettify function is working now only with numbers, not with other elements.
