### ISSUE TITLE
Multiple slider with Drag some limit option

### ISSUE THREAD

**Issue by shuoor** [IonDen/ion.rangeSlider#449]
Hi There,

I am stuck in a situation where i want to show 3 slider at a time in which sum of all three slider value cant go above 100.

Suppose i set the slider1 value to 50, slider2 value to 20. then slider3  cant be drag above 30. and vice versas for all three sliders. if in case user want to slide the slider 3 above 30 then he have to reduce the value from the slider1 or slider2.

Don't want to use disable option as i can slide back or forward to adjust the value from any slider.

Any Help?

**Comment by IonDen** [comment]
Hi, you should so something like that:
http://jsfiddle.net/IonDen/n2sxswv2/

**Comment by shuoor** [comment]
Got it...

But i am unable to do the same thing with three sliders.. Please Help???

**Comment by IonDen** [comment]
@shuoor, this will be your job already :) just use first demo as a reference
