### ISSUE TITLE
Skipping data.from value onChange event.

### ISSUE THREAD

**Issue by shuoor** [IonDen/ion.rangeSlider#450]
HI there, i am facing one more issue.

if i slide the slider very fast. it is skipping some value onChange event.

onChnge: function(data){
console.log(data.from);
}

this resulting as: 1,10, 14

It should come as 1,2,3,4,5,6,7,8

so its giving me random values after skipping some values instead of number in continuity

Any Help?

**Comment by IonDen** [comment]
Hi, you can do nothing with it. And it is not a slider restriction, it is a mousemove restriction.
https://jsfiddle.net/IonDen/q2ygojrr/
