### ISSUE TITLE
How can I install this into the aurelia cli?

### ISSUE THREAD

**Issue by seroth77** [IonDen/ion.rangeSlider#452]
I am trying to use this wonderful slider but not sure how to poperly into the Aurelia CLI.  Please help.

**Comment by seroth77** [comment]
I have done the following:

aurelia.json
`{
            "name": "ion-rangeslider",
            "path": "../node_modules/ion-rangeslider",
            "main": "js/ion.rangeSlider.min",
            "resources": [
              "css/ion.rangeSlider.css",
              "css/ion.rangeSlider.skinHTML5.css"
            ]
          }`

app.js
`$('.slider').ionRangeSlider({
      values: [15, 30, 1, 3, 6, 12, 24]
    });`

app.html
`<input type="text" class="slider" />`

It looks like the slider initializes but the CSS never styles it.  It looks like this

![image](https://cloud.githubusercontent.com/assets/8530148/23333913/945ac69a-fb62-11e6-990d-7a6b5e17805f.png)

**Comment by IonDen** [comment]
Hello, yes, CSS is definitely missing. Check the paths to CSS files
