### ISSUE TITLE
Knockout Integration

### ISSUE THREAD

**Issue by HakamFostok** [IonDen/ion.rangeSlider#453]
Actually I am working with knockout in ASP.NET MVC project. Is there any Knockout Binding Handler which integrate this jQuery plugin with knockout ?

**Comment by IonDen** [comment]
Hi, i did not heard of any. I believe that should be pretty easy, just use Stackoverflow: [one](http://stackoverflow.com/questions/31988029/change-settings-of-custom-jquery-plugin-using-knockout) and [two](http://stackoverflow.com/questions/12895123/jquery-plugins-not-working-with-knockout)
