### ISSUE TITLE
Feature suggestion: slider with gap values.

### ISSUE THREAD

**Issue by Timothyyy** [IonDen/ion.rangeSlider#456]
It will be great, to specify only min/max values of slider and array of gaps, which values will be skip when slider reach them, for example:

```javascript
$("input").ionRangeSlider({
    type: "double",
    min: 1,
    max: 100,
    gaps: [10, 20, 30, 40, 50, 60, 70, 80, 90]
});
```

**Comment by IonDen** [comment]
Hi, you can do it now, like this:
http://jsfiddle.net/IonDen/4qgq9bto/

**Comment by Timothyyy** [comment]
Well, it's tricky way)
But if
```javascript
gaps: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
```

**Comment by IonDen** [comment]
Hehe, if you will show me 2-3 real life situations, why anybody need those gaps, i will think about adding this feature to next release.

**Comment by Timothyyy** [comment]
Well, ok)

1) We have ip camera, which record and archive stream 3 days. Sometimes, camera not recording stream (connection error with storage, camera powered off, some special recording rules: motion detection, only day recording etc.). And we can watch this archive which specified with to values(begin of recording, end of recording) and gaps array(values of this array are intervals, when camera didn't record stream). So with slider we can move in this archive, skipping this gaps.
2) We have list of completed tasks by day. With slider we chose day and this action loads tasks of this day. But we want to skip weekends and holidays, so need to specify this days.
3) We have list of phones to sell. Each phone has price. So we specify min price and max price, but some prices don't have phones and we want to remove this prices from or priceline. So if we don't have any phone with price 101$ we skip this value and immediately go to 102$ after 100$.

**Comment by IonDen** [comment]
Hi again.
1. In that case it is better to use predefined values array instead of strange gaps
2. Never saw tasks interface with slider instead of calendar :)
3. This thing is usually done with price ranges, that is why slider have "double" option.

Not convinced yet :)

**Comment by Timothyyy** [comment]
> In that case it is better to use predefined values array instead of strange gaps

I already told you, that if there are over 150k values in array, it is very time consuming to prettify values, so better user small array of gaps or set intervals, which which slider will skip)

**Comment by IonDen** [comment]
You should rethink the interface. 150k values on the slider - is impossible to show. It will be not enough pixel density to show all.

So, it should be simplified to something more usable. Like calendar.

I believe that range slider should be used for situations it is best for, trying to use it for every feature is strange.

**Comment by Timothyyy** [comment]
Well, I think using slider as seek bar for video is fairly right decision. Anyway, I found good solution for my problem:
http://jsfiddle.net/kLb2r4qe/12/
Thanks for your fast and constructive feedbacks :)

**Comment by IonDen** [comment]
Thank you!
