### ISSUE TITLE
Another color for specified intevals.

### ISSUE THREAD

**Issue by Timothyyy** [IonDen/ion.rangeSlider#457]
Hi, again) I have another one question. Can I change color for specified intervals of slider, like this:
![untitled1](https://cloud.githubusercontent.com/assets/3677447/23645542/b6046fea-031d-11e7-8fdd-e0b01ca11e65.jpg)
 Thanks)

**Comment by IonDen** [comment]
Where are shadows and limits:
http://ionden.com/a/plugins/ion.rangeSlider/demo_advanced.html
Demos 33-35. But it have different purpose.

Also you can do it yourself:
1. Make a new skin with opaque bar
2. Use marks technique to create an intervals: http://jsfiddle.net/IonDen/spez12kt/

**Comment by Timothyyy** [comment]
Glad to tell you, that I found solutions for all my problems:
http://jsfiddle.net/kLb2r4qe/17/
Your slider is awesome!! :)

**Comment by IonDen** [comment]
Good luck!
