### ISSUE TITLE
Need tooltip when hover on the bar with current value

### ISSUE THREAD

**Issue by iamkhush** [IonDen/ion.rangeSlider#461]
Our users like to know the value before they press on the slider bar. For this we wish if there were a tooltip with current value where user hovers on the slider grid.

**Comment by IonDen** [comment]
Hi, if you have grid enabled, you could guess the value by looking on it.

Adding any other tooltips will bring too much noise to the interface. If you need something like that, add it yourself. It should be quite easy.

**Comment by iamkhush** [comment]
Sure, I would love to contribute to project. Any suggestions or recommendation before I dive deep into the code?

**Comment by IonDen** [comment]
Hi again. You can create your fork. But i'm not accepting any features now, only bugfixes.

This is because version 3.x is under development now. And it will replace current soon.

**Comment by iamkhush** [comment]
Thats great. 
So I imagine there might be many changes in code base and I should start only after version 3 is launched?

**Comment by IonDen** [comment]
Be patient)
