### ISSUE TITLE
Add feature that allowing to choose beetwen "prefix" and "suffix"

### ISSUE THREAD

**Issue by JamesJGoodwin** [IonDen/ion.rangeSlider#462]
Hi. I was searching for a range slider library for a few days and when i found your's, i loved it. I'm having a pleasure when using it, but there's still one feature, that is missing for me. I'd like to choose beetwen prefix and suffix setting. For example, `prefix: '$'` = $1000 and `suffix: '$'` = 1000$. Thanks in advance!

**Comment by IonDen** [comment]
Hi, @JamesJGoodwin, suffix is here, it is called "postfix".
