### ISSUE TITLE
Will this work on wordpress?

### ISSUE THREAD

**Issue by hydraides** [IonDen/ion.rangeSlider#463]
Hey,

How would you go about getting this slider to work in wordpress?

Do you have a downloadable plugin

Thanks

**Comment by IonDen** [comment]
Hello, no, i don't have a Wordpress plugin.

But that should be pretty easy to use, just follow this links:
[One](http://stackoverflow.com/questions/16823679/wordpress-plugin-development-how-to-use-jquery-javascript), [Two](https://premium.wpmudev.org/blog/adding-jquery-scripts-wordpress/?omtr=b&utm_expid=3606929-101._J2UGKNuQ6e7Of8gblmOTA.1&utm_referrer=https%3A%2F%2Fwww.google.nl%2F)

**Comment by hydraides** [comment]
Ok thank you for helpful reply.

Do you have any experience with Mapbox?  I am looking for help in, for what I think is fairly simply task but cannot figure out how to do-  (changing a filter so it updates automatically) 

www.livehazards.com (At the moment I can enter a time value and the filter will grab earthquakes from the last 24 hours. The problem is after 2 or 3 days those earthquake are still being displayed ...when all I want is just earthquakes from the last 24hours). Below is the code for the filter.

Do you have any idea how to do, I would be willing to pay for a solution , thanks

document.getElementById('filterss').addEventListener('change', function(e) {
  var time = e.target.value;
  var filtertime;
  if (time === '24h') {
    filtertime = ['>', 'time', 1490950000000];
  } else if (time === '48h') {
    filtertime = ['>', 'time', 1489090000000];
} else if (time === 'week') {
    filtertime = ['>', 'time', 1488810000000];
} else if (time === 'month') {
    filtertime = ['>', 'time',0];
  } else {
    console.log('error');
  }
  map.setFilter('earthquake-layer', filtertime);

-----
