### ISSUE TITLE
Empty value if range is max

### ISSUE THREAD

**Issue by agolovenkin** [IonDen/ion.rangeSlider#465]
I want to have EMPTY input when range is maximum.
How can I do this?
Thank you.

**Comment by lk77** [comment]
hello,
i need to have this too, i don't know if it's possible.
I have a double range selector of dates, but i need to display infinite or something like that where the range is at the maximum

**Comment by IonDen** [comment]
@agolovenkin, solution for you: http://jsfiddle.net/IonDen/myrybeqc/

@lk77 this is correct way to change visible number: http://jsfiddle.net/IonDen/vzhwbery/
