### ISSUE TITLE
Highlight on focus.

### ISSUE THREAD

**Issue by VjLumens** [IonDen/ion.rangeSlider#466]
Hello, I have 3 sliders on my page. When not active they need opacity 0.3. Any slider I move becomes opactiy 1. If I just click on a opacity 0.3 slider handle, I cant get any event that allows me to change the css. I can only do it on onchange.
What is the correct way to solve this ?
thank you

**Comment by IonDen** [comment]
Hi, @VjLumens 

Where is one hidden feature which can help you with this task.

`.irs-line` is always getting focus then you target the slider. This is done for keyboard control.
You can reuse this feature. Check this demo:

http://jsfiddle.net/IonDen/vskpkv3y/

**Comment by VjLumens** [comment]
Thank you. That is exactly what I needed to know, Good answer,
