### ISSUE TITLE
Slider type class name.

### ISSUE THREAD

**Issue by mrtag23** [IonDen/ion.rangeSlider#467]
Just got a case when I have two different designs for single type slider and a double type slider. It would be very cool to have a slider type class name on the most top wrapper, like `irs-single` and `irs-double` which will really help when you need to switch bar's or other elements styles. And thanks guys for such an awesome plugin!

**Comment by IonDen** [comment]
@mrtag23, hi. For now, this is the correct way to change sliders skin on one page:
http://jsfiddle.net/IonDen/2sruxk4e/

in 3.x this feature will be build in and you will be able to change skin via settings.
