### ISSUE TITLE
Grid not align if Max is set to small number

### ISSUE THREAD

**Issue by shuoor** [IonDen/ion.rangeSlider#469]
Grid is not properly align if max is set to smaller value like 5.

attached image and link of fiddle.

<img width="744" alt="screen shot 2017-04-25 at 11 00 30 pm" src="https://cloud.githubusercontent.com/assets/7921016/25398868/23dc0bfe-2a0b-11e7-9844-48b4392e731a.png">

http://jsfiddle.net/qv6yrjrv/810/

Any Help??

**Comment by IonDen** [comment]
Hello, @shuoor, on a very low numbers you should use `grid_snap: true` param.

This will force grid to align to actual numbers.

Example:
http://jsfiddle.net/IonDen/q5hvhut4/

**Comment by shuoor** [comment]
Thanks a lot. Working Perfectly... 💯
