### ISSUE TITLE
Two grids

### ISSUE THREAD

**Issue by klikin** [IonDen/ion.rangeSlider#470]
Hi:

Great plugin !!! but, how can I setup two grids ?
The main grid using the grid options to be shown at the bottom of the bar, as it is right now.
But other grid at the top of the bar, just to have a second values set.

Thank you !

**Comment by IonDen** [comment]
Hi, you can use "marks" technique to add additional items on the grid. Check this demo:

http://jsfiddle.net/IonDen/7aj5j374/

**Comment by klikin** [comment]
Well, I would like a second grid, except "marks" ... I mean a complete grid with the automatic calculation of steps and numbers.

I need a 0 to 100 in the bottom, and a "price" for each step in the top of the bar. Two grids of numbers, setting the begin and end of the two sets and the script do the calculation of bars and numbers (as it does for the main grid).

**Comment by klikin** [comment]
But I guess I can work on that demo and do some tricks with css ;-)

**Comment by IonDen** [comment]
jQuery.clone for the rescue!

http://jsfiddle.net/IonDen/1cbjby56/

**Comment by klikin** [comment]
hahahaha, you are god ! thank you !
