### ISSUE TITLE
Update a slider with a custom value (not in the values set) in a slider with fixed values

### ISSUE THREAD

**Issue by klikin** [IonDen/ion.rangeSlider#471]
Hi there:

I have a rangeslider with custom values set ([1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100, 125, 150, 175, 200, 250, 300, 350, 400, 450, 500, 600, 700, 800, 900, 1000, 1500, 2000, 2500, 3000, 4000, 5000])

User can play with this values,  but I have an external input when the value of the slider is updated. But I would like this input to be changed by the user and set any number, any custom number, for example: 77.

I have noticed that if I update the number of a rangeslider with fixed values, the "ball" goes to the index number of that numbers set.

How can I move the ball to the exact point when the ball should be if instead a set of values it would be a range from 1 to 5000 (in my case) ?

Difficult, uh ? ;-)

**Comment by IonDen** [comment]
Provide the demo.

**Comment by klikin** [comment]
Here is what I have right now:
http://jsfiddle.net/L39v3qpq/

I think I could get this done if instead a custom values set, I use a min and max, but I could create a custom STEPS array, instead a fix step.

I mean, to have: min: 1, max: 500, steps: [1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100, 125, 150, 175, 200, 250, 300, 350, 400, 450, 500, 600, 700, 800, 900, 1000, 1500, 2000, 2500, 3000, 4000, 5000]

**Comment by IonDen** [comment]
1. Reduce numbers for demo reasons
2. Use this demo to work on to of it: http://jsfiddle.net/IonDen/mvrfg2vc/

**Comment by klikin** [comment]
This? ;-)
http://jsfiddle.net/pfsdLs20/

**Comment by klikin** [comment]
The thing is to update the INPUT with, for example, a value of 8 ... so the ball should be placed where the 8 it is in the grid.

As I commented, maybe the solution would be to have a slider with min: 1, max: 100 and a custom array of steps, but now the script just allow one fix step.

**Comment by IonDen** [comment]
You mean something like this?
http://jsfiddle.net/IonDen/q9tqkm25/

**Comment by klikin** [comment]
Hmmm, any change in the input makes the ball goes to the beginning of the slider (to 1)

**Comment by IonDen** [comment]
There is no check where, try exact numbers, 5, 10, 25, 50 etc.

**Comment by IonDen** [comment]
Checking what number is closest to written in input - is your task.

**Comment by klikin** [comment]
What I was saying is that if I put "32" in the input, the slider shows this:
![captura de pantalla 2017-04-28 a las 23 35 34](https://cloud.githubusercontent.com/assets/1673693/25548184/75083748-2c6b-11e7-9b86-c2d1652e055f.png)

**Comment by IonDen** [comment]
If you use values array - not possible.
Use normal range.

But you will not be able to use different step. To override this, check this demos:
http://jsfiddle.net/IonDen/pzjaoxe7/
http://jsfiddle.net/IonDen/st9eotpy/

**Comment by klikin** [comment]
I see the point ... but my needs is to have a slider with steps, because I need a slider from 0 to 5000, and it's annoying to select 500 or 1000 (the most common values will be rounded ones). But I wanted to give the user a chance to select a custom value, and in that case, to update the "ball".

That's because I told you maybe (as a feature) to have a custom value of STEPS, like a steps array, instead a fix number.

Anyway I will play with the "update" function doing a custom one to move the ball to the place it should be. I think that will be the easier workaround. I will update here a demo once done (hopefully in some minutes ;-) )

**Comment by IonDen** [comment]
You may change slider type on first input use. Recreate its instance. Like this:
http://jsfiddle.net/IonDen/yury5qwb/

**Comment by klikin** [comment]
Yes, it's an idea, but (in my case) I would need the slider to work still with the "values" set in the beginning ;-)  I'm about to do it !!

**Comment by IonDen** [comment]
Good luck!

**Comment by klikin** [comment]
Check this out : http://jsfiddle.net/IonDen/q9tqkm25/

Can you help me on the last step ? you know your methods better than me ... the only thing left is to move the ball to that percentage of the slider ;)

**Comment by klikin** [comment]
I would do it with CSS, but I guess you have a quicker and better way to "move that ball to". The problem is that when you set "values" instead of "min/max" the "update :from" method moves the ball to the KEY of the array

**Comment by klikin** [comment]
So is there any method to "move the ball" properly ?

**Comment by IonDen** [comment]
Hi again, there is no such method, you solution is good enough if it fits your needs.

**Comment by klikin** [comment]
Well, it doesn't ... as I explained, when you move the ball to a custom place, the position of the ball (internal position) is still the old one ... so when you try to drag it, it returns to the old position. Where do you store the position of the ball internally ?

**Comment by IonDen** [comment]
The sliders handles are bind to sliders values. If you want to move handle beyond values it will be always a dirty hack.

**Comment by klikin** [comment]
Ok, I did it !! changing the instance.result values manually, and the ball works perfectly although you move it.
