### ISSUE TITLE
double slider active handle lost

### ISSUE THREAD

**Issue by scavazosm** [IonDen/ion.rangeSlider#472]
i notice the `type_last` class gets assigned to the currently selected handle in the double slider, but when updating the slider externally(via buttons), the entire dom gets re rendered and this class always jumps back to the second handle (`to`). This forces me to do many workarounds to be able to keep track of the currently selected handle.

**Comment by IonDen** [comment]
@scavazosm, sorry, but type_last was made for design reasons only, it was not intended to use if as some kind of anchor. Great that you found a workaround to work with it.

**Comment by scavazosm** [comment]
is there a standard way of keeping track of the current selected slider? or is my hack as good as any?

**Comment by IonDen** [comment]
Good as any.
