### ISSUE TITLE
get current context on the input

### ISSUE THREAD

**Issue by deeploy** [IonDen/ion.rangeSlider#473]
hi,

I got a problem to select (with jquery) the input where I am.
I set multiple range by clicking on a button. The problem is that I don't have a uniq selector (like #range1, #range2, etc ..). And I need to set the value of each range on the input with a data-from and data-to for example, with the onChange function.

`$('#streets .range_slider').ionRangeSlider({
              min: 0,
              max: 2000,
              onChange: function (data) {
                  $(this).data("from", data.from);
              }
            });`

And I have to make it like that .. You see the idea ? I can't create selectors before, because I don't know how many the user will need.
Each time, he's clicking on the button, another slider will show (or he can delete it also).

So for me, the only solution would be to get into the current input field and passing data-from and data-to, into it.

I don't know if I explained myself well.

Thanks in advance,
Deeploy.

**Comment by IonDen** [comment]
Hi, object `data` contains all need stuff:
```
onStart: function (data) {
    var $current_input = data.input; // jQuery object with input
    var $current_slider = data.slider; // jQuery object with slider
}
```

**Comment by deeploy** [comment]
ok thanks ;) I didn't see it
you rock ! ^^
