### ISSUE TITLE
How to make smoother movement with small values? Look inside...

### ISSUE THREAD

**Issue by PetrovAleksandr** [IonDen/ion.rangeSlider#474]
```
$("#example_id").ionRangeSlider({
        'type':'double',
        'min': '0',
        'max': '1000',
        'myValues':['4 gb', '6 gb', '8gb'],
        'grid_num':2,
        'grid': true,
        'prettify':function(num){
            if(typeof(this.myValues) === 'object' && this.myValues.length)
            {
                var step = Math.round(this.max/this.myValues.length);
                if(num >= this.max) return this.myValues[this.myValues.length-1];
                if(num < step) return this.myValues[0];
                var curStep = Math.ceil(num/step)-1;
                return this.myValues[curStep];
            }

            return num;
        }
    });
```

**Comment by PetrovAleksandr** [comment]
`$("#example_id").ionRangeSlider({
        'type':'double',
        'min': '0',
        'max': '1000',
        'myValues':['4 gb', '6 gb', '8gb'],
        'grid_num':2,
        'grid': true,
        'prettify':function(num){
            if(typeof(this.myValues) === 'object' && this.myValues.length)
            {
                var step = Math.round(this.max/this.myValues.length);
                if(num >= this.max) return this.myValues[this.myValues.length-1];
                if(num < step) return this.myValues[0];
                var curStep = Math.ceil(num/step)-1;
                return this.myValues[curStep];
            }

            return num;
        }
    });`

**Comment by IonDen** [comment]
Hi, i checked your demo. http://jsfiddle.net/IonDen/726L0aj5/
It is working fine. If you are asking if this functionality is included from the box - no.

**Comment by PetrovAleksandr** [comment]
Please add this note to your examples, I think this example will come in handy. Thank you!

**Comment by IonDen** [comment]
This is a super rare case :)
