### ISSUE TITLE
How to change the pop-up label text when both to and from are the same.

### ISSUE THREAD

**Issue by beriniwlew** [IonDen/ion.rangeSlider#475]
I've got a time range selector going on, and this works... but effects all the pop-up labels on other controls.

How do I get it to only change the label on this specific control? 

var start = moment("1980-11-20 00:00", "YYYY-MM-DD HH:mm");
var end = moment("1980-11-21 00:00", "YYYY-MM-DD HH:mm");
$("#mondayTimeSlider").ionRangeSlider({
                type: "double",
                grid: true,
                min: start.format("X"),
                max: end.format("X"),
                step: 1800,                // 30 minutes in s
                prettify: function (num) {
                    return moment(num, 'X').format("h:mm A");
                },
                force_edges: true,
                grid_snap: true,
                onFinish: function(obj) {
                    if (obj.from === obj.to) {
                        $(".irs-to").empty();
                        $(".irs-to").append("CLOSED");    
                        $(".irs-from").empty();
                        $(".irs-from").append("CLOSED");    
                    }
                }
            });

**Comment by IonDen** [comment]
Hello, you can get the link to current slider instance. Like this:
```
onFinish: function (data) {
    var $slider = data.slider;
    // now you can find items from current slider
    var $local_to_handle = $slider.find(".irs-to");
    // Profit!
}
```

**Comment by beriniwlew** [comment]
B-E-A-eutiful.  Thank you!

**Comment by beriniwlew** [comment]
The same function can't be used on on onStart, because nothing has been labeled yet.

Thus, I can't label my slider as "closed".  Any ideas on how to fix that?

**Comment by IonDen** [comment]
@beriniwlew, this is looking like a bug. You can use this dirty fix:
```
onStart: function (data) {
    setTimeout(function () {
        // do it here
    }, 1);
}
```
