### ISSUE TITLE
Add feature that allow to use custom/uneven intervals

### ISSUE THREAD

**Issue by mohitr-optimus** [IonDen/ion.rangeSlider#477]
Hi team,

I want some ranges which will visually look something like below:
These are some uneven intervals,

![expected](https://cloud.githubusercontent.com/assets/8747594/26445152/b83f059a-415c-11e7-9eef-b418b004ecf8.PNG)

Is it possible ?

**Comment by IonDen** [comment]
It is not possible now. But you always can disable build-in grid and add your own intervals.

**Comment by mohitr-optimus** [comment]
Yes, I am trying the same, but what I need is to click the written measurements. (you cannot click between 2 measurements, it automatically goes to the closest written measurement).

**Comment by IonDen** [comment]
You may create your own event. On click, call sliders update method with the value you need.
