### ISSUE TITLE
Slider not taking css and showing just numbers instead of slider

### ISSUE THREAD

**Issue by apurvgandhwani** [IonDen/ion.rangeSlider#478]
![ion](https://cloud.githubusercontent.com/assets/7307993/26753607/674add08-4887-11e7-9368-c72716b24747.PNG)
In my react application, slider is not showing up. Instead a row of numbers shows up. I am initializing the slider like this

```
$("#ionSlider-newTag").ionRangeSlider({
            min: 0,
            max: 5000,
            type: 'double',
            postfix: 's',
            maxPostfix: "+",
            prettify: false,
            hasGrid: true,
            from: 1600,
            to: 2950
        });
```

I have installed slider via npm. So i am not including any scripts and css links in my html. 

What might be the reason for slider not coming up? There are no errors in console also.

**Comment by IonDen** [comment]
Hello, CSS is missing. You need to include it manually.
