### ISSUE TITLE
Dynamically change start value

### ISSUE THREAD

**Issue by anetk** [IonDen/ion.rangeSlider#480]
I'm using two range sliders on a page and I want these two to be dependent of each other.
My second slider should never be able to contain a lower value than my first slider, it should start from what's being selected on the first slider.

Thoughts on how this could be achieved?

**Comment by IonDen** [comment]
Hello, @anetk 

Use this demo as a reference to solve your problem.

http://jsfiddle.net/IonDen/n2sxswv2/
