### ISSUE TITLE
Using with jquery.repeater

### ISSUE THREAD

**Issue by ulassenol** [IonDen/ion.rangeSlider#481]
I want to use ion.rangeSlider with jquery.repeater. How can i do? Is it possible?

**Comment by IonDen** [comment]
Hello, @ulassenol 

Repeater have callbacks ("show", "hide" and other). On adding/removing set of inputs.
In this callbacks you can create or destroy Ion.RangeSlider instances (check demos about creating and destroying instances on plugins demo-website).

**Comment by ulassenol** [comment]
@IonDen thank yok so much.
