### ISSUE TITLE
Issue updating slider values

### ISSUE THREAD

**Issue by adamBrownGT** [IonDen/ion.rangeSlider#482]
Hello,

Great plugin.

Having an issue updating values within the onFinish method.

See image attached. I have 13 months defined, with now (month 6) being the current month selected so that a user can scroll left or right and it does some actions onchange.

I am trying to update the values so that when the user drags to a new month and onFinish fires, I can get the new month (I can), I can then calculate a new array of months to display (I can) and then update values. But when I try and update values, the slider doesn't update.

Can you assist please? 

Am I allowed to call update on the slider from within the onFinish method of the slider? Is this the issue? If not I will add more info to debug with.

<img width="1225" alt="screen shot 2017-06-23 at 12 11 19" src="https://user-images.githubusercontent.com/29656094/27479742-17011782-580d-11e7-8bed-7a58ffc064e6.png">

**Comment by IonDen** [comment]
Hello, check this demo please:
http://jsfiddle.net/IonDen/nnpjcwun/

Does it solve your problem?

**Comment by adamBrownGT** [comment]
No.

Here's more info.

See attached for console log of the array of months. This log is triggered every time I drag one month to the left (or one value lower). This is correct and shows the months getting earlier. But I cannot assign this array back to the slider - it doesn't update.

`  var $range = $("#slider");
            
            $range.ionRangeSlider({
                type: "single",
                values: getSliderMonthArray(),
                from: 6,
                grid: true,
                onFinish: function (data) 
                {
                    var fromOffset = (6 - (data.from));
					var dateRangeStart = moment(window.config.currentDate).subtract(fromOffset, 'months').format('YYYY-MM-') + "01";
					var dateRangeEnd = moment(dateRangeStart).endOf('month').format('YYYY-MM-DD');
                    
                    window.config.currentDate = dateRangeStart;
                        range_instance.update({
                            values: getSliderMonthArray(), from: 6
                        });
                   
                }
            });
            var range_instance = $range.data("ionRangeSlider");
`

Do you see what I am trying to do?

When I drag one value left it reduces the months as per the array attached and the slider values should update. They do on your demo but not on mine!
<img width="1268" alt="screen shot 2017-06-23 at 12 57 42" src="https://user-images.githubusercontent.com/29656094/27481315-e0e44b7c-5813-11e7-97e6-a077a705325a.png">

**Comment by adamBrownGT** [comment]
Updated version from 2.0.0 to 2.2.0 and it's fixed.
 I feel a little silly now.

Kudos for your help. Great plugin, great support.

**Comment by IonDen** [comment]
:) No problem
