### ISSUE TITLE
Iphone -5(se) Slider does not move.

### ISSUE THREAD

**Issue by jcameron-idc** [IonDen/ion.rangeSlider#483]
Iphone 5se the slider does not respond at all or sometimes the screen its self-zooms in on the user.

**Comment by IonDen** [comment]
@jcameron-idc, i need more details. Slider was tested on iPhones, so, it should be your local problem. Give demo link and info about iOS, browser, slider version etc.

**Comment by jcameron-idc** [comment]
I have attached some screen shots from clients regarding this issue i
myself was not able to replicate this but they said they are using iPhone 5
se

**Comment by IonDen** [comment]
This is not email. You should attach screenshots manually.

**Comment by jcameron-idc** [comment]
My apologies for that, 
<img width="996" alt="screen shot 2017-06-26 at 2 44 18 pm" src="https://user-images.githubusercontent.com/26602501/27593590-87258a1e-5b25-11e7-9bc2-e9925ae9bf2a.png">

<img width="172" alt="screen shot 2017-06-26 at 2 47 20 pm" src="https://user-images.githubusercontent.com/26602501/27593591-8729dd26-5b25-11e7-8d4f-f94a1047ebcd.png">

**Comment by IonDen** [comment]
Interesting, could you provide a link to this website? You can send link to my email if you don't want to post it here.

**Comment by djalmajr** [comment]
I'm facing the same problem:

https://djalmajr.gitlab.io/cashme/simulador/passos.html
