### ISSUE TITLE
Get Current Instance

### ISSUE THREAD

**Issue by sanknm** [IonDen/ion.rangeSlider#484]
$(".range_1").ionRangeSlider({
            min: 0,
            max:100,   
            onFinish:  function (data) {
                if(data.from > 0)
                {
                    $(this).parent('.row').find('.mediumCheckStrategy').removeClass('UnselectedMedium').addClass('SelectedMedium');
                }
                else
                {
                    $(this).parent('.row').find('.mediumCheckStrategy').removeClass('SelectedMedium').addClass('UnselectedMedium');
                }    
            },
            
        });

$(this) not working here . How to get current instance of the slider

**Comment by IonDen** [comment]
You should use data.slider element to access current slider.

**Comment by sanknm** [comment]
Thank You, it was very helpful.
