### ISSUE TITLE
Sliders created in non-active tabs get negative numbers and invalid css views

### ISSUE THREAD

**Issue by mxbranson** [IonDen/ion.rangeSlider#485]
I have 7 sliders per tab (10 tabs) using double sliders. Range is 0 to 24
The active tab displays fine.

Selecting any other tab shows the 'to' bar displayed on the far left of the 'from' bar and the grid numbers are overwriting each other on the far left of the slider.

The correct 'to' and 'from' values are displayed in the current range bubble.
When you move the 'to' bar to a positive position, the slider is correctly displayed but...

The onFinish values show negative numbers for whichever bar was not moved:
fromNumber: -0
fromPers:-0.0676818950930626
fromX:-0.6666666666666666
fromX_pure:0
max:24
min:0
toNumber:3
toPers:12.791878172588833
toX:126
toX_pure:0

![clipboard01](https://user-images.githubusercontent.com/26913495/27770554-e135f1a8-5f83-11e7-81f2-a670e8c0fb6e.jpg)

Weird huh?
Thanks for a great slider!

**Comment by IonDen** [comment]
Hello, of course, inside `display: none` it is impossible to measure slider values. After making tab visible you should at least call sliders `update` method.
The best approach will be to to create slider instance, on making tab visible.

**Comment by mxbranson** [comment]
Your right. I changed the code to rebuild each set after a tiny delay when the (Bootstrap 3) <a data-toggle=tab dom is clicked. Works well now. 
Thanks.
