### ISSUE TITLE
Website demo pages down

### ISSUE THREAD

**Issue by MWDavidH** [IonDen/ion.rangeSlider#489]
Hi,

I can't see demos page,  http://ionden.com/a/plugins/ion.rangeSlider/en.html, 
website is down

**Comment by IonDen** [comment]
Hi, it happens sometimes, it is not super expensive hosting. No need to create github tickets for that.

Besides, you can always check some advanced demos on JSFiddle. https://github.com/IonDen/ion.rangeSlider#experiments-playground

**Comment by MWDavidH** [comment]
Sorry to open an issue for that,
I tried the JSFiddle demo but it's the same because the JS and CSS comes from your domain

http://ionden.com/a/plugins/ion.rangeSlider/static/css/ion.rangeSlider.skinHTML5.css
http://ionden.com/a/plugins/ion.rangeSlider/static/js/ion-rangeSlider/ion.rangeSlider.js

**Comment by IonDen** [comment]
Ah, yes. I will think about using cdn.
