### ISSUE TITLE
Steps, Prettify, Question, Maybe Bug

### ISSUE THREAD

**Issue by doomsayer2** [IonDen/ion.rangeSlider#490]
Greetings together. I am using this fantastic plugin which offers a lot of customization for my current project. I have sadly a very wide range of values and would like to change the slider respectivelfy. I will describe my question and problems as birefly as possible.
(note my datset is huge!)

**Idea:
-------**
_min: 5000
max: 21.000.000.000 (Yes..... sadly)_

The slider values should go in 1000th or 100th or 10000th steps depending on what the values are. Therefore i would first ask is it possible to make `step: function(val) { return roundToFull(val); }`, where the round function is provided by me?
Other then that i can do it with `prettifiy: funciton(val) { return rountToFull(val).toString(); }`... but the slider handles still move very slow..... and if i am for example at 5000 and want to go to 10.000 thats impossible nearly as the range is so high so i need basically a dynamic step adaptation. Other then that you should note that **prettify in typescript expects a string as return** value.  Furthermore i would like to add a grid too. I know thats hard maybe but i can describe it somehow with this ascii art.

|----|----|----|----|----|--------|--------|-------------------------|--------------------------|...
0   500  750  1000  1250 1500     2000     2500                      75000                      100000...

So a not direct linear step size would be great. Mine is the one above mentioned.

THANK YOU!!!!
Thank you for the great plugin too.

**Comment by IonDen** [comment]
Hello, @doomsayer2 
this version of slider does not support non-linear values from the box. But there are some workarounds to do that.

Logarithm:
http://jsfiddle.net/IonDen/7dbowqfd/
http://jsfiddle.net/IonDen/a7rz8qyu/

Multiple ranges on one scale:
http://jsfiddle.net/IonDen/st9eotpy/

Transform:
http://jsfiddle.net/IonDen/fpyceLgq/

**Comment by doomsayer2** [comment]
Thank you for the links and quick reply. I gonna take a look.

I would like to point out that it's a great work and I really like it and it helped me a lot. Thank you.

Cheers

**Comment by oriadam** [comment]
Hi @IonDen, the jsfiddle links that you supplied are not working, have 404 on these URLs (twice per URL):

- http://ionden.com/a/plugins/ion.rangeSlider/static/js/ion-rangeSlider/ion.rangeSlider.js
- http://ionden.com/a/plugins/ion.rangeSlider/static/css/ion.rangeSlider.css
- http://ionden.com/a/plugins/ion.rangeSlider/static/css/ion.rangeSlider.skinHTML5.css

**Comment by IonDen** [comment]
Hi, @oriadam. There is new test playground for plugin: https://jsfiddle.net/IonDen/uqs7njp9/

Old links not working because JSFIDDLE does not allow access to this files now. New test playground uses CDN with latest plugin version.

Please copy code of any demo to this new playground link and it will work. Like this:
https://jsfiddle.net/IonDen/4xst7v6r/

Check also new section in readme doc: 
https://github.com/IonDen/ion.rangeSlider#experiments-playground

All links updated.
