### ISSUE TITLE
Shift currently selected range

### ISSUE THREAD

**Issue by giedroyc** [IonDen/ion.rangeSlider#491]
Hi,

Is there a way to shift current selection to left/right. At the moment I have to slide from and to individually. Would be great if clicking in the middle of the current selection allowed me to drag both at the same time to either side while preserving the difference/distance between from and to selected.

**Comment by IonDen** [comment]
Hello, @giedroyc. Of course, check this demo:
http://ionden.com/a/plugins/ion.rangeSlider/demo_advanced.html#range_121

param - `drag_interval: true`
