### ISSUE TITLE
Seperated prefixes for "from" and "to".

### ISSUE THREAD

**Issue by Gerard987789** [IonDen/ion.rangeSlider#493]
I'm new to this slider and would like to use it for defining opening hours of an establishment. So far so good without any problems.

What I would like to try is getting a prefix for the "from-label" with value "from" and a prefix for the "to-label" with value "to".

If it is not possible, no problems. I'm already very happy with this kind of plugin!

**Comment by IonDen** [comment]
Hi, @Gerard987789, sorry. But in 2.x it is not possible to set individual prefixes/postfixes fore each handle.

**Comment by Gerard987789** [comment]
Ok, no problem.
I was only thinking about this because it might be in some way more efficient for mobile applications. If the label already is explaining the things ('from .. o'clock - til .. o'clock'' / "min .. °C/°F - max .. °C/°F" /"low - high" etc... I don't need to use other space for it.

If I have some time over I will figure it more out and try to collaborate on this point.

**Comment by IonDen** [comment]
This could be useful only for rare cases. Usually users can easily guess where is "from" and where is "to" )

**Comment by kizoso** [comment]
Maybe it is rare, but my design insists.
I use:

`.irs-from:before{content:'from '}.irs-to:before{content:'to '}`

But when the numbers are the same in the double type slider `.irs-single` doesn't show. 
So I see in this case only "**from** _my num_" or "**to** _my num_", and can't remove prefix.
I need the only num in this case.
Could you help me somehow?
Thanks in advance

**Comment by IonDen** [comment]
@kizoso, you can do something like this:
```
onChange: function (data) {
    if (data.from === data.to) {
        // hide prefix
    } else {
        // show prefix
    }
}
```

**Comment by kizoso** [comment]
Thank you!!! I remove my css and use this:




    $(".js-range-slider").ionRangeSlider({
        onChange: function (data) {
            if (data.from === data.to) {
                $('.irs-from span, .irs-to span').css('display','none')
            } else {
                $('.irs-from').prepend("<span>from </span>");
                $('.irs-to').prepend("<span>to </span>");
            }
        }
    });

**Comment by Gerard987789** [comment]
@kizoso and @IonDen  Thank you very much, both of you!!!!

**Comment by slidenerd** [comment]
I have a similar case where I want to show something like 'Rank 1 to Rank 1000', how do I modify it as 'Rank 1 to 1000' or just show 'Rank 1' on top of one of the handles while the other one merely shows '1000' @kizoso @IonDen  any help is appreciated

**Comment by IonDen** [comment]
@slidenerd could you create a demo on jsfiddle for this task? To understand the problem better.
Use this template: http://jsfiddle.net/IonDen/726L0aj5/
