### ISSUE TITLE
Ion range is locked in Rtl direction

### ISSUE THREAD

**Issue by shahramSo** [IonDen/ion.rangeSlider#494]
Ion range is locked in rtl direction when $app-direction changes to multi ($app-direction: multi;).
In fact ion-range position is changed to the right position but it's locked and it's not possible to move it.
I have changed some of directions like item-start and item-end but the result was same.
any idea?
Thanks

**Comment by IonDen** [comment]
Hi, this version of slider was not designed for RTL.
So, to do it, you should reverse it manually. Follow this demo: http://jsfiddle.net/IonDen/gbmszmp4/

**Comment by shahramSo** [comment]
Hi, 
Thank you for your reply. I've guessed.
anyway I use your solution thanks.
