### ISSUE TITLE
Cannot read property 'preventDefault' of undefined

### ISSUE THREAD

**Issue by configgamer** [IonDen/ion.rangeSlider#495]
Hi,

I have a problem with the rangeSlider, can you help me ? I try all i can ...

With Chrome : 
ion.rangeSlider.js:769 Uncaught TypeError: Cannot read property 'preventDefault' of undefined

With Firefox :
TypeError: e is undefined (line 769)

My version :
Ion.RangeSlider
version 2.1.6 Build: 369

URL for test : https://www.config-gamer.fr/index.php?option=com_rsform&view=rsform&formId=4
Click on Button "Commencer votre demande" . => I have two range, on the second page. 

THX for all.

**Comment by IonDen** [comment]
Hello, best guess - you have a conflict in one of your scripts. Then i opened you site, first error i saw - was in Masonry script, again related to jquery event handler object.

This could mean that one of your script has problems, and you are aslo using some strange jquery noconflict script.

Try to debug your issue. Disable all scripts, enable only jQuery. Then start enabling other scripts one by one to see, which one is causing the issue.
