### ISSUE TITLE
Is it possible to change Decimal separator to a Comma (,) ?

### ISSUE THREAD

**Issue by aras13** [IonDen/ion.rangeSlider#497]
Hello,
My self AR AS,
I'm building a calculator by using ion.rangeSlider I appreciate your work for this awesome plugin.
The calculator is ready but the client is asking : 
"   **_Thousand sign separator_** should be **. (period)** instead of **, (comma)**
**_Decimal sign separator_** should be **, (comma)** instead of **. (period)**   "

I found the option to change **_Thousand sign separator_** but there is no option for **_Decimal sign separator_**.
can you please help me in this.
Thank you!

**Comment by IonDen** [comment]
Hello, just write your own prettify function.
You need this? http://jsfiddle.net/IonDen/0jv7nt37/

**Comment by aras13** [comment]
yes, exactly :)
Thank you, soo much.
it's working. I appreciate your quick response.

kind regards,
AR AS

**Comment by IonDen** [comment]
NP, good luck!
