### ISSUE TITLE
1 handle bind to 1 input If using value range is array

### ISSUE THREAD

**Issue by muslimmuda15** [IonDen/ion.rangeSlider#498]
How set dynamical values from input field if the ionRangSlider using value array?

```
$(".price-range").ionRangeSlider({
      values: ["10","30","45","70","75","90","130","150","160"],
      type: 'double',
      onChange: fromTo
});
``` 

Because If I set "40"
```
var instance = $(".price-range").data("ionRangeSlider");
instance.update({
    from: "40"
});
```

I think this is set index's values array.

**Comment by IonDen** [comment]
Hello, if you are using values array. It will use only it, that is how predefined values should work by design.
Check this demo: http://jsfiddle.net/IonDen/xkfoyoym/

But, of course, you can always switch slider back to normal range.
Just follow this 2-nd demo: http://jsfiddle.net/IonDen/rkgugorf/

**Comment by muslimmuda15** [comment]
I use to example 2.

but, can I keep the array range after ranging?

**Comment by IonDen** [comment]
No, how do you imagine that? Slider is using or predefined array, or range.
