### ISSUE TITLE
Ability to initialize slider from html only

### ISSUE THREAD

**Issue by CzBuCHi** [IonDen/ion.rangeSlider#499]
currently to init slider i need to call this code:
`$('#slider').ionRangeSlider()`

i would love to be able to init slider only by adding attribute to `<input id="slider" ... />` element...

basically add this code at the end:
```
$(function () {
    $('[data-ion-range-slider]').each(function () {
        if (!($.data(this, "ionRangeSlider") instanceof IonRangeSlider)) {
            $.data(this, "ionRangeSlider", new IonRangeSlider(this, options, plugin_count++));
        }
    });
});
```

PS: awesome piece of work 👍

**Comment by IonDen** [comment]
Hi, i know, some of you guys like this kind of approach, but this is not a good idea. Because there are a lot of situations then slider should not be initialized at the beginning and should be manually controlled.

That is why i can't add this code, sorry :) but thanks for using!

**Comment by CzBuCHi** [comment]
not even lie this?
```
$(function () {
    $('[data-ion-range-slider]').each(function () {
        if (($.data(this, "ionRangeSlider") === "initialize_me_automatically")) {
            $.data(this, "ionRangeSlider", new IonRangeSlider(this, options, plugin_count++));
        }
    });
});
```

nevermind ... closing this...
