### ISSUE TITLE
Using min or max interval not working with moment.js dates

### ISSUE THREAD

**Issue by lukpep** [IonDen/ion.rangeSlider#508]
Dates are firmatted as unix ms timestamps:
`private rangeSliderStart = moment().subtract(1, 'years').format("x");  `

step size is also in ms:
`step=86400000`  <----- 24h in ms

and this works fine.
But setting min_interval (or max) to 10 days:
`min_interval=864000000` <--- 10 days in ms

does not work - I'm sill able to set both handlers on same date.
I'm usuin aurelia wrapper but I don't think it's responsible for this
https://github.com/lukpep/aurelia-ion-rangeslider/blob/master/src/aurelia-ion-rangeslider.ts
It just passes bindings to oryginal ion.rangeSlider

Config:
`grid=true 
                    grid_num=8 
                    force_edges=true 
                    step=86400000
                    min_interval=864000000
                    drag_interval=true
                    type='double'
                    min.bind="rangeSliderStart" 
                    max.bind="rangeSliderEnd" 
                    from.bind="fromDate"
                    to.bind="toDate"
                    prettify.bind="slinderRenderFunc">`

**Comment by IonDen** [comment]
Hello, maybe you missing something?

Check this moment.js demo: http://jsfiddle.net/IonDen/2e7fta8w/
Min interval working fine. Could you please experiment with it?

**Comment by lukpep** [comment]
Hi,

I also tried basing example with plain numbers:
`$("#range_119").ionRangeSlider({
    type: "double",
    min: 0,
    max: 100,
    from: 30,
    to: 70,
    min_interval: 20
});`

and it's the same - min interval not working. So maybe it's something in the wrapper after all?

**Comment by IonDen** [comment]
Could be, then. Check please if wrapper passes this argument correctly.

**Comment by lukpep** [comment]
wrapper passes the data correctly but here interval is zeroed:
```
if (typeof o.min_interval !== "number" || isNaN(o.min_interval) || !o.min_interval || o.min_interval < 0) {
       o.min_interval = 0;
 }
```

min and max intervalas unlike 'step' for example are not casted to numbers - and by default bindings from html came in as strings

**Comment by IonDen** [comment]
Ah, ok, good point, i will try to convert them first.
