### ISSUE TITLE
camelCase format for data

### ISSUE THREAD

**Issue by blue-eyed-devil** [IonDen/ion.rangeSlider#509]
for some reason if you assign data attribute as `data-extraClasses` slider does not pick up the value, but if you change it to `data-extra-classes` or `data-extraclasses` within ion rangeSlider script too. it works

**Comment by IonDen** [comment]
Hi, it is a standard jQuery method.
https://github.com/IonDen/ion.rangeSlider/blob/master/js/ion.rangeSlider.js#L395

Check your jQuery version.

**Comment by blue-eyed-devil** [comment]
yeah you are right I am using latest. Good you pointed me there, thanks, lol.
