### ISSUE TITLE
Create slider with 3 or more points?

### ISSUE THREAD

**Issue by aai2on** [IonDen/ion.rangeSlider#510]
I need to create a slider with a range (ideal low to high range) with customers actual value.

Is there any way to add multiple locked in place points?

**Comment by IonDen** [comment]
Hello, closest idea - marks: http://jsfiddle.net/IonDen/spez12kt/
If your idea is different, please provide some illustration what do you need.

**Comment by aai2on** [comment]
In my case, I have a range ( Example: 125,000 -> 320,000) The customer is currently spending 425,000.   The range slider would be used to show that the customer is outside the ideal range.

At least this is how I am trying to use the control.

**Comment by IonDen** [comment]
Good, that you found how to do your feature.
