### ISSUE TITLE
Using .setContent (Info Window) turns Slider back into a text box

### ISSUE THREAD

**Issue by michaeln914** [IonDen/ion.rangeSlider#511]
Hi,

I am working on a script that will show images based on where the slider is set, for instance if the slider is pointing to number 4, image 4 will be displayed. I am doing all of this inside an infoWindow. 
```javascript
    google.maps.event.addListener(marker, 'click', function (event) {
      let name = feature.getProperty('title');
      let description = feature.getProperty('view');
      let region = feature.getProperty('region');
      let imgDo = feature.getProperty('href');
      let direction = feature.getProperty('direction');
      let position = feature.getGeometry().get();    
      let content = `<div id="infowindow-container">
                <div class="infowindow-title">${name}</div>
                  <div class="infowindow-content">
                    <p>${description}</p>
                    <p><strong>Region:</strong> ${region}<br/>
                    <strong>Direction:</strong> ${direction}</p>
                    <input type="text" id="range_08" name="range_08" value=""/>
                  </div>
                  <img src="../img/hourly_jpg/${name}0.jpg" alt="Traffic Image is Unavailable, please try again later">
                </div>`;

      infoWindow.setContent(content);
      infoWindow.open(map, marker);

      $(function () {
          $range = $("#range_08");

          $range.ionRangeSlider({
                 grid: true,
                 from: 2, //set it to current time
                 values: [
                    "00:00", "01:00",
                    "02:00", "03:00",
                    "04:00", "05:00",
                    "06:00", "07:00",
                    "08:00", "09:00",
                    "10:00", "11:00",
                    "12:00", "13:00",
                    "14:00", "15:00",
                    "16:00", "17:00",
                    "18:00", "19:00",
                    "20:00", "21:00",
                    "22:00", "23:00",
                ],

        onChange: function (data) {
            content = `
                 <div id="infowindow-container">
                       <div class="infowindow-title">${name}</div>
                       <div class="infowindow-content">
                            <p>${description}</p>
                            <p><strong>Region:</strong> ${region}<br/>
                             <strong>Direction:</strong> ${direction}</p>
                             <input type="text" id="range_08" name="range_08" value=""/>
                       </div>
                       <img src="../img/hourly_jpg/${name}${data.from}.jpg" alt="Traffic Image is Unavailable, please try again later">
                 </div>`;
        }
        
      });
    //infoWindow.setContent(content);
    //infoWindow.open(map,marker);
    });
}
```

This code runs fine, as in the slider is appearing and the image I assigned is loading. However, if I want to update or change my images based on slider, I would have to use infoWindow.setContent(content) again in order to update the 'content' variable. Where I have commented out infoWindow.setContent, it is where I would usually execute it, however in doing so it causes my slider to turn back into a text box.

I suspect that after calling infoWindow.setContent(content) the second time, it deinitializes the slider. My slider/text box was also declared in the 'content' variable so I think that may also be the problem but I need a slider for every info window. 

I've got a live demo [here](http://pinesapple.com), if you go Inspect and look at the console as you are moving the slider, you'll notice that the img src is constantly changing but the images themselves aren't. I can make it change with infoWindow.setContent but that will result in the slider turning back into a text box :( .

**Comment by IonDen** [comment]
Hello, the problem is, that you are replacing all sliders html on update!
You should not do that! How do you expect it to work, if you are deleting its content every time?

Best workaround here - slider should be located outside your infowindow-container. This will protect it from being erased every time you change the image.

**Comment by michaeln914** [comment]
Hi, thank you for the comment, I took your suggestion and started thinking outside the box (pun), I tried declaring the input as a separate variable outside the `infowindow-container` and referenced it in `let content=.....${sliderInput}` but even when I use `infoWindow.setContent(content)` it still deletes it.

Anyway, I'm going with a different approach and have decided to just put them in the navigation bar where it's visibly clearer. Thanks again !
