### ISSUE TITLE
Sliding left or sliding right

### ISSUE THREAD

**Issue by sanjshah** [IonDen/ion.rangeSlider#512]
Hi,

I love this plugin, it's so simple to use.

Two questions 
1. is is it possible to know if the user is sliding from left - to - right or right - to - left?
2. Get the current value 

Thanks

**Comment by IonDen** [comment]
Hello.

1. Is easy, you can do it yourself, you will need extra variable - http://jsfiddle.net/IonDen/b2e7bv2c/
2. Check demos :)

**Comment by sanjshah** [comment]
Many thanks.
