### ISSUE TITLE
Min interval for date type slider

### ISSUE THREAD

**Issue by xx1100blackbird** [IonDen/ion.rangeSlider#513]
Hello! So, can I set min_interval for date type slider? I will explain the situation:
I have values array with dates, and I needed to set min interval, because left value and right value can be moved in one point (I don't need that), and 
from, to parameters not working too. Can you help me with that? Is it possible ? (Sorry for my English).

**Comment by IonDen** [comment]
Hello, if you are using values array, that does not matter what it is inside, dates or anything else.
You should think about this values as an array.

Example: http://jsfiddle.net/IonDen/qrns1kbg/

**Comment by xx1100blackbird** [comment]
Thank u so much!!!, but, is it possible to set default values when slider loads on page? (like from and to)

**Comment by IonDen** [comment]
Of course, use value array indexes as FROM and TO
