### ISSUE TITLE
Draggable slider, but snap to value when at that value

### ISSUE THREAD

**Issue by asolakian** [IonDen/ion.rangeSlider#514]
Looking to have a range slider where I can slide to any number between steps in increments of 1, but my steps should have the slider snap to it when it get's close to that value or is equal to the label value. Hope this makes sense.

**Comment by IonDen** [comment]
Hello, unfortunately it is technically impossible for this slider.

Because, slider is doing all calculations (including rounding by step) before drawing handles positions. That is why it always snap exactly to steps.
