### ISSUE TITLE
Static values (not moving with the slider)

### ISSUE THREAD

**Issue by Robinjoeh** [IonDen/ion.rangeSlider#516]
Hello.

Is there any simple way of having the current value (min and max) as static ones, not moving right/left with the slider? Just like the "min" and "max" values, to be positioned statically, without any movement.

However, I would like the static text to update with the current value of the slider - I just  don't want the current values selected to move along with the slider input.

Seems like the slider is automatically adding "left" and "right" properties to the values, so seems a CSS solution isnt enough.

Thoughts?

**Comment by IonDen** [comment]
Hi, @Robinjoeh, you mean like this?
http://jsfiddle.net/IonDen/r5aox84v/

**Comment by IonDen** [comment]
You can also hide current labels, using "hideMinMax" and/or "hideFromTo"

**Comment by Robinjoeh** [comment]
Scenario is this:

- Having multiple range sliders on the same page
- Content on the page is dynamic (including the range sliders)

I could hide the labels, I'm aware of that. But when using the callbacks (like onChange), I can't identify the origin input - which means I can't go back and fill my own inputs - unless I create a variable for every single rangeslider, but this is a bit time consuming as the content is dynamic and constantly changes without user refresh action.

**Comment by IonDen** [comment]
Hey, but this is easy.

In every callback you will get not only slider data, bug also links to slider original input. And you can easily identify it by unique attributes of that input (id, name or else).

**Comment by Robinjoeh** [comment]
Thanks again @IonDen , for your time.

I tried to debug the callback, but  couldn't find any link to the original input. This would actually be a perfect solution indeed, would you mind sharing how to access the original input? Like I said, I tried to debug it last night, but seems I'm unable to find the original input.

Will have a second look tonight as well, might have rushed it and missed it.

**Comment by IonDen** [comment]
If you will go to sliders main readme:
https://github.com/IonDen/ion.rangeSlider#description-of-data-passed-to-callbacks-onchange-and-etc

**Comment by Robinjoeh** [comment]
Couldn't agree with you more. I was probably way too tired.

Everything of course working as expected, sorry for this thread - and thank you for your time! Will close it. :-)
