### ISSUE TITLE
Disable Moving Slider using the From & To Labels

### ISSUE THREAD

**Issue by MattPua** [IonDen/ion.rangeSlider#517]
I have a question more than anything: I was wondering if it's possible to disable having the user move the slider using the from & to labels? 

Looking at the options, the closest thing I could think of looking at was the grid option, but I don't think that was correct.

Thanks

**Comment by IonDen** [comment]
![2017-11-08_16-56-39](https://user-images.githubusercontent.com/428365/32558803-f9de9d0e-c4a5-11e7-9170-8ab4cabf0f1d.png)
Hi, you mean this? Just, in CSS, add `pointer-events: none` to that class.

**Comment by MattPua** [comment]
@IonDen  perfect, thanks!
