### ISSUE TITLE
Step and min interval for moment.js (date type slider)

### ISSUE THREAD

**Issue by xx1100blackbird** [IonDen/ion.rangeSlider#518]
So. How can I set min interval for 1 month? Is it possible to set step = 1 month? Thanks

**Comment by IonDen** [comment]
Hello. You can't set up step like that. Because month is a relative value. You can't just transform it in to milliseconds.

So, best way to fix this for you - use months numbers. Demo:
http://jsfiddle.net/IonDen/L9wyozwy/
