### ISSUE TITLE
Getting real value from array in OnChange function 

### ISSUE THREAD

**Issue by xx1100blackbird** [IonDen/ion.rangeSlider#519]
Hello! I have values array of dates, so, how can I get this values (from, to) in OnChange function? Not the numbers, I need **real** values. 

Is it possible to run PHP script while OnChange function ? I need to parse from, to, parameters to php script.  Can u help me ? (If u know something). Thank you!

**Comment by IonDen** [comment]
Hey, of course you can. Check the readme:
https://github.com/IonDen/ion.rangeSlider#description-of-data-passed-to-callbacks-onchange-and-etc

You will see, that it has `from` and `from_value` along with `to` and `to_value`.

If you need to send something to backend - i would suggest to use `onFinish` callback and send `ajax` request only then `onFinish` fired.

`onChange` callback will fire too often, don't use it for ajax requests.
