### ISSUE TITLE
Range Slider with Text Input

### ISSUE THREAD

**Issue by jptheripper** [IonDen/ion.rangeSlider#520]
I have some rangesliders with alot of values (0.0 to 30.9 by 0.1 step).  Users are finding it hard to get the exact value they want on a small screen .

Is it possible to have a text box next to or below the slider that shows the value, that could also be typed in to manually update the value (and would obey the min max of course)

Thanks

**Comment by IonDen** [comment]
Hello, @jptheripper, of course it is possible. Check this demo:
http://jsfiddle.net/IonDen/mvrfg2vc/

**Comment by jptheripper** [comment]
Thank you so much! I had to switch it to change instead of change keyup, but it works great for the range sliders.

Is it also possible with sliders that use a value array? i tried it but the textbox shows the index value instead of the array value.  Thanks again!

**Comment by IonDen** [comment]
Hi, again. Check this:
https://github.com/IonDen/ion.rangeSlider#description-of-data-passed-to-callbacks-onchange-and-etc . If you working with values array, you can operate or array index, or value itself.

**Comment by alexanderadam** [comment]
The first mentioned demo (http://jsfiddle.net/IonDen/mvrfg2vc/) doesn't seem to work anymore. Is there any other working example anywhere?
