### ISSUE TITLE
i need to rtl support

### ISSUE THREAD

**Issue by asadghazanfary** [IonDen/ion.rangeSlider#521]
hello @IonDen 
When will the new edition be released? Because I really need rtl support.

thank you so much

**Comment by IonDen** [comment]
Hello, 3.0 is still under development. It could take some time.

For now, please use this workaround to inverse slider: http://jsfiddle.net/IonDen/gbmszmp4/

**Comment by asadghazanfary** [comment]
how can i use "double" type slider?

**Comment by IonDen** [comment]
The same: http://jsfiddle.net/axbq5xsx/

**Comment by asadghazanfary** [comment]
excuse me @IonDen 
if min and max value was great than zero Does this work properly?

**Comment by IonDen** [comment]
Hey, @asadghazanfary, it was a quick demo :)

Check this: http://jsfiddle.net/IonDen/t7a51bjv/

**Comment by asadghazanfary** [comment]
thank you , thank you, thank you .....
