### ISSUE TITLE
Manually call onfinish method?

### ISSUE THREAD

**Issue by jptheripper** [IonDen/ion.rangeSlider#522]
Is there a way to forceable call the onfinish method? I am updating a slider value with 
```
$range.data("ionRangeSlider").update({ 
                                from: val
                            });
```
However i need to launch the onFinish method, not the onUpdate method.  The reason is onFinish sends the final value over bluetooth.  If i add the bluetooth send to onUpdate, then sliding the slider is constantly sending values.

So i need to "send" (from onFinish) after both completion of slide event, and onUpdate from text box.  
Thank you

**Comment by IonDen** [comment]
@jptheripper, Hello, there is onUpdate method. It is used to duplicate onFinish method in that situtaion.
