### ISSUE TITLE
Commas to Value Results

### ISSUE THREAD

**Issue by rnixon223** [IonDen/ion.rangeSlider#524]
The script is great! I was easily able to add data-prettify-separator and have commas for the slider itself. I am currently showing the value x 2.5% underneath the slider. However, it is not showing the value with commas. For example, the slider is on $100,000 and the value show $2500 (which is the correct formula) but doesn't show as $2,500 which I would like it to.

Is there a way to easily accomplish this?
Thanks!

**Comment by IonDen** [comment]
Hi. I'm not really sure, what do you mean. Could you create a demo?

Meanwhile you can check this demo, with an interesting example, how to work with `prettify`: http://jsfiddle.net/IonDen/vrqqL2Lw/

There is a build-in prettify function, to transform raw numbers in to a pretty ones. But if you need to do that manually, you will need to use this regular expression:

```javascript
var num = 100000;
var numStr = num.toString();
var numWithCommas = numStr.replace(/(\d{1,3}(?=(?:\d\d\d)+(?!\d)))/g, "$1\,");
console.log(numWithCommas); // 100,000
```

**Comment by petefazio** [comment]
So you can prettify the result? how can you do that in this example?
http://jsfiddle.net/petefazio/0f2orys6/

**Comment by IonDen** [comment]
Hello, sorry for a long answer. Was unavailable.

Like this?
http://jsfiddle.net/u87cynzx/
