### ISSUE TITLE
unable to submit negative value 

### ISSUE THREAD

**Issue by meyer59** [IonDen/ion.rangeSlider#525]
Hi,
First i would like to thanks you for the great work!
I'm running into an issue with negative value. 
I want to run a range slider from -30 to 30. When i am submiting the form, the negative values are set to 0.
Positive value work fine. 
Ps: i'm binding the plugin without any options `$('.ion_slider').ionRangeSlider()`
Any idea ?
Thank you

**Comment by IonDen** [comment]
Hello, seems that your code have some problems.

Check this demo. It is working fine:
http://jsfiddle.net/jt8o00u9/

**Comment by meyer59** [comment]
With the jsFiddle provided:
 I'm getting the negative value when i'm `console.log(data.from)` in the onChange callback. 
But when the form is submitted `$form.on("submit", function (e) {
	e.preventDefault();
    
	var data = $form.serialize();
    console.log(data);
})`
i'm getting `0` 
Any ideas ? Thank you

**Comment by meyer59** [comment]
I find the root cause. My input was a `type='range'` instead to `type='text'`
Thanks for your help
