### ISSUE TITLE
Problem using slider with range of decimal values less than zero

### ISSUE THREAD

**Issue by constantval** [IonDen/ion.rangeSlider#526]
Hi,

Just want to say this range slider is exactly the thing I needed for my current project where accessibility (using the keyboard to control the slider, and clicking on the slider bar to move the handles) is key. However I have hit a bit of a problem with the data I am trying to filter.

I have an array of values from -0.20 to 0.86 and the sliders do not seem to be working with these small numbers. When I check the to and from values on my change event, they seem to be forced whole number values Eg: 1.20 to 1.86 and my values are not being filtered.

Example:
http://jsfiddle.net/ojyaj7zL/1/

**Comment by IonDen** [comment]
Hello, @constantval. This is happen because slider is trying to process the values you are using as numbers.

To fix this, try this workaround: http://jsfiddle.net/IonDen/vrqqL2Lw/

**Comment by constantval** [comment]
Thanks for coming back to me so quickly. 
I've added in the work around. And while this fixes the values appearing on the slider itself, the values I am receiving as an output from the slider are still incorrect.

http://jsfiddle.net/xjddgkyj/3/

**Comment by IonDen** [comment]
Hi again. Check this: http://jsfiddle.net/80rmL5fy/

**Comment by constantval** [comment]
Thanks for the example!
I'm not able to use the in-build onChange callback method on the sliders as I am dynamically building 20+ with data I'm populating from a json file. But with a bit of playing around with what you had provided, I did get it working with an on.change call by class name. Sadly, I can't replicate it properly in jsfiddle to give a working example. But it does just take a bit more toying around with what you linked above.
Thank you very much for all your help.
