### ISSUE TITLE
Having custom text shown on certain values for the From and To Labels

### ISSUE THREAD

**Issue by MattPua** [IonDen/ion.rangeSlider#527]
Hey I was wondering if it was possible to customize the text that shows up on the From and To labels depending on the values of the from, and to (together at the same time) and perhaps other variables as well.

Example: For pricing, if To and From values were equal to the min and Max, I'd like a straight text value (Any Price), but if only the To value > min value, but From value = Max value, then have it say "Greater than {To Value}"

I'd also like this to be customizable so that the text values can be different depending on what my conditions were. Whether it be pricing, size, etc. I thought about passing in a customizable prettify function from whatever component needs it, but I found I ran into errors trying to write the conditions for the text changes since I didn't have access to the To and From values.

Thanks

**Comment by IonDen** [comment]
Hello, the basic idea is: http://jsfiddle.net/nLohs4h2/

You can write as many conditions inside this prettify function as you want. But prettify function should be only 1.

**Comment by MattPua** [comment]
Thanks for the note. Yeah, using the prettify I could use a very simple generic function, but I was hoping I could find something slightly more robust that could be variable depending on who's using it. I was able to figure out what I needed though using plain javascript to modify the irs-singles, to, and from depending on the use case.
