### ISSUE TITLE
Option to show/display the from_min/from_max values on the slider

### ISSUE THREAD

**Issue by Viral246** [IonDen/ion.rangeSlider#528]
![image](https://user-images.githubusercontent.com/34655021/34113426-b68019ac-e435-11e7-9c10-c61044e75735.png)

Here in the image my from_min/from_max is 10/50, is there any way to show in the slider

Code
`$(".rangeslider").ionRangeSlider({
			    grid: false,
			    min: 0,
			    max: 100,
			    from: 20,
			    from_min: 10,
			    from_max: 50,
			    from_shadow: true,
			    hide_min_max: false,
				hide_from_to: false,
			    postfix: "%"
			});`

**Comment by Viral246** [comment]
Expectation is something like

![image](https://user-images.githubusercontent.com/34655021/34113616-4bc85696-e436-11e7-9dd0-2d329a0902c7.png)

**Comment by IonDen** [comment]
1. Change skin to fit your needs
2. Use Marks-technique to add 25 and 40 marks: http://jsfiddle.net/IonDen/spez12kt/

**Comment by Viral246** [comment]
Thanks for the above, that is what we required.
![image](https://user-images.githubusercontent.com/34655021/34151422-2a2b8698-e4d1-11e7-9210-6e1d0f3744aa.png)

is there a way to remove the leading blue highlight on the slider before 25%, as the option of the selection is only between 25-75

Thanks again

**Comment by IonDen** [comment]
@Viral246, of course. Just remove its style from Skin CSS :)
