### ISSUE TITLE
Ruller positioning issue

### ISSUE THREAD

**Issue by soulessvadi** [IonDen/ion.rangeSlider#529]
Cheers IonDen. There is some bug with grid in case whet it starts not from zero.
The code:
               `$("#months").ionRangeSlider({
		    grid: true,
    		    grid_num: 10,
		    min: 1,
		    max: 10,
		    from: 1,
		    postfix: " months"
		});`
![screen](https://user-images.githubusercontent.com/28763320/34214308-c59d92cc-e5aa-11e7-9f03-214333a1ee62.png)

**Comment by IonDen** [comment]
Hi, @soulessvadi, this is not a bug. Just weird set of parameters and grid is not smart enough :) To fix that, use the same grid items as values. In you case, `grid_num` should be 9.
http://jsfiddle.net/7skw918c/

Or use `grid_snap: true` param:
http://jsfiddle.net/5984t4wd/

**Comment by soulessvadi** [comment]
Yes, i have noticed that. Thanks a lot for nice plugin!

**Comment by IonDen** [comment]
@soulessvadi, don't forget to star it :)
