### ISSUE TITLE
custom seekbar design in ionic 3

### ISSUE THREAD

**Issue by ghostpatel** [IonDen/ion.rangeSlider#530]
![screenshot from 2017-12-26 14-34-48](https://user-images.githubusercontent.com/17120122/34354416-3656d1a4-ea56-11e7-962a-b4d3a82cdbd0.png)

I am not getting any idea that ionic 3 is able to design this UI or not  I searched a lot but still no idea.
please help......
thanks in advance

**Comment by IonDen** [comment]
Hello, i have no idea what are you talking about :)

**Comment by ghostpatel** [comment]
I solved this problem with pure CSS
thanks for response...

**Comment by IonDen** [comment]
@ghostpatel, sorry :)
