### ISSUE TITLE
Wordpress bugfix prettify fnc larger numbers

### ISSUE THREAD

**Issue by mikedesignco** [IonDen/ion.rangeSlider#531]
Hey,
first of all thanks for the amazing plugin!

For some reason in wordpress the larger numbers with prettify didn't work. In larger number after 999 was getting something like 1jQuery 000. After 100k it didn't work at all. 

In case someone is looking for a fix (this will get rid of the problem):

```
 prettify: function (num) {
           var ns = num.toString();
           return ns.replace(/./g, function(c, i, a) {
              return i && c !== "." && ((a.length - i) % 3 === 0) ? ',' + c : c;
           });
}
```

**Comment by IonDen** [comment]
Hi, i would be really curious to see the demo. Could you provide me the link to the page with the bug?

**Comment by mikedesignco** [comment]
Here it is,
range is 10000 to 1.5M. Sry link dont want to send public. 
```
 	  min: 10000,
  	  max: 1500000,
  	  from: 150000
```

![ionbug](https://user-images.githubusercontent.com/5349991/34537258-bdb08722-f07c-11e7-9183-b2b77bf63be4.jpg)

**Comment by IonDen** [comment]
@mikedesignco, yeah, i got what happened. I mean live demo :)
