### ISSUE TITLE
Slider value formatting issue

### ISSUE THREAD

**Issue by zopyx** [IonDen/ion.rangeSlider#534]
some slider values are badly  formatted (V 2.2.0)

![slider](https://user-images.githubusercontent.com/594239/35613975-cda0145c-066d-11e8-891d-f11caedbebe3.png)

```
            $('.range-slider').ionRangeSlider({
            
                type: "single",
                min: 0,
                max: 10000,
                step: 1000,
                grid: true,
                grid_snap: true
            });

```

**Comment by IonDen** [comment]
Hi, i cant reproduce. Could you create a demo here?
http://jsfiddle.net/IonDen/qv6yrjrv/

**Comment by zopyx** [comment]
I encountered the error within our integration with Plone CMS inside an internal application. It is not reproducible outside afaik...I solved the issue with a customer formatter.

**Comment by IonDen** [comment]
Ok, but if you manage to create a working demo with the bug, please notify me.
