### ISSUE TITLE
Dynamically add multiple Ion.RangeSlider in Angular4

### ISSUE THREAD

**Issue by cshah123** [IonDen/ion.rangeSlider#538]
I want to add multiple Ion.RangeSlider on click of a button in angular4.
Find the following link: https://www.kapwing.com/editor/subtitles
The exact same thing I am trying to achieve. When the user clicks on "Add another Subtitle" button, a new instance of Ion.RangeSlider must be created. 
Also, the slider must be linked to each other. 
For example: The 'min' for  'n+1st' slider should be 'max' of 'nth' slider.
How do I achieve this in angular4.

**Comment by IonDen** [comment]
Hi, i think the same way as in any other case. Check this demos:

Create/destroy slider:
http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html#range_52

Connected sliders:
http://jsfiddle.net/IonDen/4k3d4y3s/
http://jsfiddle.net/IonDen/ctkouh69/
http://jsfiddle.net/IonDen/n2sxswv2/
