### ISSUE TITLE
Request: a different separator for after the decimal mark

### ISSUE THREAD

**Issue by wch** [IonDen/ion.rangeSlider#541]
In my code, I use `prettify_separator: ","` so that large numbers display with commas. However, if there are small numbers with more than 3 digits after the decimal point , they also display with commas, which is undesirable.
http://jsfiddle.net/vkrd9cr6/1/

![image](https://user-images.githubusercontent.com/86978/36750532-62836d70-1bc3-11e8-8f51-b81a6387027b.png)

(In this particular example, there's also some weird rounding errors, but that's a different issue.)

It is possible for now to work around this by using a prettify function or by setting `prettify_separator: ""` when the values are small, but this adds extra complexity to the application code.

**Comment by IonDen** [comment]
Try space as a separator. But yes, if you want more complex prettify, you should write you own function. Like this: http://jsfiddle.net/IonDen/vrqqL2Lw/

**Comment by wch** [comment]
For reference, this is what I ended up using as a prettify function:

```js
function(num) {
  var n = num.toString();
  var parts = n.split(".");
  // Add separator before decimal. When executed, `this` will refer to
  // the `IonRangeSlider.options` object.
  parts[0] = parts[0].replace(/(\d{1,3}(?=(?:\d\d\d)+(?!\d)))/g, "$1" + this.prettify_separator);
  if (parts.length === 1)
    return parts[0];
  else if (parts.length === 2)
    return parts[0] + "." + parts[1];
};
```
