### ISSUE TITLE
Flat Skin Bug

### ISSUE THREAD

**Issue by xcrap** [IonDen/ion.rangeSlider#544]
http://jsfiddle.net/ehar7kmm/

When using the flat skin, if data-mi, data-from and  data-to are the same i cannot drag the handler...
I don't have this problem with other skins but the Flat it's the most gorgeous skin. Help ?

**Comment by IonDen** [comment]
Hi, yes, it happen sometimes. It is very hard sometimes to detect which handle should be on top.
But you can always unlock this by clicking on slider.

I will think what i can do with it.

**Comment by xcrap** [comment]
Yes but the clients don't know that :) 

But in a situation of the double data-type where data-min="X" and data-from="X" and data-to="X" the only slider that's able to be moved in that situation it's the right slider, and the same when it's data-max="Y" and data-to="Y" and data-from="Y". 

Actually in my tests the opposite situation never happens, it's always possible to pull the left slider when everything it's at max, it looked to be only this particular situation :) I'm using this for a rent-a-car- filters forms so I've changed the skin to HTML5 and made look like the Flat skin, that was my workaround :)

**Comment by IonDen** [comment]
Hi, if you set `from` it will be fixed: http://jsfiddle.net/ehar7kmm/2/

**Comment by xcrap** [comment]
Nuips, I've tried that also. Try without a refresh, it's doing the same thing if you have data-from. Actually when I found this problem I thought it was because of this but I've tested this before also :) It's not a big deal but this it's the best range slider ever since years and I think it would be important to have all this minor stuff arranged :)

**Comment by IonDen** [comment]
Yep, it could be tricky) Thanks for finding this.
