### ISSUE TITLE
Move jQuery from dependencies to peerDependencies

### ISSUE THREAD

**Issue by c-emil** [IonDen/ion.rangeSlider#546]
Hello, would you consider moving `jQuery` to `peerDependencies` instead of `dependencies`? I've had issues in the past with your project having `jQuery` in `dependencies`. In particular `yarn install` installs not only my version of `jQuery` that I have specified in my `dependencies`, but also your version specified in the `ion.rangeSlider` project `dependencies`. In result, two `jQuery` were included in the project and I couldn't figure out why my slider doesn't work with my version of `jQuery`. It just couldn't find the plugin. Then I realised that there are two `jQuery` versions packed by webpack. 

Here's a nice article why plugins should include such `dependencies` inside `peerDependencies`: https://yarnpkg.com/blog/2018/04/18/dependencies-done-right/

**Comment by IonDen** [comment]
Hi, thanks for info, i will check it soon.

**Comment by InhouseMedia** [comment]
A nice work-around is bypass the AMD module switch by using:
require("!imports-loader?define=>false,exports=>false!ion-rangeslider");

**Comment by juniorgarcia** [comment]
Doesn't work here. Same error.

**Comment by c-emil** [comment]
Any progress on this one?

**Comment by IonDen** [comment]
@c-emil done in 2.3.1

**Comment by c-emil** [comment]
Thanks a lot @IonDen!
