### ISSUE TITLE
Is it possible to place current selected value to the slider handle instead tooltip

### ISSUE THREAD

**Issue by spoul2000** [IonDen/ion.rangeSlider#547]
Is it possible to place tooltip data with current selected value to the slider handle. 

As I can see with current html structure using css positioning it is too complicated - tooltip parent layer with all other stuff is under slider handle layer, so repositioning will hide other nesessery elements.

Expected slider appearence is in attached image.

![slider](https://user-images.githubusercontent.com/39099391/39774664-2ccc661e-5304-11e8-99a3-6288a179c1e0.png)

**Comment by IonDen** [comment]
Hi, use this demo as a reference:
http://jsfiddle.net/IonDen/c8n8oynd/

**Comment by spoul2000** [comment]
thanx a lot, I'll try it

**Comment by Lydianne2000** [comment]
Hi, I need to do exactly this as well. The jsfiddle isn't working anymore, do you still remember the solution?
