### ISSUE TITLE
ion range slider custom grid value using prettify and moment.js

### ISSUE THREAD

**Issue by priraut88** [IonDen/ion.rangeSlider#549]
I am using ion range slider in my application. Where input data is in "year-week" format. e.g("2017-02","2017-34" -- here 02 & 34 is no of weeks). I need to show actual month from that year-week string on the grid. To convert this year-week into month I am using moment.js. In prettify function I am trying to show months. But In this case, as prettify doesn't accept string with "-" character I am converting it before passing to prettify function. after doing this prettify function accepts the input and converts it to months. Now here I need single value for months as there are multiple weeks from the same month. e.g for "Jan" there are 5 records like "2017-01","2017-02","2017-03","2017-04","2017-05". now i need, Ion slider grid should show "Jan" month only once instead of showing "Jan" 5 times on grid for 2017. How should I avoid these duplicate entries from grid.

Please let me know where I am going wrong.

Sharing the fiddle :
http://jsfiddle.net/09u17wg7/90/

@IonDen  your help would be appreciable.

**Comment by IonDen** [comment]
Hi, check this demo:
http://jsfiddle.net/IonDen/bxuoutr7/

best idea from the top of my head.

**Comment by priraut88** [comment]
@IonDen Thanks for providing solution. but with this solution I am not getting exact output which I want. In prettify, it is actually checking immediate old values. but the case where values are not in the specific order, it fails. Also, with the current solution we are getting ticks with blank labels, instead we need consistent labels on grid. e.g. If there will be 5 weeks in Jan and in Feb if 2 weeks are there then in that case we will see only Jan and Feb, and ticks will be on weekly basis.  Unfortunately, I am not able to achieve this behavior with the current solution. 

Can you please provide any other solution for the same?

**Comment by ajsjunior** [comment]
Any expected date for release this feature?
