### ISSUE TITLE
Selected slider value is not persistent across page navigation in IE or Edge

### ISSUE THREAD

**Issue by piejanssens** [IonDen/ion.rangeSlider#550]
Reproduce:
1. Open http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html with IE or Edge
2. Change a slider value and remember what you changed
3. Click any link on the page to go to visit another page
4. Click the browser's back button
--> Initial value shown

**Comment by IonDen** [comment]
Hello, @piejanssens, i don't understand. Why it should be persistent across website navigation? Why IE? It would not be persistent in other browsers too.

If you want it to be persistent, you need to do it yourself.

**Comment by piejanssens** [comment]
Because it's common behavior that a browser keeps <input> values when returning to a page.
With the referenced demo page it is persistent using FF. I was expecting it to work with Chrome too as it is working my in implementation, but on the demo page it appears not to be working either.

**Comment by IonDen** [comment]
Maybe browsers do not save value of hidden input elements? It is my best guess.
Anyway, it should be a small and easy script to save all data to local storage and preserve it.

**Comment by piejanssens** [comment]
Indeed, browsers seem to have different behavior. I've implemented a solution using sessionStorage.
Thanks
