### ISSUE TITLE
Different Step Values in Angular 2+

### ISSUE THREAD

**Issue by NagavijayColan** [IonDen/ion.rangeSlider#551]
Hi Team, I am trying to create range slider with different steps like 1 5 20 30 60 100 in angular 2+

How can I achieve it? 

Kindly please help me out 

Thanks in advance

**Comment by IonDen** [comment]
Hi, could you show some illustration of what you want?

**Comment by CoinWave** [comment]
http://jsfiddle.net/3B3tt/240/

Please Check the above link and help me 

Thank you

**Comment by NagavijayColan** [comment]
http://jsfiddle.net/3B3tt/240/

Hi , Please check the above link and help me 
I want steps like 1,30,50,60,70,90,100
Thank you

**Comment by IonDen** [comment]
Look, easy: http://jsfiddle.net/zLkm5axk/

**Comment by NagavijayColan** [comment]
Sorry, I want it in angular not in JQuery

<ion-range-slider #sliderElement type="single" [min]="0" max="120" values="" from="0" from_min="0" from_max="120" from_shadow="false"
                    to="0" hasGrid="false" to_min="0" step="40" to_max="120" to_shadow="false" grid="true" grid_num="6" postfix=" Seconds Interval"
                    decorate_both="false" (onUpdate)="myOnUpdate.parseInt($event)" (onChange)="myOnChange.parseInt($event)" (onFinish)="myOnFinish.parseInt($event)">
                    
                </ion-range-slider>

Please help me out of this

**Comment by IonDen** [comment]
Add this array of values to this attribute: `values=""`

**Comment by NagavijayColan** [comment]
I have added as you  said, It showing the following error

![image](https://user-images.githubusercontent.com/38784047/40534359-62210cf8-6023-11e8-8201-9ddee49d4a87.png)

**Comment by IonDen** [comment]
Sorry, it should be `data-values="1,10,100"`
http://jsfiddle.net/zkkdpchn/

**Comment by NagavijayColan** [comment]
Then Could you please tell that with whom i can check for solution from one of your team

**Comment by IonDen** [comment]
I believe this guys is the author of Angular wrapper: https://github.com/PhilippStein/ng2-ion-range-slider

P.S. I don't have any team here :)

**Comment by NagavijayColan** [comment]
Okay Thank you so much for your valuable time :)
