### ISSUE TITLE
changeing step value

### ISSUE THREAD

**Issue by poslwa450** [IonDen/ion.rangeSlider#552]
I need to Starting at 25, step the value by 25, until 2500 is reached. From there, step by 1000 to max 9500. But slider needs to be move first %80 area for 25 steps.

It is something like that.

<---------------------------------%80----------------------------------------><------------%20--------->
25----------------------------------------------------------------------------2500--3500--...--8500--9500

**Comment by IonDen** [comment]
Hi, this is not possible from the box. Closest workaround i could find:
1. http://jsfiddle.net/IonDen/ca6ykae6/ but prettify function should be used to convert real numbers too.
2. http://jsfiddle.net/IonDen/st9eotpy/ - same with prettify function.

**Comment by poslwa450** [comment]
I found the solution to adding ranges
  values: [25, 50, 100, 125, 150, 175, 200, ................................ 2500, 3500,4500,5500,6500,7500,8500,9500]
