### ISSUE TITLE
How to add one custom field to ion range slider

### ISSUE THREAD

**Issue by nishatke** [IonDen/ion.rangeSlider#553]
Hi team,
I want to display a number in range slider example:

<div class="range-slider color-3">
    <input type="text" class="js-range-slider" value="" />
</div>

var $range = $(".js-range-slider");

$range.ionRangeSlider({
	disable:true,
    type: "single",
    min: 0,
    max: 100,
    from: 50
	
});
for the above example i want to show one more field called remaining that is **max - from**  please help me with this .. how can i achieve this

**Comment by nishatke** [comment]
Thanks a lot for you help @IonDen , but i want display remaining number in the place of max ..and it should be single value ..please help me for this

**Comment by IonDen** [comment]
For that you will need a custom block to put on top of max, like this:
http://jsfiddle.net/q8s86w47/

**Comment by nishatke** [comment]
Thanks a lot @IonDen for your quick response and the solution ...:) its help me thank you once again ..
