### ISSUE TITLE
Possibility to chose direction of dragging when 'from' = 'to'

### ISSUE THREAD

**Issue by an4ousss** [IonDen/ion.rangeSlider#554]
Hi , Denis! Is'it possible to chose direction of dragging  when handles are staying on the same point. Right now, if i choose handle 'from' the last and drag it to the same point to handle 'to' , after that i can only move back handle 'from', but can't move handle 'to'. The same would be action with handle 'from',if it was dragged last. But i want on mousedown if i  drag left the handle 'from' will change and if drag right handle 'to' will change  from the general point. How could i implement that? Thank You!

Also i tried some opportunities to do this: 

 $("#range").ionRangeSlider({
      type: "double",
      min: 1,
      max: 14,
      step: 1,
      grid: true,
      grid_snap: true,
      values: rangeValues,
      p_values: available_quarters,
      onFinish: function () {
        $.ajax(investment_overview_path, {
          data: { range: $('#range').val()},
          type: 'GET',
          remote: true
        })
      },
      onChange: function (data) {

        var circleFrom = $('.irs-slider.from');
        var circleTo = $('.irs-slider.to');
        if (data.from === data.to) {
          $(function() {
            var tile = document.getElementById("slider"),
                tmp = 0;
            tile.onmousedown = function() {
              this.onmousemove = function(e) {
                if(tmp > e.pageX) {
                  console.log(1);
                  $(circleFrom).css('z-index','2');
                  $(circleTo).css('z-index','1');
                }
                if(tmp < e.pageX) {
                  console.log(2);
                   $('.irs-slider.from').css('z-index','1');
                  $('.irs-slider.to.type_last').css('z-index','2');
                }
                tmp = e.pageX;
              }
            window.onmouseup = function() {
                tile.onmousemove = null;
                this.onmouseup = null;
            }
            }
          });

        }
        else {
        // show prefix
        }
      }
    });
  });

**Comment by IonDen** [comment]
Hi, it is not so easy, and will require a lot of core code changes.
You can't do it from outside, sorry.
