### ISSUE TITLE
from_pretty not working on Ion.RangeSlider 2.2.0

### ISSUE THREAD

**Issue by htmlasia** [IonDen/ion.rangeSlider#556]
var $range = $("#proxy-slider"),
    $pick = $(".number");

var track = function (data) {
  $pick.html(data.from_pretty);
};

$range.ionRangeSlider({
  min: 20,
  max: 50000,
  from: 25000,
  prettify_separator: ", ",
  from_pretty: "25 k",
  hide_min_max: true,
  onStart: track,
  onChange: track,
  onFinish: track,
  onUpdate: track
});

------------------
from_pretty: "25 k", not working. Pls help

**Comment by IonDen** [comment]
Hi, sorry for a long answer, was unavailable.

`from_pretty` is available only in result object. You can't set this.
