### ISSUE TITLE
Please add new design to website

### ISSUE THREAD

**Issue by grimalschi** [IonDen/ion.rangeSlider#558]
There is two beautiful modern designs - rounded and squared.

I just want them to be published on a website, please!

**Comment by IonDen** [comment]
Hi, i'm very sorry. Was on a long vacation. Soon i will add them.

**Comment by IonDen** [comment]
It is hard to be parent and find time for all of it :) But soon.

**Comment by IonDen** [comment]
Done)) sorry for late reply http://ionden.com/a/plugins/ion.rangeSlider/skins.html#a_round
