### ISSUE TITLE
Labels that differ from values

### ISSUE THREAD

**Issue by rxng** [IonDen/ion.rangeSlider#560]
Hi,

Been trying to get the min and max labels to be text, whilst the values are numbers (for form submission). For example, min label might be A and value is 1, and max label might be Z with value of 24. However, cannot find a way to do this. Is this supported at all?

R

**Comment by IonDen** [comment]
Hello, sorry for a long answer, i was unavailable.

If you will use custom values, you can do that easily. Like this:
http://jsfiddle.net/detqs2o9/
