### ISSUE TITLE
Added Woo-Multi-Currency plugin (for Rupees and Dollar) the slider doesnot change according to the selected currency

### ISSUE THREAD

**Issue by unicus-design** [IonDen/ion.rangeSlider#562]
Hi, 
I have Added Woo-Multi-Currency plugin (for Rupees and Dollar) in my ecommerce website, when i chnage from Rupees to Dollar the ion.rangeSlider doesnot change according to the selected currency. Also it seems to multiple the amount in some cases.. 

Thanks

**Comment by IonDen** [comment]
Hi, i have no idea about plugin you are talking about.

Probably, this plugin does not restart Ion.RangeSlider properly on currency change. You should get in touch with its authors.

**Comment by adityamaxlogical** [comment]
how to replace Rupees Symbol in jQuery only range slider plugin

**Comment by IonDen** [comment]
@adityamaxlogical, look at the create and destroy demos:
http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html#range_52
