### ISSUE TITLE
update the min of the slider 1 according to the array of the slider 2

### ISSUE THREAD

**Issue by Madaj** [IonDen/ion.rangeSlider#564]
For example:

slider 1 - min $ 10 / slider 2 - 10

slider 1 - min $ 20 / slider 2 - 20

slider 1 - min $ 30 / slider 2 - 40

slider 1 - min $ 50 / slider 2 - 60

http://jsfiddle.net/0xLs46an/13/

**Comment by IonDen** [comment]
Hi, look at this demo about connecting sliders:
http://jsfiddle.net/IonDen/4k3d4y3s/
