### ISSUE TITLE
Dropdowns with params

### ISSUE THREAD

**Issue by lmewmewl** [IonDen/ion.rangeSlider#570]
Hello, i have some trouble with task.  Here is a layout, i cant understand how to add dropdowns with params, DOM always updating, even if i try to use on('click') event with update disable, range slider still working.
![tohardreangeslider](https://user-images.githubusercontent.com/15806037/43839405-a97a2240-9b26-11e8-93f5-94780229357f.jpg)

**Comment by IonDen** [comment]
Hey, 2 ways.

1. You will need to modify sliders template (in core) and manually add this dropdowns to labels
2. You should disable native labels and create custom labels, separately from slider. onChange callback will return all necessary data to move custom label around.

**Comment by lmewmewl** [comment]
2nd way is faster i think :)
later i try to share my code

**Comment by lmewmewl** [comment]
@IonDen here is my example http://jsfiddle.net/oztcdkh4/5/

But now i have a question about range, how i can change range beteween mm and meters with different labels?

**Comment by lmewmewl** [comment]
@IonDen and another question :)
http://jsfiddle.net/oztcdkh4/19/ here is my code, in updated range second diapason value not last, how to fix that?
