### ISSUE TITLE
When focus using tab key on slider handle moving to starting position of slider

### ISSUE THREAD

**Issue by kesavamoorthi1990** [IonDen/ion.rangeSlider#573]
I'm using 2.2.0 version. I have created 7 slider, already binding some value for all slider. when i'm focus using tab key for slider, after handle moving to starting position. Please help me on this issue #

**Comment by IonDen** [comment]
Hi, could you create a demo with your setup on this playground:
http://jsfiddle.net/ras1h5f8/

**Comment by MyNameTony1000** [comment]
Is there any progress on the focus issue?

**Comment by MyNameTony1000** [comment]
If you leave the slider untouched, the value resets to the minimum when you tab, and if you move it first, nothing changes when you focus. When you focus, the onChange event is triggered. Here's the standard input code:
```
<input class="js-range-slider" type="text" data-min="3500000" data-max="25000000" data-step="100000" value="4000000" tabindex="-1">
```
