### ISSUE TITLE
ion.rangeSlider on Ionic 3

### ISSUE THREAD

**Issue by abdellahaski** [IonDen/ion.rangeSlider#574]
Hi,
How can I make it work for Ionic 3 ?

I installed jquery + ion.rangeSlider via npm : 
```
npm install jquery --save
npm install @types/jquery
npm install ion-rangeslider
```
and I've imported them in my ts using: 
```
import * as $ from 'jquery';
import * as ionRangeSlidere from  'ion-rangeslider';
```

 jquery is working but when I try 
$("#example_id").ionRangeSlider();
it says that ionRangeSlider does not exist on type jQuery<HTMLElement>
and I also get the it's not a function error on the console

**Comment by IonDen** [comment]
Hi, i never worked with ionic framework before. I would suggest you to start searching for solution on their forum: https://forum.ionicframework.com/t/use-jquery-plugin-in-ionic/102537/5 or on StackOverflow

**Comment by abdellahaski** [comment]
Thanks I've let it go and used something else
