### ISSUE TITLE
Slider handle does not follow mouse properly on html {zoom: 150%;}

### ISSUE THREAD

**Issue by Zsarl** [IonDen/ion.rangeSlider#575]
First of all I must say amazing job with the slider!

I have an issue where the slider handle does not follow mouse when using html {zoom: 150%;} in the css.
This is the case when using Chrome or Vivaldi. It works in Firefox, but Firefox seems to ignore the whole zoom css.

Also I was wondering if it is possible to fix the from and to handles but still allow dragging?
Right now the slider will be stuck with: drag_interval: true, from_fixed: true, to_fixed:true

**Comment by IonDen** [comment]
Hi,

1. nether tested it, sorry.
2. No, it is not possible.
