### ISSUE TITLE
Sending empty values on submit

### ISSUE THREAD

**Issue by merkdev** [IonDen/ion.rangeSlider#576]
Hi, 
How can i pass empty values to slider on default?
I mean, send empty if visitor did nothing.

My slider looks like this (i'm using html attrs.);

`<form><input type="text" value="" class="range-slider" name="x" data-min="0" data-max="100" data-type="double" data-postfix=" x" data-step="1"  data-prettify-separator="."></form>`

It sends 0;100 when form submitted.

Thanks!

**Comment by IonDen** [comment]
Hi, you can't do this from the box. But you can run simple script to override this:
1. Move slider outside the form
2. Connect slider to a separate input field, like this: http://jsfiddle.net/IonDen/r5aox84v/
3. Put this input fields in to your form
4. Remove onStart callback from code above and this input fields will have no value on start
