### ISSUE TITLE
No default value or update on Custom Values

### ISSUE THREAD

**Issue by spacecdr** [IonDen/ion.rangeSlider#578]
Example:

`values: [0, "16Gb", "32Gb", "64Gb", "120Gb", "128Gb", "240Gb", "256Gb", "480Gb", "500Gb", "512Gb", "640Gb", "1Tb", "2Tb", "4Tb"]`

No way to update the instance with a "right" value (like "128Gb"), neither to set it on startup by from/to
Is there any way to solve my problem?

**Comment by IonDen** [comment]
Hi, you should set FROM and TO as indexes of this values array you have. If you want to set FROM to be "32gb" it should be = 2.
