### ISSUE TITLE
\plugins\ion-rangeslider\ion.rangeSlider.css.shim.ngstyle.ts Unexpected token (9:19)     You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by kolte** [IonDen/ion.rangeSlider#581]
ERROR in ./$$_gendir/wwwroot/assets/plugins/ion-rangeslider/ion.rangeSlider.css.shim.ngstyle.ts
    Module parse failed:

**Comment by IonDen** [comment]
Hi, i think where is an Angular wrapper for Ion.RangeSlider. Check this:
https://github.com/PhilippStein/ng2-ion-range-slider
