### ISSUE TITLE
Slider from label jumps from start.

### ISSUE THREAD

**Issue by nzahasan** [IonDen/ion.rangeSlider#582]
I am trying to implement a play button which updates slider after a interval. But when updating slider value the from label starts moving from start, where it should be moving from previous location. Is there any easy fix for this.

here is an example.
![ion_slider](https://user-images.githubusercontent.com/9565364/49096716-5b438280-f295-11e8-95dc-2b62f31b3300.gif)

**Comment by IonDen** [comment]
Hey, could you give me a real demo, it is hard to understand problem from video only.

**Comment by IonDen** [comment]
You can use this fiddle to repeat your problem. I could not:
https://jsfiddle.net/IonDen/8ctewdna/
