### ISSUE TITLE
Publish latest 1.9.x release to npm.

### ISSUE THREAD

**Issue by elycruz** [IonDen/ion.rangeSlider#583]
Hi I'm working on a revamping a project that is using your plugin at version 1.9.2.  I was trying to install it from your npm though not published on npm so tried via 'user/repo' syntax and noticed version 1.9.3 doesn't have a package.json file.  If you could publish that release  (latest 1.9.x) release to npm (`$ npm publish --tag ...` (where `...` is version tag) that would be great!

Thank you,
Fellow dev

**Comment by IonDen** [comment]
Hi, sorry, I can't do it. 1.x version is not supported for long time already (almost 4 years).

You should consider switching to a 2.x branch. It is not that hard as you think:

**Migrating from 1.x to 2.x** 

- All params (except functions) are lowercase now: param_name, not paramName
- Same param names was changed: hasGrid → grid, onLoad → onStart
- Callbacks data object format was changed. Example: fromNumber → from
- Slider now writes it's result to value attribute and also to data-from and data-to attributes

**Comment by elycruz** [comment]
I hear ya jehjeh (makes sense 👍 ).  The migration tidbit helps also 👍 
Thanks @IonDen !
