### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by Nazar32** [IonDen/ion.rangeSlider#585]
I guess after this commit https://github.com/IonDen/ion.rangeSlider/commit/72d85651e8300ad66835e24fa780897ad47b32e6
my plugin can not be initialized, however I import jquery before plugin initialization
```
$ = jQuery = require('jquery');
require('ion-rangeslider');
```
before everything works normal, but now I get error
![image](https://user-images.githubusercontent.com/16920168/49867804-3d892800-fe14-11e8-8cd4-8b1ea3c48e6a.png)

**Comment by IonDen** [comment]
I will test that

**Comment by Sparkier** [comment]
Is there something going on about this?

**Comment by damienalexandre** [comment]
Yes it's broken:

```
import jQuery from 'jquery';
import ionRangeSlider from 'ion-rangeslider';
```

Will result in:

```
ion.rangeSlider.js:14 Uncaught ReferenceError: jQuery is not defined
    at ion.rangeSlider.js:14
    at Object.265.jquery (ion.rangeSlider.js:23)
```

**Comment by Nazar32** [comment]
Add pull request, that will solve the problem, but still no reaction
https://github.com/IonDen/ion.rangeSlider/pull/586

**Comment by IonDen** [comment]
Hi, guys. Sorry, had a huge delay in checking this issue. Will react very soon.

**Comment by DivyanshuLoktra** [comment]
Guys any progress ?

**Comment by IonDen** [comment]
Fix pushed.
