### ISSUE TITLE
How to make custom handle text??

### ISSUE THREAD

**Issue by irfanahmad7272** [IonDen/ion.rangeSlider#590]
Hello, 
I want to make ion.rangeSlider, to have a custom handle text rather than it shows 'From' value. How can i do that?? I need to change it when it initializes or updated. 
Thanks

**Comment by mh19971967** [comment]
Hi IonDen,

congratulations on your very nice framework.

One question, which somehow, picks up on irfanahmad7272:

Is it possible to switch of the handle completly?

Thanks and kind regards

**Comment by IonDen** [comment]
@mh19971967, You mean the label? Yes, add this to params: `hide_from_to: true`
