### ISSUE TITLE
make a range move when the maximum interval is reached by dragging one of the ends of the interval

### ISSUE THREAD

**Issue by afrikazil** [IonDen/ion.rangeSlider#591]
Why not make a range move when the maximum interval is reached by dragging one of the ends of the interval? like on this video
[1.mp4.zip](https://github.com/IonDen/ion.rangeSlider/files/2729294/1.mp4.zip)

**Comment by IonDen** [comment]
@afrikazil, could you please upload video to youtube/vimeo/something?

**Comment by afrikazil** [comment]
Of course)) 
https://youtu.be/Vxoq8F09q40
