### ISSUE TITLE
Modify Value in Handle using an Input

### ISSUE THREAD

**Issue by loohney** [IonDen/ion.rangeSlider#592]
Hey, first of all thanks for creating the Ion.RangeSlider, keep up the work.

I've been curious if it would be possible to add a new feature to not only modify the value using the slider-handles but also by typing in the desired value into the box above the slider-handles.

![img](https://i.imgur.com/VVLmlHN.png)

When working with a wide range of values, sliding to a specific point becomes impossible. Therefore, being able to edit the value above the slider-handles would be a great addition to fix this.

Thank you,
Loohney

**Comment by IonDen** [comment]
Hi,
1. You already can connect handle to an input field, like this: https://jsfiddle.net/IonDen/khngpw3m/
2. Then you can use sliders service data from callbacks to create your own label, like this: https://jsfiddle.net/IonDen/7r80g2we/

**Comment by loohney** [comment]
Perfect, thank you. 👍
