### ISSUE TITLE
Values from two slider via ajax

### ISSUE THREAD

**Issue by gba1904** [IonDen/ion.rangeSlider#593]
While using only one slider, submitting the values via ajax works as expected.
But I need to collect the values from two slider for the my mysql-query.
How to manage to read the values from both sliders?

Thank you.
Any help is welcome :)

Example:
$(".S1").ionRangeSlider({
        type: "double",
        grid: true,
        step: 25000,
        min: 50000,
        max: 1000000,
        from: 0,
        to: 1000000,
        prefix: "€",
        prettify_separator: ".",
        max_postfix: "+",
        skin: "big",

        onFinish: function (data) {
       
        $.ajax({
            type: 'POST',
            url: 'phpProcess.php', 
            data: {
                min: data.from, 
                max: data.to
              /* here goes Data from S2 */
            }
        });
    }
    
    });
  
$(".S2").ionRangeSlider({
        type: "double",
        grid: true,
        step: 10,
        min: 50.00,
        max: 200.00,
        from: 0,
        to: 200,
        postfix: " qm",
        prettify_separator: ".",
        max_postfix: "+",
        skin: "big",

        onFinish: function (data) {
       
        $.ajax({
            type: 'POST',
            url: 'phpProcess.php', 
            data: {
                fl1: data.from, 
                fl2: data.to
               /* here goes Data from S1 */
            }
        });
    }
    
    });

**Comment by IonDen** [comment]
1. Put both sliders inside FORM
2. Inside `onFinish` callback call external function
3. This function (call it `send`) will serialize form data and then send it to phpProcess

**Comment by gba1904** [comment]
Sorry for my late reply IonDen,
your hints pointed me to the right solution and I've learned a lot about Ajax and JavaScript in the meantime ;-)
