### ISSUE TITLE
how to auto slider ，from left to right  and Cycle all the time ，when i press button 

### ISSUE THREAD

**Issue by kt7456** [IonDen/ion.rangeSlider#595]
how to auto slider ，from left to right  and Cycle all the time ，when i press button？ thank you！

**Comment by IonDen** [comment]
Hi, i did not understand your idea. Could you give some illustration or video?

**Comment by kt7456** [comment]
i mean can auto play ，from left to right .

**Comment by kt7456** [comment]
when i click the play button 
![m45c 9raz1xuqmm0 l k868](https://user-images.githubusercontent.com/35618730/53338108-d1f82680-393d-11e9-880e-604ff3fc3073.png)
