### ISSUE TITLE
irs-hidden-input disappeared

### ISSUE THREAD

**Issue by AlfaDelta** [IonDen/ion.rangeSlider#597]
Just to let you know a simple but effective solution for the hidden input text field but never hide.
I have a basic page in a Laravel project with Bootstrap 3.x and could not get rid of the input text field. Then I realized that the class="irs-hidden-input" was removed while visiting that page.

After a lot of debugging I end up by this solution:
$("#price").addClass("irs-hidden-input");

**Comment by IonDen** [comment]
Hi, it seams like a bug of your environment.
