### ISSUE TITLE
Change the sorting method?

### ISSUE THREAD

**Issue by kuwze** [IonDen/ion.rangeSlider#599]
I am looking for a way to change this library so that I can add an option to sort something numerically or lexicographically. My issue is that I have items that have text in them, and I want to add an optional function that just grabs the first number that appears in a string and uses that to sort them. I am a bit of an idiot at the moment and cannot seem to find any function that does the sorting/ordering. Could someone please point me towards it?

**Comment by IonDen** [comment]
Hi, this type of features should be handled by external functions.

**Comment by kuwze** [comment]
Than you!
