### ISSUE TITLE
Long Update Times

### ISSUE THREAD

**Issue by toddsandercock** [IonDen/ion.rangeSlider#600]
Update command takes ~25ms to complete when grid enabled. Is there any way to prevent recalculating the grid each 'update()' call? Appears that the jquery calls are very time expensive when recalculating the views.

**Comment by IonDen** [comment]
Hi, this is one is already in plans.
But probably will be released only with 3.0 version:
https://github.com/IonDen/ion.rangeSlider/issues/328
