### ISSUE TITLE
Cant drag the slider on mobile divices

### ISSUE THREAD

**Issue by Samuel-Bie** [IonDen/ion.rangeSlider#601]
I know that this migth be old but, i am facing problems of dragging the slider on mobile divices i am using V 2.2.0. @IonDen

**Comment by IonDen** [comment]
Hi, it was tested on mobile devices. Working fine, since 1.x version. Maybe where is some problems with your environment?

Give me more details, did you tested it on other devices?

**Comment by djalmajr** [comment]
I'm facing the same problem... Here is an example:

https://djalmajr.gitlab.io/cashme/simulador/passos.html

<img src="https://user-images.githubusercontent.com/1858147/60759751-5ea7a500-a000-11e9-877d-1006612328e4.gif" width="300" />
