### ISSUE TITLE
4 sliders?

### ISSUE THREAD

**Issue by AAverin** [IonDen/ion.rangeSlider#602]
Does the library support more then 2 sliders?

**Comment by yunusga** [comment]
range^2?

**Comment by AAverin** [comment]
@yunusga what do you mean?
I need to display this:
![screen shot 2019-01-19 at 20 06 40](https://user-images.githubusercontent.com/1481332/51431190-c4a49980-1c25-11e9-8724-911fcb80e013.png)

**Comment by IonDen** [comment]
Hi, sorry, no.
Under development in 3.x, but this is not ready yet.
