### ISSUE TITLE
Configuration for sliding from max to min value

### ISSUE THREAD

**Issue by BaterdeneZ** [IonDen/ion.rangeSlider#603]
Is there any configuration to create a slider like this?
![40088 yjlgi 092bc660-1641-49b5-b205-6b1ac09441eb](https://user-images.githubusercontent.com/29364370/51663944-2cc2f900-1ff3-11e9-98d5-bb09a87c67fc.png)

**Comment by IonDen** [comment]
Hi, @BaterdeneZ, you can create your own skin.

**Comment by BaterdeneZ** [comment]
I'm sorry for misunderstanding you, @IonDen. I didn't mean the style of the slider. What I'm trying to do is swap the position of the minimum and the maximum value.

**Comment by BaterdeneZ** [comment]
Sorry for the confusing explanation, @IonDen. I didn't mean the style of the slider. What I'm trying to do is swap the position of the minimum and the maximum value.

**Comment by IonDen** [comment]
Reverse it: https://jsfiddle.net/IonDen/65rq31a7/
