### ISSUE TITLE
Opposite function to "onFinish"?

### ISSUE THREAD

**Issue by Kcko** [IonDen/ion.rangeSlider#604]
Hi, 
is there some opposite function to onFinish?
onStart is when slider is ready and initialized - cool.
onChange when some value is updated - cool.

But Im missing when Im start to pull range button  - and this event should run only once (same behavior as onFinish event).

Thx for explanation.

**Comment by IonDen** [comment]
Hi, this method is redundant. And can be emulated very easily:
Demo: https://jsfiddle.net/IonDen/dcvup69r/

**Comment by Kcko** [comment]
Ops, thx for demo, makes a sense.
