### ISSUE TITLE
i need move only left side and do not move right side and then  have space between  is 5 

### ISSUE THREAD

**Issue by Thammarat062** [IonDen/ion.rangeSlider#611]
![sss](https://user-images.githubusercontent.com/23059656/53472386-07b22200-3a9a-11e9-9802-aff418a0b7c8.PNG)

when i move left side to 25 year right side is 30 year ,26 right side is 31,but do not move right side mov only left side.Do you know? plsss help me.

**Comment by IonDen** [comment]
Sorry, missed your question.
