### ISSUE TITLE
aurelia integration JQuery check is wrong (amd)

### ISSUE THREAD

**Issue by jrgcubano** [IonDen/ion.rangeSlider#612]
@IonDen
Trying to integrate the control in aurelia, I guess there is a bug checking JQuery existence in AMD format, so it fails. 

```
!jQuery -> needs to be typeof 'jQuery' === 'undefined' in strict mode?
```

I will post the answer from aurelia core team directly with the detailed explanation that they give me.

![image](https://user-images.githubusercontent.com/3245617/53556719-5a441a80-3b3c-11e9-88fc-986e1b9d2a10.png)

Let me know if ok to do this change... So I can open a PR!

**Comment by jrgcubano** [comment]
> Trying to integrate the control in aurelia, I guess there is a bug checking JQuery existence in AMD format, so it fails.
> 
> ```
> !jQuery -> needs to be typeof 'jQuery' === 'undefined' in strict mode?
> ```
> I will post the answer from aurelia core team directly with the detailed explanation that they give me.
> 
> ![image](https://user-images.githubusercontent.com/3245617/53556719-5a441a80-3b3c-11e9-88fc-986e1b9d2a10.png)
> 
> Let me know if ok to do this change... So I can open a PR!

**Comment by IonDen** [comment]
Fixed
