### ISSUE TITLE
Add two sliders with data bound input boxes

### ISSUE THREAD

**Issue by ec1solutions** [IonDen/ion.rangeSlider#614]
Help please!
I've tried to add two sliders and input boxes to a page using this as my source: https://jsfiddle.net/1qtzvn2m/1/

I've now managed to tie myself in total knots, the closest I can get is that both sliders update the second input box, nothing going into the first. Any pointers on how to achieve this will be totally appreciated. Thanks.

**Comment by IonDen** [comment]
Sorry, missed your question.
