### ISSUE TITLE
Is there any way to make click on grid to change the value?

### ISSUE THREAD

**Issue by iryska** [IonDen/ion.rangeSlider#615]
Hi, 
Client asked me about ading click to grid to change range value. As there any way to do it?
![Income and Investments - 5i Research - Google Chrome 2019-04-04 15 04 26](https://user-images.githubusercontent.com/402004/55554270-0b654400-56eb-11e9-9dba-9f36089dc881.png)

**Comment by newsonaut** [comment]
This has come up for me as well. Some people expect to be able to do this.

**Comment by IonDen** [comment]
Sorry, missed your question.
