### ISSUE TITLE
make interval non-clickable

### ISSUE THREAD

**Issue by Tarilonte** [IonDen/ion.rangeSlider#623]
Hello!
There is a way to make the interval non-clickable and allow the user to manipulate the handlers only?

Thanks in advance!

**Comment by IonDen** [comment]
1. You can make it draggable instead
2. You can add `pointer-events: none` to it in CSS skin file.

**Comment by Tarilonte** [comment]
> 1. You can make it draggable instead
> 2. You can add `pointer-events: none` to it in CSS skin file.

I've added the rule to .irs-line and .irs-bar and Problem solved. Thanks!
