### ISSUE TITLE
Display restrict range without restrict the hadlers

### ISSUE THREAD

**Issue by sabi1981** [IonDen/ion.rangeSlider#626]
I would like to display a range below the slider (just like when you restrict) but I don't want to restrict the handlers, is there any option for that ?

**Comment by IonDen** [comment]
You can use "custom marks" technique to display any type of data/graphics on top of the slider:
https://jsfiddle.net/IonDen/tdvxs3zL/

**Comment by sabi1981** [comment]
Thank you, that is a great help!
