### ISSUE TITLE
Is it possible Time values (like AM and PM)?

### ISSUE THREAD

**Issue by sinjuangajan** [IonDen/ion.rangeSlider#627]

**Comment by IonDen** [comment]
Hi, yes, why not.

1. Check this demo
http://ionden.com/a/plugins/ion.rangeSlider/demo_advanced.html#a_date

2. Check how you can print dates in desired format:
https://stackoverflow.com/questions/8888491/how-do-you-display-javascript-datetime-in-12-hour-am-pm-format
