### ISSUE TITLE
Has functionality "Clear"  ?

### ISSUE THREAD

**Issue by PetroGromovo** [IonDen/ion.rangeSlider#630]
Hello
Using Ion.RangeSlider(version 2.2.0) I wonder if it has functionality "Clear" to clear current selection with type = "double" property?

Please provide a link to such example...

Thanks!

**Comment by IonDen** [comment]
Hi, there is `reset` method. Which can restore slider to original position.
https://github.com/IonDen/ion.rangeSlider#public-methods

If this is not what you are looking for - please specify your question or give examples.
