### ISSUE TITLE
prevent and return false on change event

### ISSUE THREAD

**Issue by ozkandanaci** [IonDen/ion.rangeSlider#632]
Hi,

How to stop and return false onchanging slider value?
The scenario is so;

There is two or more sliders and ask for how many $ you spend on holiday 
1. slider is food 
2. slider is hotel
3. slider is arrival

sliders total will be 600$ , 
for example food = 250$, hotel=250$ , when changing arrival slide, can slide until 100$, can not move up to 100$ until food and hotel values change under 250$

**Comment by IonDen** [comment]
Sorry, missed your question.
