### ISSUE TITLE
Material skin

### ISSUE THREAD

**Issue by djibe** [IonDen/ion.rangeSlider#636]
Hi everyone,
I created a material skin that is still in a Pull Request.

You can see the demo here : https://jsfiddle.net/djibe89/ofdv53k1/

Thanks for your feedback.
NB. I'll delete this Issue when my PR is merged.

**Comment by IonDen** [comment]
Hi, looking very good! I will try to find some time next few weeks to merge it!

**Comment by djibe** [comment]
Cool @IonDen . Glad you like it.
See you soon.

**Comment by IonDen** [comment]
Hi @djibe, i checked your PR and I can't accept it:
https://github.com/IonDen/ion.rangeSlider/pull/631#issuecomment-515434283
