### ISSUE TITLE
Can initialize slider and update with vanila javascript?

### ISSUE THREAD

**Issue by lazyphpdev** [IonDen/ion.rangeSlider#637]
Hello, Is it possible to initialize the script through vanila javascript instead of jquery?
I'm about
`$(elem).ionRangeSlider();`
And
```
slider = $(elem).data("ionRangeSlider");
slider.update({
    from: sliderData[0],
    to: sliderData[1]
});
```

**Comment by IonDen** [comment]
Hi, slider is made as jQuery-plugin. So, it can be initialized only this way.

3.x version will get rid or jquery, but it is only in development right now with no clear release date.

**Comment by lazyphpdev** [comment]
> Hi, slider is made as jQuery-plugin. So, it can be initialized only this way.
> 
> 3.x version will get rid or jquery, but it is only in development right now with no clear release date.

Okay, thank you!
