### ISSUE TITLE
Value not showing anything

### ISSUE THREAD

**Issue by samb172** [IonDen/ion.rangeSlider#638]
I've installed it as the guide showed and it works fine, but no value appears in the `input` field.

`<input type="text" class="js-range-slider" name="my_range" value="" />`

`jQuery(".js-range-slider").ionRangeSlider();`

Slide across to 70 for example and it comes out as;

`<input type="text" class="js-range-slider irs-hidden-input" name="my_range" value="" tabindex="-1" readonly="">`

**Comment by IonDen** [comment]
Hi, did you try to grab the value using javascript? It could happen that browser will not update value dynamically in source code, but accessing it will work fine.

Try also to submit the form with slider, you will see that value is presented in the data.

**Comment by Richacinas** [comment]
Hello there.

I'm having the same issue. My input value always shows the same, and sending my form the value is the same as well.

It never changes when the user moves the slider. Here is some of my code:


`<input type="range" name="valor-contenido" data-min="1000" data-max="1000000" data-step="100" data-from="2000" value="2000" class="wpcf7-form-control wpcf7-range wpcf7-validates-as-required wpcf7-validates-as-number full-width irs-hidden-input" aria-required="true" aria-invalid="false" tabindex="-1" readonly="">`

And the slider initialization:

`$('input[name=valor-contenido]').ionRangeSlider({
        skin: "round",
        onChange: function (data) {
          console.log(data.input[0].value); //THIS IS ALWAYS --> 100
          console.dir(data);
        }
      });`

**Comment by IonDen** [comment]
@Richacinas you are doing something wrong. Please organize web demo in jsfiddle. You can use this link as boilerplate: https://jsfiddle.net/IonDen/uqs7njp9/
