### ISSUE TITLE
Is it possible to set range intervals with min\max?

### ISSUE THREAD

**Issue by sinneren** [IonDen/ion.rangeSlider#641]
I mean ranges like in [noUiSlider](https://refreshless.com/nouislider/examples/#section-non-linear) to make non linear slider. I need to do logarythmic (or like it) slider with values from 100.000 to 100.000.000 and in 50% it must be 5.000.000.

**Comment by IonDen** [comment]
Hi, yes. Start from this demo:
https://jsfiddle.net/IonDen/5f2730ds/

**Comment by sinneren** [comment]
`prettify: function(num) {
    		var current = num;
    		var middle = Math.floor(this.max / 2 / this.step) * this.step;

				if (num > middle) {
        	var minv = Math.log(this.min);
          var maxv = Math.log(this.max);
          
        	var scale = (maxv - minv) / 100;
          var pos = (Math.log(num) - this.min) / scale;
          
          current = Math.exp(pos * scale + this.min);
          current = Math.floor(current / this.step) * this.step + this.step;
          
        	if (current > this.max) {
          	return this.max;
          } else {
          	return current;
          }
        } else {
        	return current;
        }
    }`

**Comment by IonDen** [comment]
@sinneren, create a separate `transform` function. Because you will also need this to transform actual value. `prettify` is doing only visual change.
Or, you can write prettified value in to external `input`.

**Comment by Rombecchi** [comment]
Hi, although I understand how the mechanism works, I don't think it's as intuitive as the one on noUiSlider.
I think the best solution is to create a range option just like the one on noUiSlider.

`range: {
        // Starting at 500, step the value by 500,
        // until 4000 is reached. From there, step by 1000.
        'min': [0],
        '10%': [500, 500],
        '50%': [4000, 1000],
        'max': [10000]
    }`
