### ISSUE TITLE
Strange behavior under display block/none

### ISSUE THREAD

**Issue by JamesJGoodwin** [IonDen/ion.rangeSlider#644]
Hello. I'm having issue with strange visual behavior of my sliders under accordion I written. It seems that slider is redrawing itself everytime it become visible/invisible. Is there any way to disable this?

Example with `display: block/none`:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17240507/61998630-6d432280-b0bb-11e9-8bda-6670d9af63cf.gif)

**Comment by setiawanutama** [comment]
I'm experiencing the same issue. Upon showing the slider from invisible state (e.g.: display: none;), it initially sets the value to the min and then sets to the from value. I suppose the slider is only rendered when it is visible.

**Comment by IonDen** [comment]
Hey guys. It is impossible to render slider under `display:none`
So, normal workaround is to create slider instance on 1-st accordion open event.
