### ISSUE TITLE
colour change

### ISSUE THREAD

**Issue by couplescoachingonline** [IonDen/ion.rangeSlider#645]
Hi. Is it possible to change the colour of the slider? I really need it to fit in my theme. Thank you

**Comment by IonDen** [comment]
Hi, just modify any skin file to match your colors. Or create your own skin.

**Comment by MartH78** [comment]
is there a css builder? I managed it by editing the ion.rangeSlider.min.css

**Comment by IonDen** [comment]
Any LESS to CSS
