### ISSUE TITLE
New Skin - Mapping Marker with Marker Placeholders

### ISSUE THREAD

**Issue by nearkingdom** [IonDen/ion.rangeSlider#646]
Hi @IonDen I am attempting to create a new skin that looks like the following:

![Screen Shot 2019-08-08 at 14 56 06](https://user-images.githubusercontent.com/7198242/62709191-caf53a00-b9ec-11e9-993f-5c26139fcb6c.png)

1. I am mapping grey "placeholders" along the line to where the blue marker lands on 5 points. How would you advise getting the same % of the blue handle markers for the grey placeholders - they seem to be updated on the window changing?

2. How would you recommend the grey placeholders change color when the handle is positioned further along the line?

**My code so far with visual rendering**

![Screen Shot 2019-08-08 at 15 01 36](https://user-images.githubusercontent.com/7198242/62709530-79997a80-b9ed-11e9-9689-6571658ab390.png)

```
var $range = $(".js-range-slider");
var min = 0;
var max = 4;
var marks = [0, 1, 2, 3, 4];

$range.ionRangeSlider({
    skin: "round",
    grid: false,
    min: min,
    max: max,
    step: 1,
    from: 3,
    onStart: function (data) {
    	addMarks(data.slider);
    }
});

function convertToPercent (num) {

    var percent = (num - min) / (max - min) * 100;    

	return percent;
}

function addMarks ($slider) {
	var html = '';
    var left = 0;
    var i;
    
    for (i = 0; i < marks.length; i++) {
    	left = convertToPercent(marks[i]);
    	html += '<span class="mark" style="left: ' + left + '%">' + marks[i] + '</span>';
    }
    
    $slider.append(html);
}
```

**Comment by nearkingdom** [comment]
Just an update on this for anyone who might be interested.

I have updated my grey 'placeholder' positioning so it matches the blue marker by subtracting the percentage and applying it in a transform. See code below...

All I need to figure out now is how to turn the placeholders blue along the line. Any suggestions appreciated. 

```
function addMarks ($slider) {
	var html = '';
    var left = 0;
    var i;
    
    for (i = 0; i < marks.length; i++) {
    	left = convertToPercent(marks[i]);
    	html += '<span class="mark" style="left: ' + left + '%; -webkit-transform: translate(-' + left + '%, 0); -moz-transform: translate(-' + left + '%, 0); -ms-transform: translate(-' + left + '%, 0); -o-transform: translate(-' + left + '%, 0); -transform: translate(-' + left + '%, 0);"></span>';
    }
    
    $slider.append(html);
}
```

**Comment by nearkingdom** [comment]
So near yet so far... how do I fetch the width of the class iris-bar? If I can get that then I can change the colour of the placeholders using "if less than or equal to" statement. 

function addMarks ($slider) {
    var html = '';
    var left = 0;
    // yet need to define the width of iris-bar here
    var line = ;
    var i;    
    for (i = 0; i < marks.length; i++) {
    	left = convertToPercent(marks[i]);
        
        if (left <= line) {
            color = '#005190';
        } else {
            color = '#CCDCE9';
        }
    	html += '<span class="mark" style="background-color: '+ color +'; left: ' + left + '%; -webkit-transform: translate(-' + left + '%, 0); -moz-transform: translate(-' + left + '%, 0); -ms-transform: translate(-' + left + '%, 0); -o-transform: translate(-' + left + '%, 0); -transform: translate(-' + left + '%, 0);"></span>';
    }
    
    $slider.append(html);
}

**Comment by IonDen** [comment]
Hi!

The main idea of all slider blocks positioning - is % with negative margin.

So, if you want to match actual positioning, you should place elements like this:

```css
.item {
    left: 10%;
    margin-left: -10px;
    width: 20px;
}
```

**Comment by nearkingdom** [comment]
@IonDen Thanks for your help... we came up with a solution. You can see it working here: https://tinyurl.com/yxvmwm7j

One question I have - you will notice when using that the handle areas that clicking on the edges of the circles doesn't activate them. Is there a way of adding a border that makes the hole handle active?

**Comment by nearkingdom** [comment]
@IonDen I worked out that I could use box-shadow to do what I needed. 
However, it would be good to widen the clickable area on the empty markers. I'm not sure I can manipulate that using css - it may be a JS solution.

See the image with highlighted red areas that can't be clicked.

<img width="813" alt="Screen Shot 2019-09-25 at 10 47 24" src="https://user-images.githubusercontent.com/7198242/65590373-9cbec000-df82-11e9-88f5-7ca17f30219f.png">

**Comment by IonDen** [comment]
Hi, you add `:befor/:after` element to the line to expand its clickable area

**Comment by nearkingdom** [comment]
Ah ah - perfect. Thanks.
