### ISSUE TITLE
Update function triggering OnChange event

### ISSUE THREAD

**Issue by kanachrisi** [IonDen/ion.rangeSlider#647]
Hello,

Whenever i update the range slider from value , the onChange event is triggered, is this a normal behaviour or there is something that i am doing wrong ?
Here is how i do update 

`const seekSlider = window.parent.$('#seekSlider').data("ionRangeSlider");
 seekSlider.update({
                            from_min: next_time_index,
   });

 window.parent.$('#seekSlider').on("change", function () {

         console.log('onChange event triggered');
  });`

Thanks for the help

**Comment by IonDen** [comment]
Hi, interesting, i never tested it with updating `from_min` value. Updating with just `from` will not trigger `onChange` and will trigger only `onUpdate`.

This demo: http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html
