### ISSUE TITLE
IonRangeSlider throwing error ionRangeSlider() is not a function

### ISSUE THREAD

**Issue by Utkarsh9799** [IonDen/ion.rangeSlider#652]
I am trying to use ionRangeSlider() in my React app, but I am unable to use it because I'm getting an error that ionRangeSlider() isn't a function. 
I used CDNs before and it didn't seem to be working so I installed jQuery and ion-rangeslider modules and removed jQuery CDN to avoid clash, and worked out everything but it still is throwing the error `TypeError: $range.ionRangeSlider is not a function`

I have put my ionRangeSlider code in componentDidMount() function. How can I fix this?

**Comment by IonDen** [comment]
Try this guide: https://reactjs.org/docs/integrating-with-other-libraries.html
