### ISSUE TITLE
ionRangeSlider with dual knobs value increases in the same step

### ISSUE THREAD

**Issue by VuCuong1112** [IonDen/ion.rangeSlider#653]
![image](https://user-images.githubusercontent.com/32138188/64419232-9dbcaa00-d0c6-11e9-9b81-538e4fb36936.png)

I want the value from and to change step by step equally.
Example, when dragging and changing the value of From increase by 1 step then value of To auto increase with value of From

**Comment by VuCuong1112** [comment]
Example from = -500 when dragging and changing value of from =-250, then value of To auto increase = 525,  when value of from change inscrease 1 step then value of to increase accordingly,  same for the other case.
Please help me

**Comment by IonDen** [comment]
Maybe you need this?
https://jsfiddle.net/IonDen/gq8re42u/

`drag_interval` feature. If you drag interval itself it will move both handles at the same time.

**Comment by VuCuong1112** [comment]
Thank @IonDen 
I want to drag knob left, it move both knob left and right with equal step

**Comment by IonDen** [comment]
Sorry, there is no such an option. But good idea, will implement this in 3.x

**Comment by VuCuong1112** [comment]
Thanks I will look forward to this in the upcoming release
