### ISSUE TITLE
Help Needed with two sliders

### ISSUE THREAD

**Issue by sunil-k-sohal** [IonDen/ion.rangeSlider#654]
I have this requirement where i need to show two sliders and sum of these two sliders must equal to 100.
And both these two sliders should be interlinked with each other i.e. if I slider first slider to 40 then another slider should automatically set to 60.

**Comment by IonDen** [comment]
@sunil-k-sohal , @MahaTz please check this demo, which explains how to connect sliders.
https://jsfiddle.net/IonDen/f1t6qpx0/
