### ISSUE TITLE
When using custom data-values, the value attribute on the input tag is ignore

### ISSUE THREAD

**Issue by salcode** [IonDen/ion.rangeSlider#657]
Thanks for this great package. I did notice one unexpected behavior I wanted to share with you.

## Expected

When initializing ionRangeSlider without any parameters on an input tag like the following, I would expect the initial value of the slider would be `B`.

```
<input type="text" class="js-range-slider" value="B" data-values="A,B,C,D" />
```

## Actual Behavior

The initial value of the slider is the first value (`A` in this case), not the value of the `value` attribute.

## JSFiddle Showing the Behavior

https://jsfiddle.net/qpuwnr74/2/

**Comment by IonDen** [comment]
Hi, in specs i have set priority to data-value
