### ISSUE TITLE
RTL support?

### ISSUE THREAD

**Issue by exit-mp391** [IonDen/ion.rangeSlider#664]
Does the ion.rangeSlider have RTL support? Thanks in advance!

**Comment by IonDen** [comment]
Hi, here is the workaround: https://jsfiddle.net/IonDen/65rq31a7/

**Comment by exit-mp391** [comment]
Thanks!

**Comment by Hujairi** [comment]
Hi, I noticed that with the previous example it actually flip the range values but the bar is still on the left side, if it is rtl it needs to be from the right
