### ISSUE TITLE
Prettify Separator not working when using data attribute

### ISSUE THREAD

**Issue by thargy** [IonDen/ion.rangeSlider#665]
Using 2.3.0

```html
<input type="text" class="js-range-slider" name="salary_range" value="" 
         data-prettify-enabled: true,
         data-prettify-separator: ","
         data-prefix="£"/>
```

Incorrectly, produces labels such as "£20 000" (missing ',' separator).

Whereas:
```js
$(".js-range-slider").ionRangeSlider(
{
  prettify_separator: ',',
  prettify_separator: ',',
  prefix: '£'
});
```

Correctly produces labels such as "£20,000".

**Comment by IonDen** [comment]
Everything is working fine, demo: https://jsfiddle.net/69uzjwax/

In your case, you make a syntax mistake in the code, `data-prettify-enabled: true,` has COMMA after. This is not allowed in HTML tags.

**Comment by thargy** [comment]
+1 for me being a muppet, sorry for wasting your time!
