### ISSUE TITLE
How to trigger onChange manually

### ISSUE THREAD

**Issue by TheEssenceSeeker** [IonDen/ion.rangeSlider#668]
I need to trigger onChange programmatically. How can I do it with jQuery or planJS?
Thank you in advance!

**Comment by IonDen** [comment]
Hi, if you mean trigger onChange on slider, you can do it with using `update` method. Check this demos: http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html

**Comment by TheEssenceSeeker** [comment]
> Hi, if you mean trigger onChange on slider, you can do it with using `update` method. Check this demos: http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html
Thank you for such a fast reply! 
I want to manually trigger onChange method after I use .update() to change "from" field. Is there any good way to do this?

**Comment by IonDen** [comment]
Yes:
`$("#payment-slider").trigger("change");`

**Comment by TheEssenceSeeker** [comment]
> Yes:
> `$("#payment-slider").trigger("change");`

I've already tried this but it doesn't work :(

**Comment by IonDen** [comment]
It is working even without trigger:
https://jsfiddle.net/6mn4hubj/

**Comment by TheEssenceSeeker** [comment]
Here is an example of what I'm trying to achieve https://jsfiddle.net/dhn4kb5p/3/
When I change the value inside first input, it updates slider "from" but input2 value stays the same.

**Comment by IonDen** [comment]
You forgot about `onUpdate` callback, demo:
https://jsfiddle.net/o2dzns56/

**Comment by TheEssenceSeeker** [comment]
I see. Thank you!
