### ISSUE TITLE
ES6 imports problem

### ISSUE THREAD

**Issue by Ruala** [IonDen/ion.rangeSlider#670]
Specify the jQuery in peerDependencies but not  in  dependencies, please.
Otherwise plugin imports in different jquery instance.

Problem description from the stackoverflow.
https://stackoverflow.com/questions/44499550/jquery-plugins-giving-errors-ionrangeslider-not-a-function

**Comment by IonDen** [comment]
Will push the fix soon

**Comment by IonDen** [comment]
Fixed in 2.3.1
