### ISSUE TITLE
prettify show key

### ISSUE THREAD

**Issue by apurbajnu** [IonDen/ion.rangeSlider#676]
is it possible that the in prettify handler shows incremental key but the label will be as it is? Thanks for your great effort.  You are really Awesome. 

keys ["0", "200", "1049", "2100", "3500", "5450"]
values ["Guardian", " Brave", " Heroic", "  Fabled", " Mythic", " Legend"]

**Comment by IonDen** [comment]
Hi, it is not possible. But where is a workaround to add custom labels:
http://ionden.com/a/plugins/ion.rangeSlider/showcase.html#a_marks

**Comment by apurbajnu** [comment]
Thanks for your response. I have used this one already. But the issue is it's not so perfect like prettify. I mean the point in the handler and the label just perfect when I am using prettify. But with this marker, there has some difference between this label and the marker. Is it possible with on change method I will change the Html of the handler with from to value?

**Comment by IonDen** [comment]
You can try, why not.

**Comment by apurbajnu** [comment]
I was able to make it almost like prettify by doing some tweak in "addMarks" method. Thank you very much. 

`    function addMarks($slider) {
                                var html = '',
                                    left = 0, labelContainer,
                                    labelWidth, labelWidthPercentage, fullRangerWidth,
                                    i;
                                $.each(marks, function (key, value) {

                                    left = convertToPercent(key);
                                    html += '<span class="mark" style="left: ' + left + '%">' + value + '</span>';

                                });

                                html = '<span class="mark-container">' + html + '</span>';

                                $slider.append(html);
                                html = $slider;



                                for (i = 0; i <Object.keys(marks).length; i++) {
                                    labelContainer = html.find('.mark-container .mark').eq(i);
                                    labelWidth = labelContainer.outerWidth();
                                    fullRangerWidth = html.find('.irs').outerWidth();
                                    labelWidthPercentage = labelWidth * (100 / fullRangerWidth);
                                    labelWidthPercentage = labelWidthPercentage / 2;

                                   // if (labelWidthPercentage !== Number.POSITIVE_INFINITY) {
                                        console.log(labelWidthPercentage)
                                        //label.style.marginLeft = -this.coords.big_x[i] + "%";
                                        labelContainer.css('margin-left', -labelWidthPercentage+"%");
                                   // }
                                }
                            }`
