### ISSUE TITLE
Ability to use double handle to split into 3 segments

### ISSUE THREAD

**Issue by yeldarby** [IonDen/ion.rangeSlider#682]
Similar to #381, it'd be great to be able to use the double handled slider to to split a value into three chunks. So the "selected" part isn't the "inside" or "outside" part, they're all "selected", just different sizes.

For example, to divide $100 between 3 people:
![image](https://user-images.githubusercontent.com/870796/74586249-b25f7f80-5020-11ea-894a-c630e03ff544.png)

I think all that'd be needed is the ability to style segments 1, 2, and 3 independently. I had a look at the DOM elements and it looks like the "background" bar is 1 element right now and the "selected" part is another. So I don't think you can do this with just CSS at the moment.

**Comment by yeldarby** [comment]
I was able to hack something together that'll work! https://jsfiddle.net/yeldarb/5L0og23t/31/

**Comment by IonDen** [comment]
Nice, great job!
