### ISSUE TITLE
Input value never changing

### ISSUE THREAD

**Issue by Richacinas** [IonDen/ion.rangeSlider#686]
Sorry if this is a duplicated of this other [issue](https://github.com/IonDen/ion.rangeSlider/issues/638).

I open a new one because I feel like nobody will get notifications on a closed one.

The problem is that my input value always shows the same, and sending my form the value is the same as well.

It never changes when the user moves the slider. Here is some of my code:

`<input type="range" name="valor-contenido" data-min="1000" data-max="1000000" data-step="100" data-from="2000" value="2000" class="wpcf7-form-control wpcf7-range wpcf7-validates-as-required wpcf7-validates-as-number full-width" aria-required="true" aria-invalid="false">`

And the slider initialization:

`$('input[name=valor-contenido]').ionRangeSlider({ skin: "round", onChange: function (data) { console.log(data.input[0].value); //THIS IS ALWAYS --> 100 console.dir(data); } });`

**Comment by IonDen** [comment]
As I said in another story, please create the demo online. Probably you are doing something wrong with names or something.

Use this link to create the demo: https://jsfiddle.net/IonDen/uqs7njp9/

**Comment by Richacinas** [comment]
Hi there:

Here you can find an example. Please, pay attention to the input, because I'm thinking that could be the cause of the problem.

Everything works great if the input is a **type text**, but using a **type range causes the input value to never change...**

https://jsfiddle.net/szqw6n4g/

**Comment by IonDen** [comment]
Hi, of course it should use type `text`.

Type `range` is reserved for HTML5 range element and should not be used here. It has its own logic and not supported by older browsers.

**Comment by Richacinas** [comment]
Well.. there is so many range sliders out there that precisely work with `input range`, actually, usually they only work with that type of input. It makes sense, what these sliders are rendering is exactly what an `input range` does in a native way.

Besides, the support is massive:

![image](https://user-images.githubusercontent.com/7046504/77296986-e8abb100-6ce8-11ea-8e8a-d8504be4b884.png)


I don't know if by 

> not supported by older browsers

You mean IE8&IE9. I consider those browsers out of the game for such a long time, they are not even older browsers anymore.

**Comment by IonDen** [comment]
Remember 2 things:
1. Type `range` supports only 1 handle and 1 value. So in case of 2 handles it is out of game.
2. This plugin is developed for 9+ years already and of course it has IE8+ support.

In version 3.x I will drop old IE support of course, but not for 2.x version.

**Comment by Richacinas** [comment]
Ok perfect! thanks for all your help @IonDen.

**Comment by rogergerecke** [comment]
> Hi, of course it should use type `text`.
> 
> Type `range` is reserved for HTML5 range element and should not be used here. It has its own logic and not supported by older browsers.

Please this point to doc
this help me
