### ISSUE TITLE
Slider positions in two point slider overlap initially

### ISSUE THREAD

**Issue by ninjakx** [IonDen/ion.rangeSlider#711]
Initially they overlap with each other but when I click it on them they became far apart.
Those two slider pointer should be on the ends. But I don't know why they are showing this behaviour

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/29797787/84594681-a326fc00-ae71-11ea-91c5-0d5aee360879.gif)

**Code + Demo:**
https://blockbuilder.org/ninjakx/38a5227c6f0338afe2e14cb644b27d79

**Comment by IonDen** [comment]
Hi, this could happen if slider was initialized inside hidden div (like display:none) and then shown only.
To avoid this, you should call sliders update method on it shown, or rebuild it.
