### ISSUE TITLE
How to remove space in here?

### ISSUE THREAD

**Issue by nguyenvo123** [IonDen/ion.rangeSlider#718]
![image](https://user-images.githubusercontent.com/22131755/87913495-6d40ed00-ca99-11ea-8347-0fef145633bc.png)
1 000 -> 1000

**Comment by srajpal** [comment]
you can use prettify_enabled

```
$("#demo_0").ionRangeSlider({
   min:100,
   max:1000,
   from:550,
   prettify_enabled:false
});
```
