### ISSUE TITLE
Dynamic values - figuring out how to update on change

### ISSUE THREAD

**Issue by tmeuze** [IonDen/ion.rangeSlider#734]
I apologize if this has already been asked - I cannot find an exact duplicate of my question. I'm brand new to Javascript. I have two working sliders, and I want to be able to dynamically set the "max" value of slider2 to the current value of slider1. I have `var actualQty1` , where `actualQty1 = $('#option1SingleQty').val();` . I have the following configuration for slider2:
```
	var $range5 = $('#option5SingleRangeSlider'),
		$input5 = $('#option5SingleQty'),
		instance5,
		min5 = 0,
		max5 = 250;

	$range5.ionRangeSlider({
		skin: 'round',
		type: 'single',
		min: min5,
		max: actualQty1, 
		from: 0,
		step: 1,
		hide_min_max: true,
		onStart: function (data) {
			$input5.prop('value', data.from);
		},
		onChange: function (data) {
			$input5.prop('value', data.from);
			if (!singleOption5IsChecked) {
				activateSingleOption('option5Single');
			}
			updateSummary();
			reValidateTotal();
			saveState();
		}
	});
```
The above works statically - making the default value of slider1 == the max value of slider2. However, the max value does not update when slider1 is changed. Can someone tell me what I'm missing that will update the value on a change? My understanding is this is what callbacks are used for, but I'm not sure how to implement one here. 

I have the full code hosted here, if it helps:
JS: https://pastebin.com/NyTdRacd 
HTML: https://pastebin.com/04d7HhFH 

Thank you for any insight

**Comment by IonDen** [comment]
Hi, here is the demo of 1 slider controlling MAX of another:
https://jsfiddle.net/IonDen/f1t6qpx0/

**Comment by tmeuze** [comment]
@IonDen Brilliant, that worked! Thank you so much for your help!
