### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by TukuToi** [IonDen/ion.rangeSlider#736]
Hi, we plan to use this plugin to create some date sliders (I have already implemented a first mockup of it and works just fine and great).
Also, what was utmost important, no issues with big numbers like UNIX timestamps like so many other Range Plugins have!

Great.
But now I realised translations is only available for a few languages?
Could I somehow localise all date strings to lets say French?

I would also be willing to push this to your repo once finalised, I could provide localisation in IT< FR<DE<ES<PT
But I am not sure how'd have to add these additional languages to the plugin itself so I can just call the Locale in the setup like so:
`var lang = "fr-FR";`

Thanks for any hints, and please let me know if I can contribute with localisation - I have access to several (professional) translators (myself and others), and we are happy to contribute.

**Comment by IonDen** [comment]
Hello, actually for translation I'm using native JavaScript `toLocaleDateString` API.
You could read more about it here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

**Comment by TukuToi** [comment]
Silly me, true!
I just needed to pass the `fr-FR` key and it worked.

Sorry for the trouble.
