### ISSUE TITLE
Modify the step with jquery

### ISSUE THREAD

**Issue by Stono** [IonDen/ion.rangeSlider#739]
Hey, 
I have some DOM events which mean i need to update the sliders step value with jQuery.
I can't find any way to do this with the slider object.  Could anyone point me in the right direction?
Thanks

**Comment by IonDen** [comment]
Could you please specify your question?

If you want to set step parameter, just set it like this: `step: 10`
If you want update step parameter of already created slider instance - you should call `update` method, like on this demo:
http://ionden.com/a/plugins/ion.rangeSlider/demo_interactions.html#a_methods

**Comment by Stono** [comment]
Thank you so much, I some how missed the ability to dynamically update an existing slider!

**Comment by Stono** [comment]
confirmed this works a treat, thank you for your help.
