### ISSUE TITLE
Slider with % AND dynamic value - can't seem to get prettify to work

### ISSUE THREAD

**Issue by aximuseng** [IonDen/ion.rangeSlider#741]
I have an existing slider with data attributes like this:

`min: 0, max: 100, step: 1, postfix: '%'`

I would like to have the slider display like this (I manually edited the HTML to show this):

![Screen Shot 2021-02-27 at 1 22 08 PM](https://user-images.githubusercontent.com/51976859/109399274-2bb1d380-78ff-11eb-97d5-c2b1f23cb28e.png)

The page has multiple sliders in a nested form so each has an associated base multiplier amount i.e. $10,000 x 50% and the slider handle would dynamically update.

My thought here is that I do this:

`min: 0, max: 100, step: 1, value: 10000`

then I tried this:

```
$(".myclass").ionRangeSlider()({
  min: 0,
  max: 100,
  step: 1,
  value: $(this).data('value'),
  prettify: function(n) {
    return n + '%' + ' ($' + value * n / 100 + ')';
  }
});
```

and get:

![Screen Shot 2021-02-27 at 2 12 27 PM](https://user-images.githubusercontent.com/51976859/109400427-daf1a900-7905-11eb-859d-f0ce2dabbda1.png)

I will admit to not being the most proficient at JS so I may be missing something minor / obvious here.  After some digging I think I am not accessing the value data attribute.  I also tried this (and realized I need to turn my string to a float):

```
$(".myclass").ionRangeSlider()({
  min: 0,
  max: 100,
  step: 1,
  prettify: function(n) {
    return n + '%' + ' ($' + parseFloat($(this).data('value')) * n / 100 + ')';
  }
});
```

**Comment by IonDen** [comment]
Hi, here is the demo:
https://jsfiddle.net/qu8jsmy6/

**Comment by aximuseng** [comment]
That works except in my case the `totalInDollars` value is different for each slider on the page.  This is why I tried to add a data attribute to each slider and then reference it with `$(this)`.

**Comment by IonDen** [comment]
Yes of course you could get totalInDollars from data attribute. Don't forget to parseFloat it.

**Comment by aximuseng** [comment]
Not sure how to do this then:

https://jsfiddle.net/jasper502/ck9yuxmj/4/

**Comment by IonDen** [comment]
You can't access slider via `$(this)` in prettify. Workaround:
https://jsfiddle.net/e2xzpoag/

**Comment by aximuseng** [comment]
Thanks - that looks like something I can work with 👍. Is direct access to the data attributes something that could be considered in a future release?  I think my example show where that would be valuable.

**Comment by IonDen** [comment]
Yes, I will think about it.

**Comment by aximuseng** [comment]
I ended up settling on this (bac is my data attribute value):

$('.js-range-slider').each(function() {
  var bac;
  bac = parseFloat($(this).data('bac'));
  return $(this).ionRangeSlider({
    prettify: function(n) {
      var current;
      current = Math.round(bac / 100 * n);
      return n + '%' + ' ($' + current + ')';
    }
  });
});
