### ISSUE TITLE
Can I close onChange?

### ISSUE THREAD

**Issue by acetas** [IonDen/ion.rangeSlider#743]
Hello,

How can I solve this problem?

https://youtu.be/J9EXh49-7y8

**Comment by IonDen** [comment]
You could use `onFinish` instead if you want to fetch data only once.
Is that your question?

**Comment by acetas** [comment]
first of all thank you for the answer @IonDen 

I'm trying, but onChange is still valid because ajax is triggered whenever there is a change on the form.

**Comment by IonDen** [comment]
You mean you are listening to INPUTs 'change' event right?

In that case you should just write your own workaround. For example:
```javascript
let timer; // first you create a variable for timer

input.addEvenListener('change', () => {
  // in a function similar to this one AJAX is called every time then change happened
  // to avoid this behaviour, you will need to create a timer
  // this technique is called Debounce

  clearTimeout(timer); // clear previous call

  timer = setTimeout(() => {
    // YOU AJAX CALL SHOULD BE HERE
    // this technique ensures that only last call in a raw will be executed
  }, 300);
});
```

**Comment by acetas** [comment]
yes it works. For now, I'll go ahead with this and look for another permanent method later. 

Thank you @IonDen
