### ISSUE TITLE
Slider stuck on min value

### ISSUE THREAD

**Issue by katmelen** [IonDen/ion.rangeSlider#746]
I have created a slider using standard code off of the Poitnet website. Code is as follows:
        skin: "round",
        grid: true,
        min: 100000,
        max: 2000000,
        from: 600000,
       postfix: "+/- 20K",
       prefix: "$",
Even though I set "from:600000", slider starts at min: 100000.
Also, cannot move slider.

**Comment by Rabbit523** [comment]
![image](https://user-images.githubusercontent.com/68119978/113223866-b39f4a80-92bc-11eb-98b9-a407bd85db51.png)
I made a simple html file using that plugin.
As you can see on the screenshot, there is no problem.
<!DOCTYPE html>
<html>
	<head>
	<title>Page Title</title>
	  
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/css/ion.rangeSlider.min.css"/>

	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/js/ion.rangeSlider.min.js"></script>
	</head>
<body>

 <input type="text" class="js-range-slider" name="my_range" value="" />
 <script>
 $(".js-range-slider").ionRangeSlider({
	skin: "round",
	grid: true,
	min: 100000,
	max: 2000000,
	from: 600000,
	postfix: "+/- 20K",
	prefix: "$",
 });
 </script>
</body>
</html>

**Comment by IonDen** [comment]
You could always check your setup in playground: https://jsfiddle.net/IonDen/uoysqxk1/
It is working as expected. @katmelen @Rabbit523

**Comment by Rabbit523** [comment]
yeah, actually, there is no problem. @IonDen
