### ISSUE TITLE
Comma causes the slider to go to zero.

### ISSUE THREAD

**Issue by arnonrdp** [IonDen/ion.rangeSlider#747]
I believe I found a **low priority bug**. I have a slider with number inputs. And I am replacing dots for commas on decimals. To do it I am using this:

```js
prettify: function (num) {
  var n = num.toString();
  n = n.replace(".", ",");
  return n.replace(/(\d{1,3}(?=(?:\d\d\d)+(?!\d)))/g, "$1\.");
}
```

But for some reason when a type a comma on input, the slider immediately leads to zero. You can check it [right here](http://myoption.com.br/) on the website I am working on.

**Comment by IonDen** [comment]
You are using prettify function wrong.
```javascript
prettify: function (num) {
  var n = num.toString();
  return n.replace(".", ",");
}
```
