### ISSUE TITLE
how to change the color of the bar and the circle

### ISSUE THREAD

**Issue by FinLoik** [IonDen/ion.rangeSlider#754]
I changed the colors in css file, tried to set skin_color in js file and nothing. Please tell me how can i change colour, I do not wanna create a new bar style, just change colour.
Thanks.

**Comment by IonDen** [comment]
You should alter skin CSS file for that.

**Comment by FinLoik** [comment]
> You should alter skin CSS file for that.

Thanks for the answer, I figured it out. The fact is that I had html connected to the library of not my file but uploaded to another library, I downloaded and specified the path to the library and everything worked.
