### ISSUE TITLE
Cannot read property 'update' of undefined

### ISSUE THREAD

**Issue by pRieStaKos** [IonDen/ion.rangeSlider#755]
I got three Ion.RangeSlider on a WHMCS template and I cannot set one with min/max and disable and hide the other two with update.

![image](https://user-images.githubusercontent.com/4584686/123642903-7c452900-d82c-11eb-910c-fc3d1122e48f.png)

Code: https://codeshare.io/6ppmvm

**Ion.RangeSlider** version 2.0.13 Build: 335 ( i cannot update).

Any suggestions on why update is returning error and won't update the sliders ?

**Comment by IonDen** [comment]
You need to double check that constructions like these `slider = $('div[class^="opnmprimaryhighavailability' + $.trim(selected) + '"]').find('input').data("ionRangeSlider");` are returning to you instances of slider and not `undefined`

If it returns `undefined` - this means you are searching these elements wrong and need to debug this line of code.

**Comment by pRieStaKos** [comment]
> You need to double check that constructions like these `slider = $('div[class^="opnmprimaryhighavailability' + $.trim(selected) + '"]').find('input').data("ionRangeSlider");` are returning to you instances of slider and not `undefined`
> 
> If it returns `undefined` - this means you are searching these elements wrong and need to debug this line of code.

Issue is on first `slider.update`. Not the second slider
![Capture](https://user-images.githubusercontent.com/4584686/124623656-d2e1e100-de84-11eb-8acd-a15e014ca9d9.PNG)

**Comment by IonDen** [comment]
Not sure that do you mean, could you create the demo?

**Comment by pRieStaKos** [comment]
I managed to fix this. Reposition the custom script and its working, but form is still posting the disabled sliders. How can I prevent post of the disabled sliders ?

**Comment by IonDen** [comment]
It should not post disabled sliders in form. Please check this demo:
https://jsfiddle.net/IonDen/esL4aqtp/

and double check that you do everything correctly.

**Comment by pRieStaKos** [comment]
Thank you. I found the solution. On WHMCS ionRangeSlider is disabled, but WHMCS wants the other slider values to be passed on the order form.
