### ISSUE TITLE
Ion Ranage Slider Vertical

### ISSUE THREAD

**Issue by latinojoel** [IonDen/ion.rangeSlider#84]
The slider just works in horizontal mode.
I know this issue can be very hard to implement in html but will be a great nice have. Are you considering?

**Comment by smartdub** [comment]
@IonDen : When using the CSS `transform:rotate(270deg);` on the parent container of `type="double"` I found issues with 

1. `<span.irs-from>` and `<span.irs-to>` labels that need to **not** rotate,
2. the `mouseout` is buggy after the first slide got moved.

**Comment by IonDen** [comment]
@smartdub, good point, but i never tested or designed slider to handle this.
