### ISSUE TITLE
How to change the min-max separator (;)

### ISSUE THREAD

**Issue by mayeenulislam** [IonDen/ion.rangeSlider#90]
The plugin is returning the value (min and max) with a separator 'semicolon' (`;`) by default. In URL which is giving an awkward result `%3B`. I'm trying to modify it with a 'hyphen' (`-`) with the following code, but it's not working.

```
onChange: function(obj) {
    var some = $("#price-range").val().replace(";", "-");
    $("#price-range").val(some);
}
```

Is there a default way to change the split item (`;`) with something else (like `-`)

**Comment by Aloha276** [comment]
I tried this: 
$("#price").ionRangeSlider({ input_values_separator: "to" });
and its works.
